import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { Store } from '../src/main/store';
import { Vault } from '../src/main/vault';
test('vault real conserva identidade, Markdown, conflito e buffer após falha de escrita', () => {
  fs.mkdirSync('.local', { recursive: true });
  const dir = fs.mkdtempSync(path.resolve('.local/vault-test-'));
  let store = new Store(path.join(dir, 'data'));
  try {
    const root = path.join(dir, 'vault'); fs.mkdirSync(root);
    let vault = new Vault(store); vault.selectRoot(root);
    const subject = store.createSubject({ name: 'Fixture', color: 'sage' });
    const doc = vault.create({ subjectId: subject.id, title: 'Nota fixture' });
    const text = doc.text + fs.readFileSync('tests/fixtures/compatibility.md', 'utf8');
    const saved = vault.save({ id: doc.ref.id, text, hash: doc.hash }); assert.equal(saved.state, 'saved');
    assert.equal(fs.readFileSync(vault.resolve(doc.ref.path), 'utf8'), text);
    store.close(); store = new Store(path.join(dir, 'data')); vault = new Vault(store);
    const reopened = vault.open(doc.ref.id); assert.equal(reopened.text, text); assert.equal(reopened.ref.id, doc.ref.id);
    const local = text.replace('Esta frase pode mudar.', 'Edição local.');
    const external = text.replace('Esta frase pode mudar.', 'Edição externa.');
    fs.writeFileSync(vault.resolve(doc.ref.path), external);
    const conflict = vault.save({ id: doc.ref.id, text: local, hash: reopened.hash });
    assert.equal(conflict.state, 'conflict');
    assert.equal(vault.open(doc.ref.id).text, external); assert.equal(vault.open(doc.ref.id).draft?.text, local);
    const parent = path.dirname(vault.resolve(doc.ref.path)); const moved = parent + '-moved';
    assert.ok(parent.startsWith(root + path.sep) && moved.startsWith(root + path.sep));
    fs.renameSync(parent, moved); fs.writeFileSync(parent, 'bloqueio controlado de fixture');
    assert.throws(() => vault.save({ id: doc.ref.id, text: local, hash: reopened.hash }));
    assert.equal(store.db.prepare('SELECT text FROM drafts WHERE note_id=?').get(doc.ref.id)?.text, local);
    fs.unlinkSync(parent); fs.renameSync(moved, parent);
    assert.equal(vault.save({ id: doc.ref.id, text: local, hash: vault.open(doc.ref.id).hash }).state, 'saved');
    for (const escape of ['../outside.md', '/outside.md', 'C:/outside.md', '..\\outside.md']) assert.throws(() => vault.resolve(escape));
    const outside = path.join(dir, 'outside'); fs.mkdirSync(outside); fs.writeFileSync(path.join(outside, 'secret.md'), 'fixture externa');
    fs.symlinkSync(outside, path.join(root, 'junction'), 'junction'); assert.throws(() => vault.resolve('junction/secret.md'), /simbólicos/);
    assert.equal(fs.readFileSync(path.join(outside, 'secret.md'), 'utf8'), 'fixture externa');
    const importedPath = path.join(root, 'imported.md'); fs.copyFileSync('tests/fixtures/compatibility.md', importedPath);
    const imported = vault.import(subject.id, importedPath); assert.ok(imported.text.includes('custom_unknown: preserve-me'));
    assert.equal(vault.import(subject.id, importedPath).ref.id, imported.ref.id);
    const bomPath = path.join(root, 'bom.md');
    const bomFixture = '\uFEFF' + fs.readFileSync('tests/fixtures/compatibility.md', 'utf8').replaceAll('\n', '\r\n');
    fs.writeFileSync(bomPath, bomFixture);
    const bomDoc = vault.import(subject.id, bomPath);
    assert.ok(bomDoc.text.startsWith('\uFEFF---\r\n')); assert.ok(bomDoc.text.includes('custom_unknown: preserve-me\r\n'));
    assert.equal(vault.save({ id: bomDoc.ref.id, text: bomDoc.text, hash: bomDoc.hash }).state, 'saved');
    assert.equal(fs.readFileSync(bomPath, 'utf8'), bomDoc.text);
    fs.copyFileSync(importedPath, path.join(root, 'duplicate.md'));
    assert.throws(() => vault.import(subject.id, path.join(root, 'duplicate.md')), /Outro|Outra/);
    const invalidIdentity = `---\nstudy_id: ${'-'.repeat(36)}\nstudy_subject: ${subject.id}\n---\n# ID inválido\n`;
    const invalidPath = path.join(root, 'invalid-id.md'); fs.writeFileSync(invalidPath, invalidIdentity);
    assert.throws(() => vault.import(subject.id, invalidPath), /ID inválido/); assert.equal(fs.readFileSync(invalidPath, 'utf8'), invalidIdentity);
    vault.draft({ id: doc.ref.id, text: local, hash: vault.open(doc.ref.id).hash });
    const auditCount = Number(store.db.prepare('SELECT COUNT(*) AS n FROM audit_events').get()?.n);
    const discarded = vault.discard(doc.ref.id); assert.equal(discarded.draft, null);
    assert.equal(discarded.text, local);
    const event = store.db.prepare('SELECT action,entity_id AS id,outcome FROM audit_events ORDER BY rowid DESC LIMIT 1').get();
    assert.deepEqual({ ...event }, { action: 'note.draft-discard', id: doc.ref.id, outcome: 'ok' });
    assert.equal(Number(store.db.prepare('SELECT COUNT(*) AS n FROM audit_events').get()?.n), auditCount + 1);
    assert.ok(fs.readdirSync(path.join(dir, 'data', 'recovery')).some(name => name.startsWith('draft-') && fs.readFileSync(path.join(dir, 'data', 'recovery', name), 'utf8') === local));
  } finally { store.close(); }
});
