import { z } from 'zod';
import { workspaceLayout, defaultWorkspace, workspaceTabs, defaultWorkspaceTabs, workspaceFromLegacy } from './workspace';
export const themeInput = z.enum(['editorial', 'olive', 'graphite', 'midnight']);
const featuredProjectsInput = z.array(z.uuid()).max(40).refine(ids => new Set(ids).size === ids.length, 'Projetos repetidos');
const nameInput = z.string().trim().max(80).regex(/^[^\u0000-\u001f\u007f]*$/);
export const preferenceInput = z.strictObject({ name: nameInput.optional(), theme: themeInput.optional(), animations: z.boolean().optional(), editorialBackground: z.boolean().optional(), featuredProjectIds: featuredProjectsInput.optional(), workspaceLayout:workspaceLayout.optional(), workspaceTabs:workspaceTabs.optional() }).refine(value => Object.keys(value).length > 0 && Object.values(value).every(item => item !== undefined));
export const preferencesSchema = z.strictObject({ name: nameInput, theme: themeInput, animations: z.boolean(), editorialBackground: z.boolean().default(true), photo: z.string().max(512 * 1024).regex(/^data:image\/png;base64,[A-Za-z0-9+/]+={0,2}$/).nullable(), featuredProjectIds: featuredProjectsInput.default([]),workspaceLayout:workspaceLayout.default(defaultWorkspace),workspaceTabs:workspaceTabs.optional() }).transform(value => ({ ...value, workspaceTabs: value.workspaceTabs ?? workspaceFromLegacy(value.workspaceLayout) }));
export type Preferences = z.infer<typeof preferencesSchema>;
export const defaultPreferences: Preferences = { name: '', theme: 'editorial', animations: true, editorialBackground: true, photo: null, featuredProjectIds: [],workspaceLayout:defaultWorkspace,workspaceTabs:defaultWorkspaceTabs };
export const PHOTO_LIMIT = 5 * 1024 * 1024;
export const photoInput = z.strictObject({ bytes: z.custom<Uint8Array>(value => value instanceof Uint8Array && value.byteLength > 0 && value.byteLength <= PHOTO_LIMIT) });
export const folderInput = z.strictObject({ folder: z.enum(['data', 'vault']) });
export type AppManagement = { dataDirectory: string; vault: string | null; counts: { subjects: number; notes: number; materials: number; videos: number; projects: number; drafts: number }; databaseBytes: number };
