import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { AppError } from '../shared/contracts';
import { activitySchema,prepareActivityInput,responseInput,requestRef,activityRef,quizStartInput,quizAnswerInput,quizFinishInput,activityCardInput,validateActivity,generationPrompt,correctionPrompt,parseActivityJson,type ActivityRequest,type ActivitySummary,type ActivityPayload,type ActivityCard,type QuizSession,type SourceContext } from '../shared/study-activity';
import { Store } from './store';
import { Study } from './study';
import { ActivitySources,contentHash } from './activity-sources';

function canonical(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';return '{'+Object.keys(value).sort().map(key=>JSON.stringify(key)+':'+canonical((value as Record<string,unknown>)[key])).join(',')+'}';}
export class StudyActivities {
  constructor(readonly store:Store,readonly sources:ActivitySources,readonly study:Study,readonly now=()=>Date.now()){}
  async prepare(raw:z.input<typeof prepareActivityInput>):Promise<ActivityRequest>{const input=prepareActivityInput.parse(raw),subject=this.store.requireSubject(input.subjectId);
    if(new Set(input.sources.map(s=>`${s.kind}:${s.id}`)).size!==input.sources.length)throw new AppError('DUPLICATE_SOURCE','Selecione cada fonte uma única vez.');
    const sources=[];for(const source of input.sources)sources.push(await this.sources.read(subject.id,source));
    const body=sources.flatMap(s=>s.chunks.map(c=>c.text.replace(/^\uFEFF?---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/,''))).join('\n');if((body.match(/\p{L}/gu)?.length??0)<20)throw new AppError('INSUFFICIENT_TOPIC','Não há texto útil suficiente para identificar um tema. Selecione materiais com conteúdo de estudo.');
    const snapshotId=randomUUID(),id=randomUUID(),packet={id:snapshotId,subject:subject.name,sources};
    const request:ActivityRequest={id,subjectId:subject.id,snapshotId,type:input.type,difficulty:input.difficulty,prompt:'',promptLimit:input.promptLimit,packet,createdAt:this.now(),sourceSizes:sources.map(s=>({title:s.title,characters:JSON.stringify(s).length})).sort((a,b)=>b.characters-a.characters)};request.prompt=generationPrompt(request);
    this.store.transaction(()=>{this.store.requireSubject(subject.id);this.store.db.prepare('INSERT INTO activity_snapshots VALUES(?,?,?,?)').run(snapshotId,subject.id,JSON.stringify(packet),request.createdAt);this.store.db.prepare('INSERT INTO activity_requests(id,subject_id,snapshot_id,type,difficulty,prompt,prompt_limit,created_at) VALUES(?,?,?,?,?,?,?,?)').run(id,subject.id,snapshotId,input.type,input.difficulty,request.prompt,input.promptLimit,request.createdAt);this.store.audit('activity.prepare',id,'ok');});return request;
  }
  requests(subjectId:string):Omit<ActivityRequest,'packet'|'prompt'|'sourceSizes'>[]{this.store.requireSubject(subjectId);return this.store.db.prepare('SELECT id,subject_id subjectId,snapshot_id snapshotId,type,difficulty,prompt_limit promptLimit,created_at createdAt FROM activity_requests WHERE subject_id=? ORDER BY rowid DESC').all(subjectId) as unknown as Omit<ActivityRequest,'packet'|'prompt'|'sourceSizes'>[];}
  request(raw:z.infer<typeof requestRef>):ActivityRequest{const input=requestRef.parse(raw);this.store.requireSubject(input.subjectId);const row=this.store.db.prepare('SELECT r.id,r.subject_id subjectId,r.snapshot_id snapshotId,r.type,r.difficulty,r.prompt,r.prompt_limit promptLimit,r.created_at createdAt,r.response originalResponse,s.packet FROM activity_requests r JOIN activity_snapshots s ON r.snapshot_id=s.id AND r.subject_id=s.subject_id WHERE r.id=? AND r.subject_id=?').get(input.requestId,input.subjectId);if(!row)throw new AppError('REQUEST_NOT_FOUND','Pedido não encontrado nesta matéria e neste perfil local.');const packet=JSON.parse(String(row.packet));return {...row,packet,sourceSizes:packet.sources.map((s:unknown)=>({title:(s as {title:string}).title,characters:JSON.stringify(s).length})).sort((a:{characters:number},b:{characters:number})=>b.characters-a.characters)} as ActivityRequest;}
  validate(raw:z.infer<typeof responseInput>){const input=responseInput.parse(raw),request=this.request({subjectId:input.subjectId,requestId:input.requestId}),report=validateActivity(input.text,request);if(!report.valid){const candidate=parseActivityJson(input.text).value as {requestId?:unknown}|undefined;if(typeof candidate?.requestId==='string'&&candidate.requestId!==request.id){const other=this.store.db.prepare('SELECT r.id,r.subject_id subjectId,s.name FROM activity_requests r JOIN subjects s ON s.id=r.subject_id WHERE r.id=?').get(candidate.requestId);if(other){report.matchingRequestId=String(other.id);report.matchingSubjectId=String(other.subjectId);report.matchingSubjectName=String(other.name);}}}
    this.store.transaction(()=>{this.store.db.prepare('UPDATE activity_requests SET response=? WHERE id=? AND subject_id=?').run(input.text,input.requestId,input.subjectId);this.store.audit('activity.validate',input.requestId,report.valid?'ok':'invalid');});const {payload:_payload,...safe}=report;return safe;
  }
  correction(raw:z.infer<typeof responseInput>){const input=responseInput.parse(raw),request=this.request({subjectId:input.subjectId,requestId:input.requestId}),report=this.validate(input);if(report.valid)throw new AppError('ALREADY_VALID','O JSON já é válido. Confira a prévia e importe.');return correctionPrompt(request,input.text,report);}
  promptToCopy(raw:z.infer<typeof requestRef> & {mode:'prompt'|'correction';text?:string}):{text:string;short:boolean}{const request=this.request({subjectId:raw.subjectId,requestId:raw.requestId});const result=raw.mode==='prompt'?{text:request.prompt,short:false}:this.correction({subjectId:raw.subjectId,requestId:raw.requestId,text:raw.text??''});if(result.text.length>request.promptLimit)throw new AppError('PROMPT_LIMIT',`O texto tem ${result.text.length} caracteres e excede o limite ${request.promptLimit}. Desmarque os maiores materiais e prepare outro pedido.`);return result;}
  import(raw:z.infer<typeof responseInput>):{activity:ActivitySummary;existing:boolean}{const input=responseInput.parse(raw),request=this.request({subjectId:input.subjectId,requestId:input.requestId}),report=validateActivity(input.text,request);if(!report.valid||!report.payload)throw new AppError('ACTIVITY_INVALID','A resposta ainda contém problemas. Valide novamente antes de importar.');const payload=report.payload,hash=contentHash(canonical(payload));return this.store.transaction(()=>{
    this.request({subjectId:input.subjectId,requestId:input.requestId});const existing=this.store.db.prepare('SELECT id FROM study_activities WHERE request_id=? AND payload_hash=?').get(request.id,hash);if(existing)return {activity:this.summary(String(existing.id),input.subjectId),existing:true};
    const id=randomUUID(),revision=Number(this.store.db.prepare('SELECT count(*) n FROM study_activities WHERE request_id=?').get(request.id)!.n)+1;this.store.db.prepare('INSERT INTO study_activities VALUES(?,?,?,?,?,?,?,?)').run(id,request.id,hash,JSON.stringify(payload),payload.type,payload.title,revision,this.now());
    if(payload.type==='flashcards')for(const item of payload.items){const ref=item.provenance.references.map(r=>request.packet.sources.find(s=>s.sourceId===r.sourceId)).find(s=>s?.kind==='note');const noteId=ref&&this.store.db.prepare('SELECT id FROM notes WHERE id=? AND subject_id=?').get(ref.id,input.subjectId)?ref.id:null;
      const card=this.study.createInTransaction({subjectId:input.subjectId,noteId,question:item.front,answer:item.back,excerpt:item.explanation});this.store.db.prepare('INSERT INTO activity_cards VALUES(?,?,?)').run(id,item.id,card.id);}
    this.store.audit('activity.import',id,'ok');return {activity:this.summary(id,input.subjectId),existing:false};});
  }
  private record(raw:z.infer<typeof activityRef>){const input=activityRef.parse(raw);this.store.requireSubject(input.subjectId);const row=this.store.db.prepare('SELECT a.*,r.subject_id subjectId,r.snapshot_id snapshotId FROM study_activities a JOIN activity_requests r ON a.request_id=r.id WHERE a.id=? AND r.subject_id=?').get(input.activityId,input.subjectId);if(!row)throw new AppError('ACTIVITY_NOT_FOUND','Atividade não encontrada nesta matéria.');return {row,payload:activitySchema.parse(JSON.parse(String(row.payload)))};}
  private summary(id:string,subjectId:string):ActivitySummary{const {row,payload}=this.record({activityId:id,subjectId});return {id,requestId:String(row.request_id),title:payload.title,type:payload.type,difficulty:payload.difficulty,revision:Number(row.revision),createdAt:Number(row.created_at),supplements:payload.items.filter(i=>i.provenance.basis!=='material').length};}
  list(subjectId:string):ActivitySummary[]{this.store.requireSubject(subjectId);return this.store.db.prepare('SELECT a.id FROM study_activities a JOIN activity_requests r ON a.request_id=r.id WHERE r.subject_id=? ORDER BY a.rowid DESC').all(subjectId).map(row=>this.summary(String(row.id),subjectId));}
  cards(raw:z.infer<typeof activityRef>):ActivityCard[]{const input=activityRef.parse(raw),{payload}=this.record({subjectId:input.subjectId,activityId:input.activityId});if(payload.type!=='flashcards')throw new AppError('ACTIVITY_TYPE','Esta atividade é um questionário.');const cards=this.study.cards(input.subjectId),rows=this.store.db.prepare('SELECT item_id itemId,card_id cardId FROM activity_cards WHERE activity_id=?').all(input.activityId);return payload.items.map(item=>({...item,review:cards.find(c=>c.id===rows.find(r=>r.itemId===item.id)?.cardId)??null}));}
  rate(raw:z.infer<typeof activityCardInput>){const input=activityCardInput.parse(raw);const card=this.cards({subjectId:input.subjectId,activityId:input.activityId}).find(c=>c.id===input.itemId);if(!card?.review)throw new AppError('CARD_MISSING','O cartão de revisão foi removido. O conteúdo da atividade permanece disponível.');return this.study.review({subjectId:input.subjectId,id:card.review.id,version:input.version,rating:input.rating,operationId:input.operationId});}
  start(raw:z.input<typeof quizStartInput>):QuizSession{const input=quizStartInput.parse(raw),{payload}=this.record({subjectId:input.subjectId,activityId:input.activityId});if(payload.type!=='quiz')throw new AppError('ACTIVITY_TYPE','Esta atividade contém flashcards.');return this.store.transaction(()=>{const previous=this.store.db.prepare('SELECT id,finished_at FROM quiz_sessions WHERE activity_id=? ORDER BY rowid DESC LIMIT 1').get(input.activityId);if(previous&&(!input.restart||previous.finished_at===null))return this.session(String(previous.id),input.subjectId);const id=randomUUID();this.store.db.prepare('INSERT INTO quiz_sessions(id,activity_id,answers,started_at) VALUES(?,?,?,?)').run(id,input.activityId,'{}',this.now());this.store.audit('quiz.start',id,'ok');return this.session(id,input.subjectId);});}
  private sessionRow(id:string,subjectId:string){const row=this.store.db.prepare('SELECT s.* FROM quiz_sessions s JOIN study_activities a ON s.activity_id=a.id JOIN activity_requests r ON a.request_id=r.id WHERE s.id=? AND r.subject_id=?').get(id,subjectId);if(!row)throw new AppError('SESSION_NOT_FOUND','Tentativa não encontrada nesta matéria.');return row;}
  session(id:string,subjectId:string):QuizSession{const row=this.sessionRow(id,subjectId),{payload}=this.record({activityId:String(row.activity_id),subjectId});if(payload.type!=='quiz')throw new AppError('ACTIVITY_TYPE','Tentativa inválida.');const answers=JSON.parse(String(row.answers));const results=row.finished_at===null?null:{correct:payload.items.filter(q=>answers[q.id]===q.correctOptionId).length,total:10,percent:payload.items.filter(q=>answers[q.id]===q.correctOptionId).length*10,durationMs:Math.max(0,Number(row.finished_at)-Number(row.started_at)),items:payload.items.map(q=>({id:q.id,selected:answers[q.id],correctOptionId:q.correctOptionId,correct:answers[q.id]===q.correctOptionId,explanation:q.explanation,provenance:q.provenance}))};return {id,activityId:String(row.activity_id),version:Number(row.version),state:results?'finished':'running',answers,items:payload.items.map(({id,topic,question,options})=>({id,topic,question,options})),results};}
  answer(raw:z.infer<typeof quizAnswerInput>):QuizSession{const input=quizAnswerInput.parse(raw);return this.store.transaction(()=>{const row=this.sessionRow(input.sessionId,input.subjectId);if(row.finished_at!==null)throw new AppError('QUIZ_FINISHED','Esta tentativa já foi finalizada.');if(Number(row.version)!==input.version)throw new AppError('QUIZ_CHANGED','A tentativa mudou. Abra novamente para continuar.');const current=this.session(input.sessionId,input.subjectId);if(!current.items.some(q=>q.id===input.itemId))throw new AppError('ITEM_NOT_FOUND','Questão não encontrada.');const answers={...current.answers,[input.itemId]:input.optionId};this.store.db.prepare('UPDATE quiz_sessions SET answers=?,version=version+1 WHERE id=?').run(JSON.stringify(answers),input.sessionId);this.store.audit('quiz.answer',input.sessionId,'ok');return this.session(input.sessionId,input.subjectId);});}
  finish(raw:z.infer<typeof quizFinishInput>):QuizSession{const input=quizFinishInput.parse(raw);return this.store.transaction(()=>{const current=this.session(input.sessionId,input.subjectId);if(current.state==='finished')return current;if(current.version!==input.version)throw new AppError('QUIZ_CHANGED','A tentativa mudou. Abra novamente para continuar.');if(current.items.some(q=>!current.answers[q.id]))throw new AppError('QUIZ_INCOMPLETE','Responda às10questões antes de finalizar.');this.store.db.prepare('UPDATE quiz_sessions SET finished_at=?,version=version+1 WHERE id=?').run(this.now(),input.sessionId);this.store.audit('quiz.finish',input.sessionId,'ok');return this.session(input.sessionId,input.subjectId);});}
  async reference(subjectId:string,requestId:string,sourceId:string,chunkId:string):Promise<SourceContext>{const request=this.request({subjectId,requestId}),source=request.packet.sources.find(s=>s.sourceId===sourceId),chunk=source?.chunks.find(c=>c.id===chunkId);if(!source||!chunk)throw new AppError('REFERENCE_NOT_FOUND','Trecho não encontrado no snapshot.');return {title:source.title,status:await this.sources.status(subjectId,source),chunk,source:{kind:source.kind,id:source.id}};}
}
