import fs from 'node:fs';
const id = process.argv[2];
const outcome = process.argv[3] ?? 'em_andamento';
const note = process.argv[4] ?? 'Implementação iniciada; verificações em andamento.';
const folder = outcome === 'concluido' ? 'done' : 'doing';
const previous = ['todo', 'doing', 'done'].find(f => fs.existsSync(`docs/tasks/${f}/${id}.md`));
if (!previous) throw Error('Ticket não encontrado');
let ticket = fs.readFileSync(`docs/tasks/${previous}/${id}.md`, 'utf8').replace(/^status: .+$/m, `status: ${folder}`).replace(/^outcome: .+$/m, `outcome: ${outcome}`);
ticket += `\n### Checkpoint 02/10/2026\n\n${note} Tempo humano: não informado.\n`;
if (folder !== previous) fs.renameSync(`docs/tasks/${previous}/${id}.md`, `docs/tasks/${folder}/${id}.md`);
fs.writeFileSync(`docs/tasks/${folder}/${id}.md`, ticket);
let index = fs.readFileSync('docs/tasks/README.md', 'utf8').replace(`${previous}/${id}.md`, `${folder}/${id}.md`);
index = index.replace('Estado inicial: todas as 11 tarefas em todo.', 'Execução local da alpha iniciada em 02/10/2026; consulte os tickets e as evidências.');
fs.writeFileSync('docs/tasks/README.md', index);
const labels = { em_andamento: 'Em andamento', parcial: 'Parcial', bloqueado: 'Bloqueado', concluido: 'Concluído' };
let state = fs.readFileSync('docs/status/ALPHA_STATE.md', 'utf8').replace(new RegExp(`^\\| ${id} \\| .*? \\| .*? \\|`, 'm'), `| ${id} | ${folder} | ${labels[outcome]} |`);
state = state.replace(/## Próxima ação\r?\n[\s\S]*?(?=\r?\n## Tickets)/, `## Próxima ação\n\n${id}: ${note}\n`);
state = state.replace(/Setup\/documentação preparados\.[^\r\n]+/, 'Implementação local da alpha em execução no Windows nativo. Resultados por critério em docs/validation/ALPHA.md.');
const validation = fs.readFileSync('docs/validation/ALPHA.md', 'utf8');
const sectionStart = validation.indexOf(`## ${id} `);
const sectionEnd = validation.indexOf('\n## ', sectionStart + 1);
const section = validation.slice(sectionStart, sectionEnd < 0 ? undefined : sectionEnd);
const pending = [...section.matchAll(/^\| (C\d+) \| (?!aprovado)[^|]+\|/gm)].map(m => m[1]);
state = state.replace(new RegExp(`^(\\| ${id} \\| [^|]+ \\| [^|]+ \\| [^|]+ \\|)[^\\r\\n]+`, 'm'), `$1 ${pending.join(', ') || '—'} |`);
fs.writeFileSync('docs/status/ALPHA_STATE.md', state);
fs.appendFileSync('docs/status/RUN_LOG.md', `\n### 02/10/2026 — ${id}: ${labels[outcome]}\n\n${note}\n`);
