import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { _electron as electron } from 'playwright';
import { prepareFixture } from './test-fixture';
import { Store } from '../src/main/store';
import { Vault } from '../src/main/vault';
import { Desks } from '../src/main/desk';
import { Videos } from '../src/main/videos';
import { Annotations } from '../src/main/annotations';
import type { ActivityRequest, ActivityPayload } from '../src/shared/study-activity';

// Declared fixtures, real packaged Windows app/clipboard/PDF.js/SQLite. No AI provider call.
const fixture=prepareFixture('external-activities'),data=path.join(fixture.dir,'data');
const seed=new Store(data),vault=new Vault(seed);
const source=fs.readFileSync('tests/fixtures/activities/matter-a.md','utf8');
const a=vault.save({id:fixture.noteA.ref.id,hash:fixture.noteA.hash,text:fixture.noteA.text.split('# Nota A')[0]+source});
assert.equal(a.state,'saved');if(a.state==='saved')fixture.noteA=a.document;
const b=vault.save({id:fixture.noteB.ref.id,hash:fixture.noteB.hash,text:fixture.noteB.text.split('# Nota B')[0]+fs.readFileSync('tests/fixtures/activities/matter-b.md','utf8')});assert.equal(b.state,'saved');
const extra=vault.create({subjectId:fixture.a.id,title:'HTTP · complemento local'});
vault.save({id:extra.ref.id,hash:extra.hash,text:extra.text+'\nGET solicita um recurso; POST envia dados ao servidor. HTTP 200 indica sucesso.\n'});
const videos=new Videos(seed),annotations=new Annotations(seed,new Desks(seed),videos);
const video=videos.add({subjectId:fixture.a.id,title:'HTTP · aula anotada',url:'https://www.youtube.com/watch?v=M7lc1UVf-VE'});
annotations.addMoment({subjectId:fixture.a.id,videoId:video.id,seconds:42,text:'Anotação local: HTTP 404 indica que o recurso solicitado não foi encontrado.'});
// Same provider/video cannot duplicate in one matter; use a distinct official example ID.
videos.add({subjectId:fixture.a.id,title:'Vídeo sem texto',url:'https://www.youtube.com/watch?v=dQw4w9WgXcQ'});
seed.close();
const original=fs.readFileSync(path.join(fixture.root,fixture.noteA.ref.path));
fs.mkdirSync('.local/evidence',{recursive:true});
const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
async function launch(){return electron.launch({executablePath:path.resolve('release/win-unpacked/App Estudos.exe'),args:[`--user-data-dir=${data}`],env});}
let app=await launch(),page=await app.firstWindow();
const errors:string[]=[],network:string[]=[],checks:string[]=[],screenshots:string[]=[];let initialLedger=0;
function listen(){page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});}listen();
const work=()=>page.locator('.activities-workspace');
async function idle(){await page.locator('.area-stage[data-motion=idle]').waitFor();}
async function shot(name:string){if(name==='limit')await work().locator('.activity-prompt').scrollIntoViewIfNeeded();await page.waitForFunction(()=>Array.from(document.querySelectorAll('dialog[open]')).every(d=>(d as HTMLElement).style.opacity===''));const file=`.local/evidence/external-activities-${name}.png`;await page.screenshot({path:file});screenshots.push(file);console.log('CAPTURE '+name);}
async function close(){const closed=new Promise<void>(resolve=>app.once('close',()=>resolve()));await page.getByRole('button',{name:'Fechar janela',exact:true}).click();await closed;}
async function reopen(){await close();app=await launch();page=await app.firstWindow();listen();await page.getByRole('button',{name:'Abrir revisões',exact:true}).click();await idle();await page.getByRole('button',{name:'Atividades',exact:true}).click();await work().waitFor();}
async function currentRequest():Promise<ActivityRequest>{return page.evaluate(async subjectId=>{const list=await window.desktop.activityRequests({subjectId});if(!list.ok||!list.value[0])throw Error('Pedido não existe');const r=await window.desktop.activityRequest({subjectId,requestId:list.value[0].id});if(!r.ok)throw Error(r.message);return r.value;},fixture.a.id);}
function payload(r:ActivityRequest):ActivityPayload{const p=JSON.parse(fs.readFileSync(`tests/fixtures/activities/${r.type==='quiz'?'quiz':'flashcards'}-v1.json`,'utf8'));p.requestId=r.id;p.materialSnapshotId=r.snapshotId;p.difficulty=r.difficulty;for(const item of p.items)for(const ref of item.provenance.references){ref.sourceId=r.packet.sources[0].sourceId;ref.chunkId=r.packet.sources[0].chunks[0].id;}return p;}
async function validate(p:unknown){await work().getByRole('textbox',{name:'JSON da resposta',exact:true}).fill(typeof p==='string'?p:JSON.stringify(p));await work().getByRole('button',{name:'Validar resposta',exact:true}).click();}
async function noReward(){const db=new Store(data);try{assert.equal(db.db.prepare('SELECT count(*) n FROM economic_receipts').get()!.n,0);assert.equal(db.db.prepare('SELECT count(*) n FROM card_reviews').get()!.n,0);assert.equal(db.db.prepare('SELECT count(*) n FROM game_ledger').get()!.n,initialLedger);}finally{db.close();}}
try{
  await page.waitForFunction(() => document.querySelector<HTMLInputElement>('#note-title-input')?.value === 'HTTP e JavaScript');await idle();await page.setViewportSize({width:1440,height:940});
  const baseline=new Store(data);initialLedger=Number(baseline.db.prepare('SELECT count(*) n FROM game_ledger').get()!.n);baseline.close();
  await page.locator('.study-practice-actions summary').click();await page.getByRole('button',{name:'Criar questionário',exact:true}).click();await work().waitFor();
  assert.equal(await work().getByRole('checkbox',{name:'Selecionar Nota B',exact:true}).count(),0);
  assert.equal(await work().getByRole('checkbox',{name:'Selecionar Vídeo sem texto',exact:true}).isDisabled(),true);
  for(const title of ['HTTP e JavaScript','HTTP · complemento local','fixture-A.pdf','HTTP · aula anotada'])await work().getByRole('checkbox',{name:`Selecionar ${title}`,exact:true}).check();
  await work().getByRole('button',{name:'Preparar prompt',exact:true}).click();await work().getByRole('button',{name:'Copiar prompt',exact:true}).waitFor({timeout:70000});
  const r=await currentRequest();assert.equal(r.packet.sources.length,4);assert.ok(r.packet.sources[0].chunks.map(c=>c.text).join('').includes(source));assert.ok(!r.prompt.includes('MARCADOR_PRIVADO_OUTRA_MATERIA'));
  const pdf=r.packet.sources.find(s=>s.kind==='pdf')!;assert.equal(pdf.chunks.length,3);assert.ok(pdf.chunks[1].text.includes('Test fixture A - page 2'));assert.deepEqual(pdf.chunks[1].location,{kind:'page',page:2});assert.ok(r.prompt.includes('Anotação local: HTTP 404'));
  await work().getByRole('button',{name:'Copiar prompt',exact:true}).click();await work().getByRole('button',{name:'Copiado',exact:true}).waitFor();assert.equal(await app.evaluate(async({clipboard})=>await clipboard.readText()),r.prompt);
  await shot('prompt');checks.push('Quatro fontes reais da mesma matéria, Markdown integral/código, três páginas extraídas por PDF.js e anotação local42s; clipboard Windows confirmado.');
  await app.evaluate(({clipboard})=>{(globalThis as any).__activityClipboard=clipboard.writeText;clipboard.writeText=async()=>{throw Error('Falha injetada de clipboard');};});
  await work().getByRole('button',{name:'Copiado',exact:true}).click();await work().locator('.settings-error').waitFor();assert.equal(await work().getByRole('button',{name:'Copiado',exact:true}).count(),0);assert.equal(await work().getByRole('textbox',{name:'Prompt completo',exact:true}).inputValue(),r.prompt);
  await app.evaluate(({clipboard})=>{clipboard.writeText=(globalThis as any).__activityClipboard;delete (globalThis as any).__activityClipboard;});
  checks.push('Falha de clipboard injetada: nenhuma confirmação falsa e texto integral disponível para cópia manual.');
  const quiz=payload(r);assert.equal(quiz.type,'quiz');if(quiz.type!=='quiz')throw Error('Quiz fixture');quiz.items[1].provenance={basis:'material',references:[{sourceId:pdf.sourceId,chunkId:pdf.chunks[1].id}],supplement:null};
  const bad=JSON.stringify(quiz).replace('"schemaVersion":"1.0"','"schemaVersion":"1.0","schemaVersion":"1.0"');
  await validate(bad);await work().getByRole('heading',{name:'Não foi possível importar',exact:true}).waitFor();assert.ok((await work().locator('.activity-errors').innerText()).includes('$.schemaVersion'));assert.equal(await work().getByRole('textbox',{name:'JSON da resposta',exact:true}).inputValue(),bad);
  await work().getByRole('button',{name:'Copiar pedido de correção',exact:true}).click();await work().getByRole('button',{name:'Copiado',exact:true}).waitFor();const repair=await app.evaluate(async({clipboard})=>await clipboard.readText());assert.ok(repair.includes(JSON.stringify(bad)));assert.ok(repair.includes('DUPLICATE_PROPERTY'));assert.ok(repair.includes(r.id));await shot('correction');
  await reopen();await work().getByRole('button',{name:`Continuar pedido ${r.id.slice(0,8)}`,exact:true}).click();assert.equal(await work().getByRole('textbox',{name:'JSON da resposta',exact:true}).inputValue(),bad);assert.equal((await currentRequest()).prompt,r.prompt);
  await validate(quiz);await work().getByRole('heading',{name:'Prévia da atividade',exact:true}).waitFor();await shot('preview');await work().getByRole('button',{name:'Importar e começar',exact:true}).click();await work().getByRole('button',{name:'Alternativa A',exact:true}).waitFor();await noReward();
  for(let i=0;i<2;i++){await work().getByRole('button',{name:`Ir para questão ${i+1}`,exact:true}).click();await work().getByRole('button',{name:`Alternativa ${quiz.items[i].correctOptionId}`,exact:true}).click();await work().getByRole('button',{name:`Alternativa ${quiz.items[i].correctOptionId}`,exact:true}).waitFor({state:'visible'});await page.waitForFunction(n=>document.querySelector('.activity-practice')?.textContent?.includes(`${n} respondidas`),i+1);}
  assert.equal(await work().getByText(quiz.items[0].explanation,{exact:true}).count(),0);await shot('quiz');
  const imported=await page.evaluate(async subjectId=>{const r=await window.desktop.listActivities({subjectId});if(!r.ok)throw Error(r.message);return r.value[0];},fixture.a.id);
  await reopen();await work().getByRole('button',{name:`Estudar ${quiz.title}`,exact:true}).click();await work().getByRole('button',{name:'Alternativa A',exact:true}).waitFor();assert.ok((await work().locator('.activity-practice').innerText()).includes('2 respondidas'));
  for(let i=2;i<10;i++){await work().getByRole('button',{name:`Ir para questão ${i+1}`,exact:true}).click();await work().getByRole('button',{name:`Alternativa ${quiz.items[i].correctOptionId}`,exact:true}).click();await page.waitForFunction(n=>document.querySelector('.activity-practice')?.textContent?.includes(`${n} respondidas`),i+1);}
  await work().getByRole('button',{name:'Finalizar questionário',exact:true}).click();await work().getByRole('heading',{name:'Resultado do questionário',exact:true}).waitFor();assert.ok((await work().locator('.quiz-kpis').innerText()).includes('100%'));assert.equal(await work().locator('.quiz-result').count(),10);await shot('results');await noReward();
  await work().locator('.quiz-result').nth(1).getByRole('button',{name:'Conferir trecho 1',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Fonte: fixture-A.pdf',exact:true});await dialog.waitFor();assert.ok((await dialog.innerText()).includes('Página 2'));assert.ok((await dialog.innerText()).includes('Test fixture A - page 2'));await shot('reference');await dialog.getByRole('button',{name:'Abrir fonte local',exact:true}).click();await idle();await page.locator('canvas[data-rendered-page="2"]').waitFor();
  await page.getByRole('button',{name:'Abrir revisões',exact:true}).click();await idle();if(await page.getByRole('button',{name:'Atividades',exact:true}).getAttribute('aria-pressed')!=='true')await page.getByRole('button',{name:'Atividades',exact:true}).click();
  await work().getByRole('button',{name:'Minhas atividades',exact:true}).click();await work().getByRole('button',{name:`Continuar pedido ${r.id.slice(0,8)}`,exact:true}).click();await work().getByRole('textbox',{name:'Arquivo JSON da atividade',exact:true}).count();
  await work().locator('input[type=file]').setInputFiles({name:'quiz-v1.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(quiz,null,2))});await work().getByRole('heading',{name:'Prévia da atividade',exact:true}).waitFor();await work().getByRole('button',{name:'Importar e começar',exact:true}).click();await work().getByRole('heading',{name:'Resultado do questionário',exact:true}).waitFor();
  let db=new Store(data);assert.equal(db.db.prepare('SELECT count(*) n FROM study_activities').get()!.n,1);assert.equal(db.db.prepare('SELECT count(*) n FROM quiz_sessions').get()!.n,1);db.close();
  await work().getByRole('button',{name:'Minhas atividades',exact:true}).click();await work().getByRole('button',{name:`Continuar pedido ${r.id.slice(0,8)}`,exact:true}).click();await validate({...quiz,title:'HTTP e JavaScript · revisão 2'});await work().getByRole('button',{name:'Importar e começar',exact:true}).click();await work().getByRole('button',{name:'Alternativa A',exact:true}).waitFor();
  db=new Store(data);assert.equal(db.db.prepare('SELECT count(*) n FROM study_activities').get()!.n,2);assert.equal(db.db.prepare('SELECT count(*) n FROM quiz_sessions WHERE activity_id=? AND finished_at IS NOT NULL').get(imported.id)!.n,1);db.close();checks.push('Duplicatas JSON recusadas, pedido/correção/original sobrevivem reabertura; quiz real retomado2/10, final100%/10explicações, referência PDF2 abre leitor; arquivo usa mesmo pipeline, replay não duplica, revisão preserva tentativa.');
  await work().getByRole('button',{name:'Criar flashcards',exact:true}).click();for(const title of ['HTTP e JavaScript','HTTP · complemento local'])if(!(await work().getByRole('checkbox',{name:`Selecionar ${title}`,exact:true}).isChecked()))await work().getByRole('checkbox',{name:`Selecionar ${title}`,exact:true}).check();
  await work().getByRole('button',{name:'Preparar prompt',exact:true}).click();await work().getByRole('button',{name:'Copiar prompt',exact:true}).waitFor();const flashRequest=await currentRequest(),flash=payload(flashRequest);assert.equal(flash.type,'flashcards');if(flash.type!=='flashcards')throw Error('Flash fixture');flash.items[0].explanation='Explicação: '+'x'.repeat(3988);flash.items[0].back+='<img src=x onerror="window.activityExecuted=true">';
  await work().locator('input[type=file]').setInputFiles({name:'flashcards-v1.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(flash))});await work().getByRole('heading',{name:'Prévia da atividade',exact:true}).waitFor();
  db=new Store(data);db.db.exec("CREATE TRIGGER ui_activity_fail BEFORE INSERT ON audit_events WHEN NEW.action='activity.import' BEGIN SELECT RAISE(FAIL,'fixture rollback'); END;");db.close();await work().getByRole('button',{name:'Importar e começar',exact:true}).click();await work().locator('.settings-error').waitFor();
  db=new Store(data);assert.equal(db.db.prepare('SELECT count(*) n FROM flashcards').get()!.n,0);assert.equal(db.db.prepare('SELECT count(*) n FROM study_activities').get()!.n,2);db.db.exec('DROP TRIGGER ui_activity_fail');db.close();
  await work().getByRole('button',{name:'Importar e começar',exact:true}).click();await work().getByRole('button',{name:'Revelar resposta',exact:true}).waitFor();await noReward();assert.equal(await work().getByText(flash.items[0].back,{exact:true}).count(),0);await work().getByRole('button',{name:'Revelar resposta',exact:true}).click();assert.equal(await work().locator('.activity-card-back img').count(),0);const longText=await work().evaluate(e=>({width:e.clientWidth,scroll:e.scrollWidth}));assert.ok(longText.scroll<=longText.width+1,'Explicação integral de4000caracteres sem overflow horizontal');assert.equal(await page.evaluate(()=>(window as any).activityExecuted),undefined);
  await work().getByRole('button',{name:'Lembrei',exact:true}).click();await work().getByRole('button',{name:'Ir para cartão 1',exact:true}).click();assert.ok((await work().locator('.activity-practice').innerText()).includes('1 revisões'));await work().getByRole('button',{name:'Ir para cartão 10',exact:true}).click();await work().getByRole('button',{name:'Revelar resposta',exact:true}).click();await work().getByText('Complemento de conhecimento geral',{exact:true}).waitFor();await shot('flashcards');
  await page.getByRole('button',{name:'Cartões',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.review-library>button').length===9);await page.getByRole('button',{name:'Mostrar biblioteca inteira',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.review-library>button').length===10);assert.equal(await page.locator('.review-library>button').count(),10);await page.getByRole('button',{name:'Atividades',exact:true}).click();
  await work().getByRole('button',{name:'Minhas atividades',exact:true}).click();await work().getByRole('button',{name:`Continuar pedido ${flashRequest.id.slice(0,8)}`,exact:true}).click();await validate(flash);await work().getByRole('button',{name:'Importar e começar',exact:true}).click();await work().getByRole('button',{name:'Revelar resposta',exact:true}).waitFor();assert.ok((await work().locator('.activity-practice').innerText()).includes('1 revisões'));const replay=new Store(data);assert.equal(replay.db.prepare('SELECT count(*) n FROM flashcards').get()!.n,10);assert.equal(replay.db.prepare('SELECT count(*) n FROM card_reviews').get()!.n,1);replay.close();
  await reopen();await work().locator('.activity-library article').filter({hasText:'Flashcards ·'}).getByRole('button',{name:`Estudar ${flash.title}`,exact:true}).click();await work().getByRole('button',{name:'Revelar resposta',exact:true}).waitFor();assert.ok((await work().locator('.activity-practice').innerText()).includes('1 revisões'));
  const notePath=path.join(fixture.root,fixture.noteA.ref.path);fs.appendFileSync(notePath,'\nFonte mudou após o snapshot.');await work().getByRole('button',{name:'Revelar resposta',exact:true}).click();await work().getByRole('button',{name:'Conferir trecho 1',exact:true}).click();await page.getByText('A fonte mudou. Este trecho preserva o snapshot exportado.',{exact:true}).waitFor();await page.getByRole('dialog').getByRole('button',{name:'Fechar diálogo',exact:true}).click();
  fs.renameSync(notePath,notePath+'.moved');await work().getByRole('button',{name:'Conferir trecho 1',exact:true}).click();await page.getByText('Fonte atual ausente. O snapshot conserva o contexto exportado.',{exact:true}).waitFor();assert.equal(await page.getByRole('dialog').getByRole('button',{name:'Abrir fonte local',exact:true}).count(),0);await shot('missing-source');await page.getByRole('dialog').getByRole('button',{name:'Fechar diálogo',exact:true}).click();fs.renameSync(notePath+'.moved',notePath);fs.writeFileSync(notePath,original);const notice=page.getByRole('button',{name:'Fechar aviso da navegação',exact:true});if(await notice.count())await notice.click();
  checks.push('Flashcards por arquivo criam10cartões reais e replay por colagem conserva revisões; rollback injetado não deixa atividade/cartões parciais; verso por ação, autoavaliação Study.review persiste e biblioteca existente atualiza10cartões ao voltar, HTML inerte, complemento e snapshot alterado/ausente identificados.');
  await work().getByRole('button',{name:'Criar questionário',exact:true}).click();await work().getByRole('checkbox',{name:'Selecionar HTTP e JavaScript',exact:true}).check();await work().getByRole('spinbutton',{name:'Limite do prompt',exact:true}).fill('2000');await work().getByRole('button',{name:'Preparar prompt',exact:true}).click();await work().getByText(/O prompt excede o limite/).waitFor();assert.equal(await work().getByRole('button',{name:'Copiar prompt',exact:true}).count(),0);await shot('limit');
  await page.getByRole('button',{name:'Dividir com PDFs',exact:true}).focus();await page.keyboard.press('Enter');await idle();await page.setViewportSize({width:1040,height:760});await idle();await work().getByRole('button',{name:'Preparar prompt',exact:true}).waitFor({state:'visible'});await work().evaluate(e=>e.scrollTop=0);await shot('compact');const rect=await work().boundingBox();assert.ok(rect&&rect.width<550);const horizontal=await work().evaluate(e=>({width:e.clientWidth,scroll:e.scrollWidth}));assert.ok(horizontal.scroll<=horizontal.width+1);
  db=new Store(data);const counts={activities:db.db.prepare('SELECT count(*) n FROM study_activities').get()!.n,cards:db.db.prepare('SELECT count(*) n FROM flashcards').get()!.n,reviews:db.db.prepare('SELECT count(*) n FROM card_reviews').get()!.n,sessions:db.db.prepare('SELECT count(*) n FROM quiz_sessions').get()!.n};db.close();assert.deepEqual(counts,{activities:3,cards:10,reviews:1,sessions:2});assert.ok(fs.readFileSync(notePath).equals(original));assert.deepEqual(errors,[]);assert.deepEqual(network,[]);
  // Explicitly selecting a different local request, without remapping its response.
  await page.getByRole('button',{name:'Abrir revisões',exact:true}).click();await idle();await page.setViewportSize({width:1440,height:940});
  await work().getByRole('combobox',{name:'Matéria das atividades',exact:true}).selectOption(fixture.b.id);await work().getByRole('button',{name:'Criar questionário',exact:true}).click();await work().getByRole('spinbutton',{name:'Limite do prompt',exact:true}).fill('100000');await work().getByRole('checkbox',{name:'Selecionar Outra matéria',exact:true}).check();await work().getByRole('button',{name:'Preparar prompt',exact:true}).click();await work().getByRole('button',{name:'Copiar prompt',exact:true}).waitFor();
  const corresponding=await page.evaluate(async subjectId=>{const list=await window.desktop.activityRequests({subjectId});if(!list.ok)throw Error(list.message);const r=await window.desktop.activityRequest({subjectId,requestId:list.value[0].id});if(!r.ok)throw Error(r.message);return r.value;},fixture.b.id);
  const otherResponse=JSON.stringify(payload(corresponding));
  await work().getByRole('combobox',{name:'Matéria das atividades',exact:true}).selectOption(fixture.a.id);await work().getByRole('button',{name:`Continuar pedido ${r.id.slice(0,8)}`,exact:true}).click();await validate(otherResponse);await work().getByRole('button',{name:`Escolher pedido correspondente ${corresponding.id.slice(0,8)} · Matéria B`,exact:true}).click();
  await page.waitForFunction(subjectId=>document.querySelector<HTMLSelectElement>('[aria-label="Matéria das atividades"]')?.value===subjectId,fixture.b.id);assert.equal(await work().getByRole('textbox',{name:'JSON da resposta',exact:true}).inputValue(),otherResponse);await work().getByRole('button',{name:'Validar resposta',exact:true}).click();await work().getByRole('heading',{name:'Prévia da atividade',exact:true}).waitFor();assert.ok((await work().locator('.activity-preview').innerText()).includes('Matéria B'));await shot('corresponding-request');
  const denied=await app.evaluate(async({BrowserWindow},subjectId)=>{const win=new BrowserWindow({show:false,webPreferences:{nodeIntegration:true,contextIsolation:false,sandbox:false}});try{await win.loadURL('data:text/html,<title>Controlled IPC probe only</title>');return await win.webContents.executeJavaScript(`Promise.all(['activity:sources','activity:prepare','activity:request','activity:copy','activity:validate','activity:import','quiz:start','quiz:answer','quiz:finish'].map(channel=>require('electron').ipcRenderer.invoke(channel,{subjectId:${JSON.stringify(subjectId)}})))`);}finally{win.destroy();}},fixture.a.id);assert.ok(denied.every((r:any)=>!r.ok&&r.code==='FORBIDDEN'));
  checks.push('Pedido de outra matéria requer escolha explícita; JSON original preservado, fontes/pedido corretos após mudança, nenhuma importação automática. Nove canais novos recusam sender externo real.');
  checks.push('Limite2000 bloqueia cópia sem corte; viewport1040×760 dividido com PDF, fontes preservadas, três atividades/10cartões/uma revisão/duas tentativas; zero pageerror ou rede HTTP(S) no renderer.');
  fs.writeFileSync('.local/evidence/external-activities-smoke.json',JSON.stringify({platform:process.platform,fixture:'Declarada, não é resposta de provedor.',checks,counts,errors,network,screenshots},null,2));console.log(JSON.stringify({checks,counts,errors,network},null,2));
}catch(error){await shot('failure').catch(()=>{});console.error((await page.locator('body').innerText()).slice(-7000));throw error;}
finally{await close().catch(()=>app.close());}
