import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { _electron as electron } from 'playwright';
import electronPath from 'electron';
import { Store } from '../src/main/store';
import { Game } from '../src/main/game';
import { Projects } from '../src/main/projects';
import { UserPreferences } from '../src/main/preferences';
import type { GameAction, GameState } from '../src/shared/game';

// Uses real services and a dedicated preview fixture. Accelerated clock is only for
// preparing an earned economy before launch; both workshop games run in real time.
const fixture=process.argv.find(a=>a.startsWith('--fixture='))?.slice(10);assert.ok(fixture);
const directory=path.resolve(fixture),data=path.join(directory,'data');assert.equal(path.dirname(directory),path.resolve('.local'));assert.ok(path.basename(directory).startsWith('frontend-preview-'));
const db=new Store(data),prefs=new UserPreferences(db),projects=new Projects(db);let now=Date.now()-7*24*3600000;const game=new Game(db,()=>now);
const act=(action:GameAction)=>game.act({operationId:crypto.randomUUID(),action});
act({kind:'producer-buy',producer:'collectors',quantity:1});now+=7*24*3600000;game.get();
act({kind:'producer-buy',producer:'collectors',quantity:10});act({kind:'producer-buy',producer:'workshops',quantity:10});act({kind:'producer-buy',producer:'warehouses',quantity:1});act({kind:'economy-upgrade',id:'collectors-1'});
for(const item of ['windmill','cottage','lanterns','benches','greenhouse','fountain'] as const)act({kind:'buy',item});
prefs.update({theme:'editorial',animations:true,editorialBackground:true});
const projectRoot=path.join(directory,'Projeto de janela');fs.mkdirSync(projectRoot,{recursive:true});const file=path.join(projectRoot,'README.md');const source=Buffer.from('\ufeff# Projeto demonstrativo\r\n\r\nFonte preservada.\r\n');fs.writeFileSync(file,source);
projects.chooseRoot(projectRoot);const project=projects.catalog().projects.find(p=>p.name==='Projeto de janela')!;
const notes=db.db.prepare('SELECT path FROM notes').all();const originals=notes.map(n=>({file:path.join(directory,'vault',String(n.path)),bytes:fs.readFileSync(path.join(directory,'vault',String(n.path)))}));
db.close();fs.mkdirSync('.local/evidence',{recursive:true});
const packaged=process.argv.includes('--packaged'),env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
async function launch(){return electron.launch({executablePath:packaged?path.resolve('release/win-unpacked/App Estudos.exe'):electronPath,args:[...(packaged?[]:['.']),`--user-data-dir=${data}`],env});}
let app=await launch(),page=await app.firstWindow();const errors:string[]=[],checks:string[]=[];
page.on('pageerror',e=>errors.push(e.message));
async function state(){const r=await page.evaluate(()=>window.desktop.getGame());assert.ok(r.ok);return r.value;}
async function ready(){await page.locator('.game-shell[aria-busy=false]').waitFor();}
async function area(target:string){await page.waitForFunction(a=>document.querySelector(`[data-area="${a}"]`)?.getAttribute('aria-hidden')==='false'&&document.querySelector('[data-testid=area-stage]')?.getAttribute('data-motion')==='idle',target);}
async function shot(name:string){await page.waitForTimeout(120);await page.screenshot({path:`.local/evidence/progression-${name}.png`});}
async function dimensions(width:number,height:number){await app.evaluate(({BrowserWindow},size)=>BrowserWindow.getAllWindows()[0].setContentSize(size.width,size.height),{width,height});await page.waitForFunction(size=>innerWidth===size.width&&innerHeight===size.height,{width,height});}
try{
 await page.getByTestId('version').waitFor();await page.locator('canvas[data-rendered-page="2"]').waitFor();await page.emulateMedia({reducedMotion:'no-preference'});await shot('desk');
 assert.equal(await page.locator('.desktop-drag').evaluate(e=>getComputedStyle(e).getPropertyValue('-webkit-app-region')),'drag');
 await page.getByRole('button',{name:'Maximizar janela',exact:true}).click();await page.getByRole('button',{name:'Restaurar janela',exact:true}).waitFor();assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isMaximized()),true);
 await page.getByRole('button',{name:'Restaurar janela',exact:true}).click();await page.getByRole('button',{name:'Maximizar janela',exact:true}).waitFor();
 await page.getByRole('button',{name:'Minimizar janela',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-testid=editorial-background]')?.getAttribute('data-running')==='false');assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isMinimized()),true);
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].restore());await page.waitForFunction(()=>!document.hidden);
 const invalid=await page.evaluate(()=>window.desktop.controlWindow({action:'arbitrary'} as never));assert.ok(!invalid.ok&&invalid.code==='INVALID_ARGUMENT');checks.push('Janela: maximizar/restaurar/minimizar, região de arraste e argumento inválido aprovados');
 const foreign=await app.evaluate(async({BrowserWindow})=>{const w=new BrowserWindow({show:false,webPreferences:{nodeIntegration:true,contextIsolation:false,sandbox:false}});try{await w.loadURL('data:text/html,fixture');return await w.webContents.executeJavaScript("Promise.all([['window:get'],['window:command',{action:'minimize'}],['game:action',{operationId:'00000000-0000-4000-8000-000000000001',action:{kind:'prestige',expectedCycles:0,expectedGain:1}}]].map(([channel,input])=>require('electron').ipcRenderer.invoke(channel,input)))");}finally{w.destroy();}});
 for(const r of foreign as {ok:boolean;code:string}[])assert.deepEqual({ok:r.ok,code:r.code},{ok:false,code:'FORBIDDEN'});checks.push('IPC: controles de janela e prestígio de outro remetente negados');
 await page.getByRole('button',{name:'Abrir configurações',exact:true}).click();await area('settings');await page.getByRole('button',{name:'Aparência',exact:true}).click();
 const backdrop=page.getByTestId('editorial-background');assert.equal(await backdrop.evaluate(e=>getComputedStyle(e,'::before').animationName),'editorial-drift');
 const transform=await backdrop.evaluate(e=>getComputedStyle(e,'::before').transform);await page.waitForTimeout(400);assert.notEqual(await backdrop.evaluate(e=>getComputedStyle(e,'::before').transform),transform);
 await page.getByRole('switch',{name:'Fundo animado do Editorial',exact:true}).uncheck();await page.waitForFunction(()=>document.querySelector('[data-testid=editorial-background]')?.getAttribute('data-running')==='false');assert.equal(await backdrop.evaluate(e=>getComputedStyle(e,'::before').animationName),'none');
 await page.getByRole('switch',{name:'Fundo animado do Editorial',exact:true}).check();await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await backdrop.evaluate(e=>getComputedStyle(e,'::before').animationName),'none');assert.equal(await backdrop.evaluate(e=>getComputedStyle(e,'::before').opacity),'0');await page.emulateMedia({reducedMotion:'no-preference'});await shot('settings');checks.push('Fundo: animação efetiva, controle independente, minimização e movimento reduzido aprovados');
 await page.getByRole('button',{name:'Entrar na cidade',exact:true}).click();await area('city');await page.locator('canvas[data-testid=city-canvas][data-ready=true]').waitFor();
 const canvas=await page.locator('canvas[data-testid=city-canvas]').elementHandle();
 for(const skin of ['original','cyberpunk','newyork'] as const){await page.getByRole('combobox',{name:'Skin da cidade'}).selectOption(skin);await ready();await page.waitForFunction(s=>document.querySelector('[data-testid=city-canvas]')?.getAttribute('data-skin')===s,skin);await page.getByRole('button',{name:'Centralizar cidade',exact:true}).click();await page.locator('canvas[data-camera=idle]').waitFor();assert.equal(await canvas!.evaluate(e=>e===document.querySelector('[data-testid=city-canvas]')),true);await shot(skin);}
 await page.getByRole('button',{name:'Visitar fazenda',exact:true}).click();await page.getByRole('heading',{name:'Sua fazenda',exact:true}).waitFor();await page.getByRole('button',{name:'Plantar canteiro 1',exact:true}).click();await ready();const planting=(await state()).plots[0];await page.getByRole('combobox',{name:'Skin da cidade'}).selectOption('cyberpunk');await ready();assert.deepEqual((await state()).plots[0],planting);await page.getByRole('combobox',{name:'Skin da cidade'}).selectOption('newyork');await ready();checks.push('Três skins completas, canvas/câmera reutilizados e cultivo intacto aprovados');
 await page.getByRole('button',{name:'Produção',exact:true}).click();await page.getByRole('heading',{name:'Uma cidade que produz.',exact:true}).waitFor();await shot('production');const count=(await state()).economy.producers.collectors;await page.getByRole('button',{name:'Comprar 1 Coletores',exact:true}).click();await ready();assert.equal((await state()).economy.producers.collectors,count+1);
 await page.getByRole('button',{name:'Tecnologias',exact:true}).click();await shot('technologies');assert.equal(await page.getByRole('button',{name:'Adquirir Coletores · Automação',exact:true}).isDisabled(),true);
 await page.getByRole('button',{name:'Conquistas',exact:true}).click();await shot('achievements');await page.getByRole('button',{name:'Prestígio',exact:true}).click();await shot('prestige');await page.getByRole('button',{name:'Revisar novo ciclo',exact:true}).click();await page.getByRole('button',{name:'Continuar neste ciclo',exact:true}).click();assert.equal((await state()).economy.cycles,0);checks.push('Compra UI, tecnologias bloqueadas, conquistas e cancelamento de prestígio aprovados');
 if(!process.argv.includes('--skip-workshops')){
  await page.getByRole('button',{name:'Oficina',exact:true}).click();await page.getByRole('combobox',{name:'Ritmo dos desafios'}).selectOption('normal');
  let qte:GameState;await page.getByRole('button',{name:/Sincronizar o motor/}).click();await ready();const qteStart=Date.now();
  for(let i=0;i<36;i++){await page.getByTestId('qte-key').waitFor();const key=await page.getByTestId('qte-key').textContent();await page.keyboard.press(key!);await ready();await page.waitForFunction(stage=>document.querySelector('[data-testid=challenge-panel]')?.textContent?.includes(`${Math.min(36,stage+1)} / 36`),i+1);if(i===12||i===24)await shot(`qte-phase-${i===12?2:3}`);if(i%12===11)console.log(`QTE: ${i+1}/36 etapas reais`);}
  qte=await state();assert.equal(qte.challenge!.status,'completed');assert.equal(qte.challenge!.hits,36);assert.equal(qte.challenge!.coins,300);const qteMs=Date.now()-qteStart;assert.ok(qteMs>=120000&&qteMs<=240000);await shot('qte-completed');
  await page.getByRole('button',{name:/Calibrar a válvula/}).click();await ready();const skillStart=Date.now();
  for(let i=0;i<36;i++){await page.getByTestId('skill-track').waitFor();await page.waitForFunction(()=>{const track=document.querySelector('[data-testid=skill-track]') as HTMLElement|null;if(!track)return false;const position=Number(track.dataset.position),target=Number(track.dataset.target);return Math.abs(position-target)<3;},{},{polling:'raf'});await page.getByRole('button',{name:'Calibrar válvula',exact:true}).click();await ready();await page.waitForFunction(stage=>document.querySelector('[data-testid=challenge-panel]')?.textContent?.includes(`${Math.min(36,stage+1)} / 36`),i+1);if(i%12===11)console.log(`Calibração: ${i+1}/36 etapas reais`);}
  const skill=await state();assert.equal(skill.challenge!.status,'completed');assert.equal(skill.challenge!.hits,36);assert.equal(skill.challenge!.coins,375);const skillMs=Date.now()-skillStart;assert.ok(skillMs>=120000&&skillMs<=240000);await shot('skill-completed');checks.push(`Oficina real: QTE ${Math.round(qteMs/1000)}s e calibração ${Math.round(skillMs/1000)}s, 36 acertos/fases/recompensa em ambos`);
 }
 await page.getByRole('button',{name:'Oficina',exact:true}).click();await page.getByRole('button',{name:/Sincronizar o motor/}).click();await ready();await page.getByRole('button',{name:'Pausar partida',exact:true}).click();await ready();const paused=(await state()).challenge!;await shot('office');await page.getByRole('button',{name:'Abrir Hoje',exact:true}).click();await area('home');await page.keyboard.press(paused.sequence[0]);const hidden=(await state()).challenge!;assert.equal(hidden.stage,paused.stage);assert.equal(hidden.status,'paused');await page.getByRole('button',{name:'Entrar na cidade',exact:true}).click();await area('city');await page.getByRole('button',{name:'Oficina',exact:true}).click();await page.getByRole('button',{name:'Retomar partida',exact:true}).click();await ready();await page.getByRole('button',{name:'Encerrar tentativa · sem custo',exact:true}).click();await ready();checks.push('Pausa, navegação sem entrada oculta, retomada e cancelamento aprovados');
 await page.getByRole('button',{name:'Produção',exact:true}).click();await page.getByRole('button',{name:'Prestígio',exact:true}).click();await page.getByRole('button',{name:'Revisar novo ciclo',exact:true}).click();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Confirmar novo ciclo',exact:true}).click();await ready();assert.equal((await state()).economy.cycles,1);assert.equal((await state()).economy.producers.collectors,0);assert.equal((await state()).skin,'newyork');await page.getByRole('button',{name:'Adquirir Ferramentas herdadas',exact:true}).click();await ready();assert.equal((await state()).engine.power,2);checks.push('Prestígio confirmado pela UI e melhoria permanente aprovados');
 await dimensions(1040,760);await page.getByRole('button',{name:'Vila',exact:true}).click();await shot('compact-city');assert.ok(await page.locator('.game-footer').isVisible());const bounds=await page.locator('.game-footer').boundingBox();assert.ok(bounds&&bounds.y+bounds.height<=760);
 await page.getByRole('button',{name:'Abrir configurações',exact:true}).click();await area('settings');await page.getByRole('button',{name:'Aparência',exact:true}).click();await page.getByRole('switch',{name:'Fundo animado do Editorial',exact:true}).uncheck();const boot=await page.evaluate(()=>window.desktop.bootstrap());assert.ok(boot.ok);const subjectId=boot.value.subjects[0].id;const focus=await page.evaluate(async subjectId=>{const prior=await window.desktop.getFocus({subjectId});if(prior.ok&&prior.value.session?.state==='paused')return window.desktop.actFocus({subjectId,id:prior.value.session.id,action:'resume'});return window.desktop.startFocus({subjectId,minutes:25});},subjectId);assert.ok(focus.ok&&focus.value.session?.state==='running');const focusId=focus.value.session.id;
 await page.getByRole('button',{name:'Abrir Explorer',exact:true}).click();await area('explorer');await page.getByRole('button',{name:'Explorar Projeto de janela',exact:true}).click();await page.getByRole('button',{name:'Arquivo README.md',exact:true}).click();const editor=page.getByRole('textbox',{name:'Conteúdo do arquivo',exact:true});await editor.click();await page.keyboard.press('Control+End');await page.keyboard.insertText('\nRascunho salvo pelo botão Fechar.');
 const closed=new Promise<void>(resolve=>app.once('close',()=>resolve()));await page.getByRole('button',{name:'Fechar janela',exact:true}).click();await closed;
 app=await launch();page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.getByTestId('version').waitFor();
 await page.getByRole('button',{name:'Entrar na cidade',exact:true}).click();await area('city');assert.equal((await state()).skin,'newyork');assert.equal((await state()).economy.prestige,1);assert.equal((await state()).engine.power,2);
 const retained=await page.evaluate(async subjectId=>({focus:await window.desktop.getFocus({subjectId}),prefs:await window.desktop.getPreferences()}),subjectId);assert.ok(retained.focus.ok&&retained.prefs.ok);assert.equal(retained.focus.value.session?.id,focusId);assert.equal(retained.focus.value.session?.state,'paused');assert.equal(retained.focus.value.session?.recovered,false);assert.equal(retained.prefs.value.editorialBackground,false);assert.equal(retained.prefs.value.animations,true);checks.push('Foco ativo pausado ao fechar e fundo independente desligado conservados após reinício');
 await page.getByRole('button',{name:'Abrir Explorer',exact:true}).click();await area('explorer');const reopened=await page.evaluate(ref=>window.desktop.openProjectFile(ref),{projectId:project.id,path:'README.md'});assert.ok(reopened.ok&&reopened.value.draft?.text.includes('Rascunho salvo pelo botão Fechar.'));assert.deepEqual(fs.readFileSync(file),source);for(const original of originals)assert.deepEqual(fs.readFileSync(original.file),original.bytes);checks.push('Fechar/reabrir: draft/bytes originais, skin, prestígio e melhoria permanente conservados');
 assert.deepEqual(errors,[]);const resultName=process.argv.includes('--skip-workshops')?'progression-final-results':'progression-results';fs.writeFileSync(`.local/evidence/${resultName}.json`,JSON.stringify({platform:process.platform,packaged,fixture:directory,checks,errors},null,2));console.log(checks.join('\n'));
}catch(error){try{await shot('failure');}catch{}fs.writeFileSync('.local/evidence/progression-failure.json',JSON.stringify({checks,errors,error:String(error)},null,2));throw error;}finally{await app.close();}
