import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { _electron as electron } from 'playwright';
import { prepareFixture } from './test-fixture';
import { Store } from '../src/main/store';
import { Projects } from '../src/main/projects';
import { Vault } from '../src/main/vault';
import type { GameState } from '../src/shared/game';

// Isolated, named fixtures go through the real vault/SQLite services and IPC.
const fixture=prepareFixture('clean-workspace'),data=path.join(fixture.dir,'data');
const db=new Store(data),vault=new Vault(db),nodes=[fixture.noteA.ref];
for(const title of ['Vetores','Transformações','Matrizes','Geometria','Base e dimensão','Determinantes','Autovalores','Sistemas lineares','Aplicações'])nodes.push(vault.create({subjectId:fixture.a.id,title}).ref);
const edited=vault.save({id:fixture.noteA.ref.id,hash:fixture.noteA.hash,text:fixture.noteA.text.split('# Nota A')[0]+'# Nota A\n\n## Transformações lineares\n\nUma transformação preserva a soma de vetores e a multiplicação por um escalar. A matriz registra como cada vetor da base se transforma.\n\n### Observe antes de calcular\n\n- Identifique a base do espaço.\n- Aplique a transformação aos vetores da base.\n- Organize as imagens nas colunas da matriz.\n\n> A geometria dá sentido à conta.\n\n| Conceito | Leitura |\n| --- | --- |\n| Vetor | Direção e comprimento |\n| Matriz | Representação da transformação |\n| Determinante | Mudança de área |\n\n### Próxima investigação\n\nConecte esta nota a Matrizes e explore exemplos no PDF.\n'});assert.equal(edited.state,'saved');if(edited.state==='saved')fixture.noteA=edited.document;
const projectRoot=path.join(fixture.dir,'Projeto local');fs.mkdirSync(projectRoot);const projectFile=path.join(projectRoot,'README.md');fs.writeFileSync(projectFile,'# Projeto de prova\n\nFonte preservada.\n');const projects=new Projects(db),project=projects.chooseRoot(projectRoot);const projectId=projects.catalog().projects[0].id;const projectSource=fs.readFileSync(projectFile);
db.close();fs.mkdirSync('.local/evidence',{recursive:true});
const originals=[fixture.noteA,fixture.noteB].map(n=>({file:path.join(fixture.root,n.ref.path),bytes:fs.readFileSync(path.join(fixture.root,n.ref.path))}));
const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
async function launch(){return electron.launch({executablePath:path.resolve('release/win-unpacked/App Estudos.exe'),args:[`--user-data-dir=${data}`],env});}
let app=await launch(),page=await app.firstWindow();const errors:string[]=[],checks:string[]=[],durations:Record<string,number>={};page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(15000);
async function idle(){await page.locator('.area-stage[data-motion=idle]').waitFor();}
async function module(area:string,index=1){await page.getByRole('combobox',{name:`Módulo ${index}`,exact:true}).selectOption(area);await idle();}
async function add(name:string){await page.locator('.workspace-add summary').click();await page.getByRole('menuitem',{name,exact:true}).click();await idle();}
async function shot(name:string){await page.screenshot({path:`.local/evidence/clean-${name}.png`});}
async function state():Promise<GameState>{const r=await page.evaluate(()=>window.desktop.getGame());assert.ok(r.ok);return r.value;}
async function prefs(){const r=await page.evaluate(()=>window.desktop.getPreferences());assert.ok(r.ok);return r.value;}
async function busyDone(){await page.locator('.game-shell[aria-busy=false]').waitFor();}
async function closeWindow(){const closed=new Promise<void>(resolve=>app.once('close',()=>resolve()));await page.getByRole('button',{name:'Fechar janela',exact:true}).click();await closed;}
try{
 await page.getByRole('heading',{name:'Nota A',exact:true}).waitFor();await idle();await page.mouse.move(80,90);await page.waitForTimeout(220);
 assert.deepEqual((await prefs()).workspaceLayout,{panes:['study'],sizes:[100]});assert.equal(await page.locator('.sidebar').isVisible(),false);assert.equal(await page.locator('.pdf-reader').count(),0);assert.equal(await page.locator('.suspended-popover').count(),0);
 await page.getByRole('button',{name:'Leitura',exact:true}).click();await shot('single');await page.getByRole('button',{name:'Editar',exact:true}).click();
 const editor=page.getByRole('textbox',{name:'Conteúdo da nota',exact:true});await editor.click();await editor.press('Control+End');await page.keyboard.insertText('\nRascunho de divisão preservado.');
 await page.getByRole('button',{name:'Abrir acervo',exact:true}).click();await page.getByRole('button',{name:'Matéria B',exact:true}).click();await page.getByRole('heading',{name:'Nota B',exact:true}).waitFor();
 await page.getByRole('button',{name:'Abrir acervo',exact:true}).click();await page.getByRole('button',{name:'Matéria A',exact:true}).click();await page.getByRole('heading',{name:'Nota A',exact:true}).waitFor();await editor.press('Control+End');assert.ok((await editor.textContent())?.includes('Rascunho de divisão preservado.'));
 const focusButton=page.getByRole('button',{name:'Abrir foco',exact:true});await focusButton.hover();await page.getByRole('region',{name:'Painel de foco',exact:true}).waitFor();await page.mouse.move(80,90);await page.locator('.suspended-popover').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Abrir checklist',exact:true}).click();await page.getByRole('textbox',{name:'Nova tarefa',exact:true}).fill('Revisão suspensa');await page.getByRole('button',{name:'Criar tarefa',exact:true}).click();await page.getByRole('textbox',{name:'Nova etapa em Revisão suspensa',exact:true}).fill('Conectar ideias');await page.getByRole('button',{name:'Adicionar etapa em Revisão suspensa',exact:true}).click();await page.getByRole('button',{name:'Retomar Conectar ideias',exact:true}).click();await shot('tools');await page.getByRole('button',{name:'Fechar painel suspenso',exact:true}).click();await page.mouse.move(80,90);
 checks.push('Uma área inicial; acervo e ferramentas recolhidos; hover, checklist real e draft entre matérias conservados.');
 await add('PDF');await page.locator('canvas[data-rendered-page="2"]').waitFor();await add('Grafo');await page.getByTestId('graph-canvas').waitFor();assert.equal(await page.getByRole('combobox',{name:/^Módulo /}).count(),3);
 const divider=page.getByRole('separator',{name:'Largura do módulo 1',exact:true});await divider.focus();await divider.press('ArrowRight');await divider.press('ArrowRight');
 const d2=page.getByRole('separator',{name:'Largura do módulo 2',exact:true}),bounds=await d2.boundingBox();assert.ok(bounds);await page.mouse.move(bounds.x+4,bounds.y+180);await page.mouse.down();await page.mouse.move(bounds.x-30,bounds.y+180,{steps:8});await page.mouse.up();await page.waitForTimeout(250);
 const saved=(await prefs()).workspaceLayout;assert.equal(saved.panes.length,3);assert.ok(saved.sizes.every(n=>n>=20));assert.notDeepEqual(saved.sizes,[100/3,100/3,100/3]);
 await page.locator('.workspace-add summary').click();assert.equal(await page.getByRole('menuitem',{name:'Cidade',exact:true}).isDisabled(),true);await page.locator('.workspace-add summary').click();
 await page.getByRole('button',{name:'Leitura',exact:true}).click();await shot('split');await page.setViewportSize({width:1040,height:760});await idle();for(const area of saved.panes){const b=await page.locator(`[data-area=${area}]`).boundingBox();assert.ok(b&&b.width>=180&&b.height>500&&b.y+b.height<=760);}const gh=await page.getByRole('button',{name:'Mostrar notas e relações',exact:true}).boundingBox();assert.ok(gh&&gh.x+gh.width<=1040);await shot('compact');await page.setViewportSize({width:1440,height:940});
 await page.getByRole('combobox',{name:'Módulo 3',exact:true}).focus();await page.getByRole('button',{name:'Tela única',exact:true}).click();await idle();await page.getByTestId('graph-canvas').waitFor();assert.equal(await page.locator('.graph-details').isVisible(),false);
 await page.waitForTimeout(2600);const canvas=page.getByTestId('graph-canvas'),before=Number(await canvas.getAttribute('data-zoom'));await page.getByRole('button',{name:'Aproximar grafo',exact:true}).click();await page.waitForTimeout(45);const intermediate=Number(await canvas.getAttribute('data-zoom'));await page.waitForTimeout(600);const after=Number(await canvas.getAttribute('data-zoom'));assert.ok(before<intermediate&&intermediate<after);
 await page.getByRole('button',{name:'Selecionar nó Matrizes',exact:true}).click();await page.waitForTimeout(700);await page.getByRole('combobox',{name:'Nota de origem da relação',exact:true}).selectOption(nodes[0].id);await page.getByRole('combobox',{name:'Nota de destino da relação',exact:true}).selectOption(nodes[3].id);await page.getByRole('textbox',{name:'Nome da relação',exact:true}).fill('Fundamenta');const viewBefore={x:Number(await canvas.getAttribute('data-target-x')),y:Number(await canvas.getAttribute('data-target-y')),zoom:Number(await canvas.getAttribute('data-zoom'))};await page.getByRole('button',{name:'Conectar notas',exact:true}).click();await page.getByRole('button',{name:'Excluir relação Fundamenta',exact:true}).waitFor();const links=await page.evaluate(subjectId=>window.desktop.noteLinks({subjectId}),fixture.a.id);assert.ok(links.ok&&links.value.length===1);
 await page.getByRole('button',{name:'Fechar notas e relações',exact:true}).click();await page.waitForTimeout(500);assert.ok(Math.abs(Number(await canvas.getAttribute('data-zoom'))-viewBefore.zoom)<.01);
 const cb=await canvas.boundingBox();assert.ok(cb);const panBefore=Number(await canvas.getAttribute('data-target-x'));await page.mouse.move(cb.x+cb.width*.65,cb.y+cb.height*.75);await page.mouse.down();await page.mouse.move(cb.x+cb.width*.65+100,cb.y+cb.height*.75+20,{steps:10});await page.mouse.up();await page.waitForTimeout(800);assert.notEqual(Number(await canvas.getAttribute('data-target-x')),panBefore);await shot('graph');
 await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Aproximar grafo',exact:true}).click();await page.waitForTimeout(80);assert.equal(await canvas.getAttribute('data-camera'),'idle');await module('study');assert.equal(await canvas.getAttribute('data-camera'),'idle');const hiddenZoom=await canvas.getAttribute('data-zoom');await page.waitForTimeout(150);assert.equal(await canvas.getAttribute('data-zoom'),hiddenZoom);await page.emulateMedia({reducedMotion:'no-preference'});
 checks.push('Até três áreas; arraste e teclado ajustam/persistem larguras; compacto sem corte; grafo com zoom intermediário, foco, pan, relação real e redução/ocultação sem movimento.');
 await add('Explorer');await page.getByRole('button',{name:'Explorar Projeto local',exact:true}).click();await page.getByRole('button',{name:'Arquivo README.md',exact:true}).click();const pe=page.getByRole('textbox',{name:'Conteúdo do arquivo',exact:true});await pe.click();await pe.press('Control+End');await page.keyboard.insertText('\nRascunho do projeto dividido.');await add('PDF');await page.locator('canvas[data-rendered-page="2"]').waitFor();await pe.focus();assert.equal(await page.locator('.workspace-pane-choices>div.selected select').inputValue(),'explorer');await shot('explorer-split');const ps=await page.locator('.project-status').boundingBox();assert.ok(ps&&ps.y+ps.height<910);await page.getByRole('combobox',{name:'Módulo 1',exact:true}).focus();await page.getByRole('button',{name:'Tela única',exact:true}).click();await idle();
 await module('city');await page.locator('canvas[data-ready=true]').waitFor();assert.equal(await page.locator('.game-inspector').isVisible(),false);await page.getByRole('button',{name:'Motor',exact:true}).click();await busyDone();const initial=await state();
 await page.getByRole('button',{name:'Gerar moedas',exact:true}).click();await page.waitForTimeout(45);assert.notEqual(await page.locator('.motor-module .engine-wheel').evaluate(e=>getComputedStyle(e).transform),'none');await busyDone();
 await page.getByRole('button',{name:'Gerar moedas',exact:true}).evaluate((e,count)=>{for(let i=0;i<count;i++)(e as HTMLButtonElement).click();},60);await busyDone();const clicked=await state();assert.equal(clicked.engine.clicks,initial.engine.clicks+61);assert.equal(clicked.coins,initial.coins+61*initial.engine.power);await shot('motor');
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(50);await page.getByRole('button',{name:'Gerar moedas',exact:true}).click();await busyDone();assert.equal(await page.locator('.motor-module .engine-wheel').evaluate(e=>getComputedStyle(e).transform),'none');await page.emulateMedia({reducedMotion:'no-preference'});await page.getByRole('button',{name:'Gerar moedas',exact:true}).click();await busyDone();await page.waitForTimeout(280);const rotation=await page.locator('.motor-module .engine-wheel').evaluate(e=>Number((e as HTMLElement).style.transform.match(/rotate\(([-.\d]+)deg\)/)?.[1]??0));assert.ok(Math.abs(rotation)<50);
 await page.getByRole('button',{name:'Oficina',exact:true}).click();await page.getByRole('combobox',{name:'Ritmo dos desafios',exact:true}).selectOption('normal');await page.getByRole('button',{name:/Sincronizar o motor/}).click();await busyDone();let c=(await state()).challenge!;assert.equal(c.sequence.length,36);await page.getByTestId('workshop-preparing').waitFor();const started=Date.now();await page.getByTestId('qte-key').waitFor();
 for(let i=0;i<36;i++){c=(await state()).challenge!;assert.equal(c.stage,i);if(i>0)assert.equal(c.readyAt,c.stepAt);await page.keyboard.press(c.sequence[i]);await busyDone();await page.waitForFunction(stage=>Number(document.querySelector('.challenge-score')?.textContent?.match(/^(\d+)/)?.[1])===stage,i+1);if(i<35)assert.equal(await page.getByTestId('workshop-preparing').count(),0);}
 durations.qte=Date.now()-started;assert.ok(durations.qte<60000);assert.equal((await state()).challenge!.hits,36);assert.equal((await state()).challenge!.coins,300);
 await page.getByRole('combobox',{name:'Ritmo dos desafios',exact:true}).selectOption('relaxed');await page.getByRole('button',{name:/Calibrar a válvula/}).click();await busyDone();const skillStart=Date.now();await page.getByTestId('workshop-preparing').waitFor();await page.getByTestId('skill-track').waitFor();await shot('office');
 for(let i=0;i<36;i++){c=(await state()).challenge!;assert.equal(c.stage,i);if(i>0)assert.equal(c.readyAt,c.stepAt);await page.waitForFunction(()=>{const t=document.querySelector<HTMLElement>('[data-testid=skill-track]');if(!t||Math.abs(Number(t.dataset.position)-Number(t.dataset.target))>=1.8)return false;const button=Array.from(document.querySelectorAll<HTMLButtonElement>('.challenge-panel button')).find(b=>b.textContent==='Calibrar válvula');if(!button||button.disabled)return false;button.click();return true;});await busyDone();await page.waitForFunction(stage=>Number(document.querySelector('.challenge-score')?.textContent?.match(/^(\d+)/)?.[1])===stage,i+1);if(i<35)assert.equal(await page.getByTestId('workshop-preparing').count(),0);}
 durations.skill=Date.now()-skillStart;console.log('Oficina completa',durations);assert.ok(durations.skill<90000);assert.equal((await state()).challenge!.hits,36);checks.push(`Motor: 61 cliques rápidos exatos e animação imediata/reduzida. Oficina real: QTE ${durations.qte}ms e calibração ${durations.skill}ms, 36 acertos cada, sem preparo intermediário.`);
 await page.getByRole('button',{name:'Mercado',exact:true}).click();await page.getByRole('button',{name:'Comprar Moinho',exact:true}).waitFor();await page.getByRole('button',{name:'Personagem',exact:true}).click();await page.getByRole('button',{name:'Salvar build · grátis',exact:true}).waitFor();await page.getByRole('button',{name:'Memória',exact:true}).click();await page.getByRole('combobox',{name:'Dificuldade da memória',exact:true}).selectOption('hard');await page.getByRole('button',{name:'Começar rodada →',exact:true}).click();await busyDone();assert.equal((await state()).round!.cards.length,18);
 await add('PDF');await page.locator('canvas[data-rendered-page="2"]').waitFor();await add('Caderno');await page.getByRole('combobox',{name:'Módulo 1',exact:true}).focus();await page.getByRole('separator',{name:'Largura do módulo 1',exact:true}).press('Shift+ArrowRight');await page.waitForFunction(async()=>{const p=await window.desktop.getPreferences();return p.ok&&p.value.workspaceLayout.sizes[0]>38;});const layoutBeforeClose=(await prefs()).workspaceLayout;await page.getByRole('button',{name:'Motor',exact:true}).click();await busyDone();
 await page.getByRole('button',{name:'Abrir foco',exact:true}).click();await page.getByRole('button',{name:'Iniciar foco',exact:true}).click();await page.getByRole('button',{name:'Pausar foco',exact:true}).waitFor();await page.getByRole('button',{name:'Fechar painel suspenso',exact:true}).click();await page.mouse.move(80,90);await page.locator('.suspended-popover').waitFor({state:'hidden'});
 const beforeClose=await state();await page.getByRole('button',{name:'Gerar moedas',exact:true}).evaluate(e=>{for(let i=0;i<40;i++)(e as HTMLButtonElement).click();});await closeWindow();app=await launch();page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.getByTestId('version').waitFor();await idle();assert.deepEqual((await prefs()).workspaceLayout,layoutBeforeClose);const retainedFocus=await page.evaluate(subjectId=>window.desktop.getFocus({subjectId}),fixture.a.id);assert.ok(retainedFocus.ok&&retainedFocus.value.session?.state==='paused'&&!retainedFocus.value.session.recovered);assert.equal((await state()).engine.clicks,beforeClose.engine.clicks+40);await page.locator('canvas[data-rendered-page="2"]').waitFor();const draft=await page.evaluate(id=>window.desktop.openNote({id}),fixture.noteA.ref.id);assert.ok(draft.ok&&draft.value.draft?.text.includes('Rascunho de divisão preservado.'));
 const reopenedProject=await page.evaluate(ref=>window.desktop.openProjectFile(ref),{projectId,path:'README.md'});assert.ok(reopenedProject.ok&&reopenedProject.value.draft?.text.includes('Rascunho do projeto dividido.'));assert.deepEqual(fs.readFileSync(projectFile),projectSource);
 for(const original of originals)assert.deepEqual(fs.readFileSync(original.file),original.bytes);assert.deepEqual(errors,[]);checks.push('Fechar drena 40 cliques pendentes; restart conserva larguras ajustadas, foco pausado, jogo, PDF2 e draft; fontes intactas. Memória/mercado/personagem continuam acessíveis.');
 fs.writeFileSync('.local/evidence/clean-results.json',JSON.stringify({date:new Date().toISOString(),fixture:fixture.dir,checks,durations,layoutBeforeClose,errors},null,2));console.log(checks.join('\n'));
}catch(error){await shot('failure').catch(()=>{});fs.writeFileSync('.local/evidence/clean-failure.txt',String(error));throw error;}finally{await app.close().catch(()=>{});}
