import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {_electron as electron,type Page} from 'playwright';
import {prepareFixture} from './test-fixture';
import {Store} from '../src/main/store';
import {Vault} from '../src/main/vault';
import {Checklist} from '../src/main/checklist';
import {Game} from '../src/main/game';
import {UserPreferences} from '../src/main/preferences';
import type {GameState} from '../src/shared/game';

// Generated content and material/clock seeds only. All actions use the packaged IPC,
// filesystem and SQLite. No personal profile, vault or production service is opened.
const f=prepareFixture('visual-experience'),data=path.join(f.dir,'data'),out='.local/evidence/visual-experience';fs.mkdirSync(out,{recursive:true});
const seed=new Store(data);seed.renameSubject({id:f.a.id,name:'Matemática'});seed.renameSubject({id:f.b.id,name:'Programação'});
const v=new Vault(seed);v.save({id:f.noteA.ref.id,hash:f.noteA.hash,text:f.noteA.text+'\n# Uma ideia leva a outra\n\n## Regra da cadeia\n\nPara derivar uma função composta, observe primeiro a função de fora e depois a de dentro.\n\n**Exemplo:** se f(x) = (3x + 1)², então f′(x) = 6(3x + 1).\n\n## Minha explicação\n\nCada etapa da transformação contribui para a variação do resultado.\n\n## Próximo passo\n\n- [ ] Resolver dois exemplos sem consultar a fórmula.\n'});
const checklist=new Checklist(seed),task=checklist.create(f.a.id,'Resolver dois exemplos da regra da cadeia');checklist.add({subjectId:f.a.id,taskId:task.id,text:'Explicar com minhas palavras'});
new UserPreferences(seed).update({name:'Rafael · perfil de demonstração',theme:'editorial'});
new Game(seed).get();const raw=JSON.parse(String(seed.db.prepare('SELECT state FROM game_player').get()!.state));raw.inventory={wood:45,stone:45,wheat:10,carrot:5};seed.db.prepare('UPDATE game_player SET state=?').run(JSON.stringify(raw));seed.close();
const source=fs.readFileSync(path.join(f.root,f.noteA.ref.path)),originalPdf=fs.readFileSync(f.pdfB),importFile=path.join(f.dir,'ideia-importada.md');fs.writeFileSync(importFile,'# Ideia importada\n\nMaterial de demonstração, preservado no arquivo original.\n');const originalImport=fs.readFileSync(importFile);const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
let app=await electron.launch({executablePath:path.resolve('release/win-unpacked/App Estudos.exe'),args:[`--user-data-dir=${data}`],env}),page=await app.firstWindow();
const errors:string[]=[],graphicsErrors:string[]=[],checks:string[]=[],shots:string[]=[],clips:string[]=[],metrics:Record<string,unknown>={};
function listen(){page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(msg.type()==='error'&&/WebGL|shader|THREE/i.test(msg.text()))graphicsErrors.push(msg.text());});}listen();
async function idle(){await page.locator('.area-stage[data-motion=idle]').waitFor();await page.locator('.activity-rail[aria-busy=false]').waitFor();}
async function shot(name:string){const file=path.join(out,name+'.png');await page.waitForFunction(()=>{const dialog=document.querySelector('dialog[open]');return !dialog||Number(getComputedStyle(dialog).opacity)>.99;});await page.screenshot({path:file});shots.push(path.basename(file));console.log('CAPTURE '+name);}
async function game():Promise<GameState>{const r=await page.evaluate(()=>window.desktop.getGame());assert.ok(r.ok);return r.value;}
async function record(canvasTestId:string,name:string){const result=await page.evaluate(async({id})=>{const canvas=document.querySelector<HTMLCanvasElement>(`canvas[data-testid="${id}"]`)!;const stream=canvas.captureStream(15),chunks:Blob[]=[];const type=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm';const recorder=new MediaRecorder(stream,{mimeType:type,videoBitsPerSecond:1400000});const done=new Promise<void>((resolve,reject)=>{recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>resolve();recorder.onerror=e=>reject(e);});recorder.start();await new Promise(r=>setTimeout(r,4500));recorder.stop();await done;stream.getTracks().forEach(track=>track.stop());const buffer=await new Blob(chunks,{type}).arrayBuffer();return {bytes:Array.from(new Uint8Array(buffer)),type};},{id:canvasTestId});assert.ok(result.bytes.length>1000);fs.writeFileSync(path.join(out,name+'.webm'),Buffer.from(result.bytes));clips.push(name+'.webm');console.log('CLIP '+name);}
async function frameInfo(selector:string){return page.locator(selector).evaluate(el=>({...((el as HTMLElement).dataset)}));}
async function content(){await page.locator('.rail-subject').getByRole('button',{name:'Adicionar conteúdo',exact:true}).click();await page.getByRole('dialog',{name:'Adicionar conteúdo',exact:true}).waitFor();}
try{
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1440,1000));await page.getByRole('textbox',{name:'Título da nota',exact:true}).waitFor();await idle();await shot('caderno');
 await page.getByRole('button',{name:'Abrir início',exact:true}).click();await idle();await page.getByRole('region',{name:'Próximo passo sugerido',exact:true}).getByRole('button',{name:'Continuar esta tarefa',exact:true}).waitFor();
 const book='canvas[data-testid=study-sculpture]';await page.locator(book+'[data-ready=true]').waitFor();await shot('hoje');const before=await frameInfo(book);await page.waitForTimeout(1000);const after=await frameInfo(book);assert.ok(Number(after.frames)>Number(before.frames)&&Number(after.time)>Number(before.time));metrics.book={drawCalls:after.drawCalls,renderedFramesPerSecond:Number(after.frames)-Number(before.frames)};
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator(book+'[data-motion=still]').waitFor();const still=await frameInfo(book);await page.waitForTimeout(350);assert.equal((await frameInfo(book)).frames,still.frames);assert.equal(still.motion,'still');await page.emulateMedia({reducedMotion:'no-preference'});
 await page.getByRole('button',{name:'Continuar esta tarefa',exact:true}).click();await idle();await page.getByRole('region',{name:'Painel de checklist',exact:true}).waitFor({state:'visible'});await page.getByRole('button',{name:'Fechar painel suspenso',exact:true}).click();checks.push('Hoje usa checklist existente; botão abre matéria e ferramenta. Livro 3D movimenta e fica estático com movimento reduzido.');
 await content();await shot('adicionar-conteudo');await page.getByRole('button',{name:/Escrever uma nota/}).click();await page.getByRole('dialog',{name:'Adicionar conteúdo',exact:true}).waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('#note-title-input')?.value==='Sem título');assert.equal(await page.locator('dialog[open]').count(),0);await page.keyboard.insertText('Ideia capturada sem preencher formulários.');await page.getByRole('button',{name:'Salvar nota',exact:true}).click();await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('#note-title-input')?.value==='Ideia capturada sem preencher formulários.');
 await content();await page.getByRole('button',{name:/Guardar uma aula/}).click();await page.getByRole('textbox',{name:'Link do YouTube',exact:true}).fill('https://www.youtube.com/watch?v=M7lc1UVf-VE');await page.getByRole('textbox',{name:'Título do vídeo',exact:true}).fill('Aula de demonstração');await page.getByRole('button',{name:'Salvar link',exact:true}).click();await page.locator('dialog[open]').waitFor({state:'hidden'});await shot('aulas');
 // Only the native picker result is selected by the harness; imported bytes and
 // all validations are real. This does not verify operating the Windows picker.
 await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},f.pdfB);
 await content();await page.getByRole('button',{name:/Trazer um PDF/}).click();await idle();await page.locator('canvas[data-rendered-page="1"]').waitFor();await shot('pdf');
 await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},importFile);
 await content();await page.getByRole('button',{name:/Importar notas/}).click();await idle();await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('#note-title-input')?.value==='Ideia importada');assert.deepEqual(fs.readFileSync(f.pdfB),originalPdf);assert.deepEqual(fs.readFileSync(importFile),originalImport);
 checks.push('Painel reutiliza escrita com título automático, aula salva e PDF real; seleção do diálogo nativo é fixture explícita.');
 await page.getByRole('button',{name:'Voltar aos estudos',exact:true}).click();await idle();await page.getByRole('button',{name:'Minhas notas',exact:true}).first().click();await shot('acervo');await page.getByRole('button',{name:'Fechar acervo',exact:true}).click();
 await page.getByRole('button',{name:'Entrar na cidade',exact:true}).click();await idle();const city='canvas[data-testid=city-canvas]';await page.locator(city+'[data-ready=true]').waitFor();await shot('projeto-em-construcao');
 for(const project of ['Depósito','Posto do bosque','Posto da mina']){await page.getByRole('button',{name:'Construir '+project,exact:true}).click();await page.locator('.game-shell[aria-busy=false]').waitFor();await page.waitForTimeout(200);if(project==='Depósito'){assert.equal((await frameInfo(city)).emitting,'true');await shot('construcao-3d');}}
 await page.waitForTimeout(900);await shot('cidade-valeserene');const start=await frameInfo(city);await page.waitForTimeout(1200);const end=await frameInfo(city);assert.ok(Number(end.effectsTime)>Number(start.effectsTime));assert.equal(end.farmWorking,'2');metrics.city={drawCalls:end.drawCalls,triangles:end.triangles,renderedFramesPerSecond:(Number(end.frames)-Number(start.frames))/1.2};
 for(const skin of ['cyberpunk','newyork','original']){await page.getByRole('combobox',{name:'Skin da cidade',exact:true}).selectOption(skin);await page.locator(`canvas[data-skin="${skin}"]`).waitFor();await page.waitForTimeout(300);if(skin!=='original'){await page.getByRole('button',{name:'Noite',exact:true}).click();await page.locator('.game-shell[aria-busy=false]').waitFor();await shot('cidade-'+skin);}}
 await page.getByRole('button',{name:'Dourado',exact:true}).click();await page.locator('.game-shell[aria-busy=false]').waitFor();await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(200);const frozen=await frameInfo(city);await page.waitForTimeout(700);assert.equal((await frameInfo(city)).effectsTime,frozen.effectsTime);await page.emulateMedia({reducedMotion:'no-preference'});
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].minimize());await page.waitForTimeout(300);const minimized=await frameInfo(city);await page.waitForTimeout(350);assert.equal((await frameInfo(city)).frames,minimized.frames);await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.restore();w.show();});await page.waitForTimeout(350);
 await page.getByRole('button',{name:'Abrir início',exact:true}).click();await idle();const hidden=await frameInfo(city);await page.waitForTimeout(500);assert.equal((await frameInfo(city)).frames,hidden.frames);await page.locator(book+'[data-ready=true]').waitFor();
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1040,760));await page.waitForTimeout(300);await shot('hoje-compacto');const bounds=await page.locator('.workspace-body').evaluate(el=>({bottom:el.getBoundingClientRect().bottom,height:innerHeight,overflow:document.documentElement.scrollWidth>innerWidth}));assert.ok(bounds.bottom<=bounds.height&&!bounds.overflow);
 for(const theme of ['olive','midnight','graphite']){const r=await page.evaluate(theme=>window.desktop.updatePreferences({theme:theme as 'olive'|'midnight'|'graphite'}),theme);assert.ok(r.ok);await page.reload();await page.getByTestId('version').waitFor();await idle();await shot('tema-'+theme);}
 checks.push('Três skins, construção com partículas confirmadas, água e postos em movimento, modo reduzido, minimização e área oculta; janela1040×760.');
 await page.evaluate(()=>window.desktop.updatePreferences({theme:'editorial'}));await page.reload();await page.getByTestId('version').waitFor();await idle();await page.getByRole('button',{name:'Entrar na cidade',exact:true}).click();await idle();await page.locator(city+'[data-ready=true]').waitFor();await shot('cidade-compacta');
 // Loss of GPU context must not disable the independent, typed game controls.
 await page.locator(city).evaluate(el=>(el as HTMLCanvasElement).getContext('webgl2')?.getExtension('WEBGL_lose_context')?.loseContext());await page.getByRole('alert').filter({hasText:'cenário 3D foi interrompido'}).waitFor();await page.getByRole('button',{name:'Motor',exact:true}).click();await page.getByRole('button',{name:'Gerar Produção',exact:true}).click();await page.locator('.game-shell[aria-busy=false]').waitFor();checks.push('Perda real de contexto WebGL conserva ferramentas e motor.');
 assert.deepEqual(fs.readFileSync(path.join(f.root,f.noteA.ref.path)),source);assert.deepEqual(errors,[]);assert.deepEqual(graphicsErrors,[]);
 await app.close();const fresh=fs.mkdtempSync(path.resolve('.local/visual-first-use-')),documents=path.join(fresh,'documents');fs.mkdirSync(documents);app=await electron.launch({executablePath:path.resolve('release/win-unpacked/App Estudos.exe'),args:[`--user-data-dir=${path.join(fresh,'data')}`],env});page=await app.firstWindow();listen();await app.evaluate(({app},dir)=>app.setPath('documents',dir),documents);await page.getByRole('button',{name:'Voltar aos estudos',exact:true}).click();await idle();await page.getByRole('button',{name:'Preparar pasta de notas',exact:true}).waitFor();await page.locator(book+'[data-ready=true]').waitFor();await shot('primeiro-uso');
 await page.getByRole('button',{name:'Abrir início',exact:true}).click();await idle();await page.getByRole('button',{name:'Escrever agora',exact:true}).click();await page.getByRole('textbox',{name:'Nome da matéria',exact:true}).fill('Minha primeira matéria');await page.getByRole('button',{name:'Criar matéria',exact:true}).click();await page.getByRole('textbox',{name:'Conteúdo da nota',exact:true}).waitFor();assert.equal(await page.locator('dialog[open]').count(),0);assert.ok(fs.existsSync(path.join(documents,'NodusNotes')));await shot('primeira-nota');checks.push('Primeiro uso pelo Hoje prepara pasta isolada, cria matéria e abre nota sem formulário adicional.');
 // Record after screenshots, in a fresh process: captureStream can leave stale
 // compositor tiles in later native screenshots on this Chromium/Windows host.
 await app.close();app=await electron.launch({executablePath:path.resolve('release/win-unpacked/App Estudos.exe'),args:[`--user-data-dir=${data}`],env});page=await app.firstWindow();listen();await page.getByTestId('version').waitFor();
 await page.getByRole('button',{name:'Abrir início',exact:true}).click();await idle();await page.locator(book+'[data-ready=true]').waitFor();await record('study-sculpture','ideias-3d');
 await page.getByRole('button',{name:'Entrar na cidade',exact:true}).click();await idle();await page.locator(city+'[data-ready=true]').waitFor();await record('city-canvas','cidade-viva');
 assert.deepEqual(errors,[]);assert.deepEqual(graphicsErrors,[]);fs.writeFileSync(path.join(out,'windows.json'),JSON.stringify({at:new Date().toISOString(),platform:process.platform,packaged:true,fixture:'generated study content, isolated material/clock seeds; native picker selection not verified',checks,metrics,errors,graphicsErrors,screenshots:shots,clips},null,2));console.log(JSON.stringify({checks,metrics,errors,graphicsErrors},null,2));
}catch(e){await shot('failure').catch(()=>{});throw e;}finally{await app.close().catch(()=>{});}
