import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { _electron as electron } from 'playwright';
import { prepareFixture } from './test-fixture';
import { Store } from '../src/main/store';
import { Projects } from '../src/main/projects';
const fixture=prepareFixture('pdf-export'),data=path.join(fixture.dir,'data'),downloads=path.join(fixture.dir,'downloads');fs.mkdirSync(downloads);
const markdown='# Exportação de demonstração\n\n## Uma leitura com contraste\n\nEste caderno usa **texto claro**, títulos e margem de leitura sobre fundo preto. Acentos: ação, revisão, equação.\n\n> Uma ideia importante merece espaço para respirar.\n\n- Primeiro conceito\n- Segundo conceito\n\n| Conceito | Exemplo |\n|---|---|\n| Energia | E = mc² |\n| Revisão | Uma pergunta por vez |\n\n```typescript\nconst assunto = "Estudos";\nconst revisar = (titulo: string) => `Revisar: ${titulo}`;\n```\n\n';
const example=path.join(fixture.root,'00-demonstracao.md');fs.writeFileSync(example,'---\nunknown: preserved\n---\n'+markdown+Array.from({length:34},(_,i)=>`### Tópico ${i+1}\n\n${'Conteúdo de demonstração para verificar a paginação. '.repeat(8)}\n\n`).join(''));
const project=path.join(fixture.dir,'Caderno de demonstração');fs.mkdirSync(project);fs.writeFileSync(path.join(project,'README.md'),markdown);fs.writeFileSync(path.join(project,'source.ts'),'export const ignored=true;\r\n');
const db=new Store(data),registered=new Projects(db).chooseRoot(project);db.close();
fs.mkdirSync(path.join(project,'vazio'));
const originals=new Map([example,path.join(project,'README.md'),path.join(project,'source.ts')].map(file=>[file,fs.readFileSync(file)]));
const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
const app=await electron.launch({executablePath:path.resolve('release/win-unpacked/App Estudos.exe'),args:[`--user-data-dir=${data}`],env}),page=await app.firstWindow();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
try {
  // Real Electron path configuration confines this fixture's output; no dialog, IPC, FS or print mocks.
  await app.evaluate(({app},target)=>app.setPath('downloads',target),downloads);
  await app.evaluate(({app,session})=>{(globalThis as any).__pdfRuntime=[];app.on('browser-window-created',(_event,win)=>{win.webContents.on('did-finish-load',()=>{if(win.webContents.getURL().startsWith('nodus-pdf:'))(globalThis as any).__pdfRuntime.push({url:win.webContents.getURL(),prefs:win.webContents.getLastWebPreferences(),isolated:win.webContents.session!==session.defaultSession,storage:win.webContents.session.getStoragePath(),preloads:win.webContents.session.getPreloads()});});});});
  await page.getByRole('heading',{name:'Nota A',exact:true}).waitFor();
  await page.getByRole('button',{name:'Abrir configurações',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-area=settings]')?.getAttribute('aria-hidden')==='false' && document.querySelector('[data-testid=area-stage]')?.getAttribute('data-motion')==='idle');
  await page.getByRole('button',{name:'Dados e app',exact:true}).click();const exportButton=page.getByRole('button',{name:'Exportar pasta em PDF',exact:true});await exportButton.waitFor();await page.waitForFunction(()=>!document.querySelector<HTMLButtonElement>('.settings-export>button')?.disabled);
  await exportButton.click();await page.getByRole('textbox',{name:'PDF exportado',exact:true}).waitFor({timeout:60000});const first=await page.getByRole('textbox',{name:'PDF exportado',exact:true}).inputValue();assert.ok(first.startsWith(downloads+path.sep));assert.ok(fs.readFileSync(first).subarray(0,5).equals(Buffer.from('%PDF-')));
  await page.locator('.settings-export').scrollIntoViewIfNeeded();await page.screenshot({path:'.local/evidence/export-settings.png'});
  await exportButton.click();await page.waitForFunction(old=>(document.querySelector<HTMLInputElement>('[aria-label="PDF exportado"]')?.value||'')!==old && !!document.querySelector('[aria-label="PDF exportado"]'),first);const second=await page.getByRole('textbox',{name:'PDF exportado',exact:true}).inputValue();assert.notEqual(second,first);assert.ok(fs.existsSync(first));
  await page.getByRole('combobox',{name:'Origem da exportação',exact:true}).selectOption(registered.projects[0].id);await page.waitForFunction(()=>!document.querySelector<HTMLButtonElement>('.settings-export>button')?.disabled);await exportButton.click();await page.getByRole('textbox',{name:'PDF exportado',exact:true}).waitFor({timeout:60000});const projectPdf=await page.getByRole('textbox',{name:'PDF exportado',exact:true}).inputValue();assert.ok((await page.locator('.settings-export-result').textContent())?.includes('1 nota'));
  const filesBefore=fs.readdirSync(downloads);await page.getByRole('combobox',{name:'Pasta para exportar',exact:true}).selectOption('vazio');await exportButton.click();await page.getByRole('alert').filter({hasText:'não contém notas Markdown'}).waitFor();assert.deepEqual(fs.readdirSync(downloads),filesBefore);await page.getByRole('combobox',{name:'Pasta para exportar',exact:true}).selectOption('');
  const rejectDb=new Store(data);rejectDb.db.exec("CREATE TRIGGER reject_export_audit BEFORE INSERT ON audit_events WHEN NEW.action='pdf:export' BEGIN SELECT RAISE(ABORT,'fixture audit failure'); END");rejectDb.close();
  await exportButton.click();await page.getByRole('alert').filter({hasText:'Não foi possível concluir a operação'}).waitFor();assert.deepEqual(fs.readdirSync(downloads),filesBefore);assert.equal(await page.getByRole('textbox',{name:'PDF exportado',exact:true}).count(),0);
  const restoreDb=new Store(data);restoreDb.db.exec('DROP TRIGGER reject_export_audit');restoreDb.close();
  const concurrent=await page.evaluate(async()=>Promise.all([window.desktop.exportFolderPdf({source:'vault',folder:''}),window.desktop.exportFolderPdf({source:'vault',folder:''})]));assert.equal(concurrent.filter(r=>r.ok).length,1);assert.ok(concurrent.some(r=>!r.ok&&r.code==='EXPORT_BUSY'));
  const invalid=await page.evaluate(async()=>[await window.desktop.exportFolderPdf({source:'vault',folder:'../outside'}),await window.desktop.exportFolderPdf({source:'vault',folder:'',path:'C:/outside'} as never),await window.desktop.pdfExportFolders({source:'project',projectId:'00000000-0000-4000-8000-000000000001'})]);assert.ok(invalid.every(r=>!r.ok));
  const foreign=await app.evaluate(async({BrowserWindow})=>{const win=new BrowserWindow({show:false,webPreferences:{nodeIntegration:true,contextIsolation:false,sandbox:false}});try{await win.loadURL('data:text/html,fixture');return await win.webContents.executeJavaScript("Promise.all([require('electron').ipcRenderer.invoke('pdf:folders',{source:'vault'}),require('electron').ipcRenderer.invoke('pdf:export',{source:'vault',folder:''})])");}finally{win.destroy();}});assert.ok(foreign.every((r:{ok:boolean;code:string})=>!r.ok&&r.code==='FORBIDDEN'));
  assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length),1,'superfície oculta foi destruída');
  const runtime=await app.evaluate(()=>(globalThis as any).__pdfRuntime);assert.equal(runtime.length,5);for(const item of runtime){assert.equal(item.prefs.javascript,false);assert.equal(item.prefs.nodeIntegration,false);assert.equal(item.prefs.contextIsolation,true);assert.equal(item.prefs.sandbox,true);assert.equal(item.prefs.webSecurity,true);assert.ok(!item.prefs.preload);assert.equal(item.isolated,true);assert.equal(item.storage,null);assert.deepEqual(item.preloads,[]);}
  const auditDb=new Store(data),audit=auditDb.db.prepare("SELECT action,entity_id,outcome FROM audit_events WHERE action='pdf:export' AND outcome='ok'").all();auditDb.close();assert.equal(audit.length,4);for(const item of audit){assert.match(String(item.entity_id),/^[0-9a-f-]{36}$/);assert.ok(!JSON.stringify(item).includes(downloads));}
  for(const[file,bytes]of originals)assert.deepEqual(fs.readFileSync(file),bytes);assert.deepEqual(errors,[]);
  fs.copyFileSync(projectPdf,'.local/evidence/export-sample.pdf');fs.writeFileSync('.local/evidence/export-results.json',JSON.stringify({date:new Date().toISOString(),packaged:true,fixture:fixture.dir,first,second,projectPdf,emptyFolder:'UI error/no artifact',auditFailure:'real SQLite trigger/UI error/no artifact/no receipt',audit,concurrent,runtime,invalid,foreign,errors},null,2));
  console.log('PDF real pela UI/IPC/Chromium e FS, vault/subpastas e projeto Markdown, nomes únicos sem sobrescrita; fontes intactas, payload/sender negados, superfície limpa e zero pageerrors.');
}finally{await app.close();}
