import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { _electron as electron } from 'playwright';
import { prepareFixture } from './test-fixture';
import { Store } from '../src/main/store';
import { Projects } from '../src/main/projects';
const fixture = prepareFixture('settings'), data = path.join(fixture.dir, 'data');
const project = path.join(fixture.dir, 'project'); fs.mkdirSync(project); const projectFile = path.join(project, 'example.ts'); fs.writeFileSync(projectFile, '\uFEFFexport const fixture = true;\r\n');
const db = new Store(data); new Projects(db).chooseRoot(project); db.close();
const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
async function launch() { return electron.launch({ executablePath: path.resolve('release/win-unpacked/App Estudos.exe'), args: [`--user-data-dir=${data}`], env }); }
let app = await launch(), page = await app.firstWindow(); const reports: string[] = [], errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
async function settled(area: string) { await page.waitForFunction(area => document.querySelector('[data-testid=area-stage]')?.getAttribute('data-motion') === 'idle' && document.querySelector(`[data-area="${area}"]`)?.getAttribute('aria-hidden') === 'false', area); }
async function settings() { await page.getByRole('button', {name:'Abrir configurações',exact:true}).click(); await settled('settings'); }
async function prefs() { const r = await page.evaluate(() => window.desktop.getPreferences()); assert.ok(r.ok); return r.value; }
async function shot(name: string) { await page.screenshot({path:`.local/evidence/settings-${name}.png`}); }
try {
  await page.getByRole('heading',{name:'Nota A',exact:true}).waitFor();
  const editor = page.getByRole('textbox',{name:'Conteúdo da nota',exact:true}); await editor.click(); await page.keyboard.press('Control+End'); await page.keyboard.insertText('\nRascunho conservado durante configurações.');
  await editor.evaluate(el => el.setAttribute('data-settings-editor','retained'));
  await settings(); assert.equal(await page.locator('[data-settings-editor=retained]').count(),1);
  await page.getByRole('textbox',{name:'Nome do perfil',exact:true}).fill('Perfil de demonstração'); await page.getByRole('button',{name:'Salvar perfil',exact:true}).click(); await page.getByRole('status').filter({hasText:'Perfil salvo'}).waitFor(); assert.equal((await prefs()).name,'Perfil de demonstração');
  const raster = await app.evaluate(({nativeImage}) => {
    const width=96,height=64, pixels=Buffer.alloc(width*height*4);
    for(let y=0;y<height;y++)for(let x=0;x<width;x++){const i=(y*width+x)*4;pixels[i]=70+Math.floor(x*1.1);pixels[i+1]=80+Math.floor(y*1.3);pixels[i+2]=130;pixels[i+3]=255;}
    const image=nativeImage.createFromBitmap(pixels,{width,height});return {png:image.toPNG().toString('base64'),jpeg:image.toJPEG(90).toString('base64')};
  });
  const png=path.join(fixture.dir,'avatar-fixture.png'),jpeg=path.join(fixture.dir,'avatar-fixture.jpg'),fake=path.join(fixture.dir,'invalid-fixture.png');fs.writeFileSync(png,Buffer.from(raster.png,'base64'));fs.writeFileSync(jpeg,Buffer.from(raster.jpeg,'base64'));fs.writeFileSync(fake,'<svg onload="fixture">not raster</svg>');
  const photo=page.getByLabel('Arquivo da foto do perfil',{exact:true});await photo.setInputFiles(png);await page.getByRole('status').filter({hasText:'Foto atualizada'}).waitFor();const originalPhoto=(await prefs()).photo;assert.ok(originalPhoto?.startsWith('data:image/png;base64,'));
  const dimensions=await app.evaluate(({nativeImage},url)=>nativeImage.createFromDataURL(url!).getSize(),originalPhoto);assert.deepEqual(dimensions,{width:256,height:256});
  await photo.setInputFiles(fake);await page.getByRole('alert').filter({hasText:'PNG ou JPEG'}).waitFor();assert.equal((await prefs()).photo,originalPhoto);
  await photo.setInputFiles(jpeg);await page.waitForFunction(()=>!document.querySelector('.settings-main [role=alert]') && !document.querySelector<HTMLInputElement>('.settings-file')?.disabled);assert.ok((await prefs()).photo?.startsWith('data:image/png;base64,'));
  await page.getByRole('button',{name:'Remover foto',exact:true}).click();await page.getByRole('status').filter({hasText:'Foto removida'}).waitFor();assert.equal((await prefs()).photo,null);
  await photo.setInputFiles(png);await page.getByRole('status').filter({hasText:'Foto atualizada'}).waitFor();await shot('profile');
  reports.push('Perfil/PNG/JPEG reais pelo input de arquivo e IPC; normalização256×256, foto inválida conserva anterior, remoção conserva nome e novo upload.');
  await page.getByRole('button',{name:'Aparência',exact:true}).click();const colors:string[]=[];
  for(const [theme,title] of [['graphite','Grafite'],['midnight','Azul noite'],['olive','Oliva']] as const){await page.getByRole('button',{name:new RegExp(`^${title}`)}).click();await page.waitForFunction(theme=>document.documentElement.dataset.theme===theme,theme);colors.push(await page.locator('.settings-workspace').evaluate(el=>getComputedStyle(el).backgroundColor));assert.equal((await prefs()).theme,theme);}
  assert.equal(new Set(colors).size,3);await page.getByRole('button',{name:/^Azul noite/}).click();await page.waitForFunction(()=>document.documentElement.dataset.theme==='midnight');
  await page.getByRole('switch',{name:'Animações da interface',exact:true}).click();await page.waitForFunction(()=>document.documentElement.dataset.animations==='off');assert.equal(await page.getByRole('button',{name:/^Azul noite/}).evaluate(el=>getComputedStyle(el).transitionDuration),'0s');await shot('appearance');
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(1040,760));await page.waitForFunction(()=>innerWidth===1040);assert.ok(await page.getByRole('switch',{name:'Animações da interface',exact:true}).isVisible());await shot('compact');await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(1424,900));await page.waitForFunction(()=>innerWidth===1424);
  await page.getByRole('button',{name:'Entrar na cidade',exact:true}).click();await settled('city');await page.locator('canvas[data-ready=true]').waitFor();const canvas=page.locator('canvas[data-ready=true]');await canvas.evaluate(el=>el.setAttribute('data-settings-city','retained'));
  await page.getByRole('button',{name:'Visitar bosque',exact:true}).click();await page.waitForTimeout(90);assert.equal(await canvas.getAttribute('data-camera'),'idle');const pose=await canvas.evaluate(el=>({x:el.getAttribute('data-target-x'),z:el.getAttribute('data-target-z')}));await page.waitForTimeout(160);assert.deepEqual(await canvas.evaluate(el=>({x:el.getAttribute('data-target-x'),z:el.getAttribute('data-target-z')})),pose);
  await settings();await page.getByRole('switch',{name:'Animações da interface',exact:true}).click();await page.waitForFunction(()=>document.documentElement.dataset.animations==='on');await page.getByRole('button',{name:'Entrar na cidade',exact:true}).click();await settled('city');assert.equal(await page.locator('[data-settings-city=retained]').count(),1);await page.getByRole('button',{name:'Visitar fazenda',exact:true}).click();await page.waitForTimeout(110);assert.equal(await canvas.getAttribute('data-camera'),'moving');
  await settings();await page.getByRole('switch',{name:'Animações da interface',exact:true}).click();await page.waitForFunction(()=>document.documentElement.dataset.animations==='off');await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('switch',{name:'Animações da interface',exact:true}).click();await page.waitForFunction(()=>document.documentElement.dataset.animations==='on');await page.getByRole('button',{name:'Entrar na cidade',exact:true}).click();await settled('city');await page.getByRole('button',{name:'Visitar bosque',exact:true}).click();await page.waitForTimeout(90);assert.equal(await canvas.getAttribute('data-camera'),'idle');await page.emulateMedia({reducedMotion:'no-preference'});await settings();await page.getByRole('switch',{name:'Animações da interface',exact:true}).click();await page.waitForFunction(()=>document.documentElement.dataset.animations==='off');
  reports.push('Três paletas com cores computadas distintas; off CSS/GSAP/Three, on restaura câmera, preferência Windows continua prevalecendo; mesmo canvas e editor conservados.');
  await page.getByRole('button',{name:'Dados e app',exact:true}).click();await page.getByRole('textbox',{name:'Pasta de dados do app',exact:true}).waitFor();assert.equal(await page.getByRole('textbox',{name:'Pasta de dados do app',exact:true}).inputValue(),data);assert.equal(await page.getByRole('textbox',{name:'Pasta de notas',exact:true}).inputValue(),fixture.root);const management=await page.evaluate(()=>window.desktop.getAppManagement());assert.ok(management.ok);assert.deepEqual({...management.value.counts,drafts:0},{subjects:2,notes:2,materials:2,videos:0,projects:1,drafts:0});assert.ok(management.value.databaseBytes>0);assert.ok(management.value.counts.drafts>=1);await shot('data');
  const invalid=await page.evaluate(async()=>({prefs:await window.desktop.updatePreferences({theme:'remote'} as never),photo:await window.desktop.setProfilePhoto({bytes:new Uint8Array([1,2])}),folder:await window.desktop.openAppFolder({folder:'data',path:'C:/outside'} as never)}));for(const r of Object.values(invalid))assert.equal(r.ok,false);
  const opened=await page.evaluate(()=>window.desktop.openAppFolder({folder:'data'}));assert.ok(opened.ok,'shell.openPath deve aceitar o diretório fictício registrado');
  const before=await prefs();
  const foreign=await app.evaluate(async({BrowserWindow})=>{
    const win=new BrowserWindow({show:false,webPreferences:{nodeIntegration:true,contextIsolation:false,sandbox:false}});
    try{await win.loadURL('data:text/html,fixture');return await win.webContents.executeJavaScript(`Promise.all([['preferences:get'],['preferences:update',{name:'forbidden'}],['profile:photo',{bytes:new Uint8Array([1])}],['profile:photo-remove'],['app:management'],['app:folder',{folder:'data'}]].map(([channel,input])=>require('electron').ipcRenderer.invoke(channel,input)))`);}finally{win.destroy();}
  });for(const r of foreign as {ok:boolean;code:string}[])assert.deepEqual({ok:r.ok,code:r.code},{ok:false,code:'FORBIDDEN'});assert.deepEqual(await prefs(),before);
  await page.getByRole('button',{name:'Gerenciar projetos no Explorer',exact:true}).click();await settled('explorer');await page.getByRole('button',{name:'Arquivo example.ts',exact:true}).click();await page.getByRole('textbox',{name:'Conteúdo do arquivo',exact:true}).waitFor();const projectBackground=await page.locator('.project-editor .cm-editor').evaluate(el=>getComputedStyle(el).backgroundColor);assert.equal(projectBackground,'rgb(17, 29, 45)');
  const code=page.getByRole('textbox',{name:'Conteúdo do arquivo',exact:true});await code.click();await page.keyboard.press('Control+End');await page.keyboard.insertText('// rascunho preservado\r\n');await settings();await page.locator('.settings-main').getByRole('button',{name:'Voltar aos estudos',exact:true}).click();await settled('study');assert.equal(await page.locator('[data-settings-editor=retained]').count(),1);assert.ok(await editor.innerText().then(t=>t.includes('Rascunho conservado')));await page.keyboard.press('Control+s');await page.waitForFunction(()=>document.querySelector('.note-foot')?.textContent?.includes('Arquivo atualizado'));
  const final=await prefs();await app.close();app=await launch();page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.getByRole('heading',{name:'Nota A',exact:true}).waitFor();assert.deepEqual(await prefs(),final);assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'midnight');assert.equal(await page.evaluate(()=>document.documentElement.dataset.animations),'off');assert.ok(fs.readFileSync(path.join(fixture.root,fixture.noteA.ref.path),'utf8').includes('Rascunho conservado'));
  await settings();await page.getByRole('button',{name:'Dados e app',exact:true}).click();await page.getByRole('button',{name:'Gerenciar projetos no Explorer',exact:true}).click();await settled('explorer');await page.getByRole('textbox',{name:'Conteúdo do arquivo',exact:true}).waitFor();assert.ok(await page.getByRole('textbox',{name:'Conteúdo do arquivo',exact:true}).innerText().then(t=>t.includes('rascunho preservado')));assert.equal(fs.readFileSync(projectFile,'utf8'),'\uFEFFexport const fixture = true;\r\n');await page.keyboard.press('Control+s');await page.getByRole('status').filter({hasText:'Salvo no arquivo'}).waitFor();assert.ok(fs.readFileSync(projectFile,'utf8').startsWith('\uFEFFexport const fixture = true;\r\n'));
  reports.push('Gestão consulta banco/paths/runtime reais, shell.openPath retorna sucesso para pasta de dados fictícia; argumentos e seis canais de outro sender negados; restart conserva perfil/foto/tema/off, nota salva e projeto BOM/CRLF/draft conservados.');
  assert.deepEqual(errors,[]);fs.writeFileSync('.local/evidence/settings-results.json',JSON.stringify({date:new Date().toISOString(),fixture:fixture.dir,packaged:true,reports,colors,photoDimensions:dimensions,opened,foreign,errors},null,2));console.log(reports.join('\n'));
}catch(error){await shot('failure').catch(()=>{});throw error;}finally{await app.close();}
