import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {_electron as electron,type Page} from 'playwright';
import {prepareFixture} from './test-fixture';
import {Store} from '../src/main/store';
import {UserPreferences} from '../src/main/preferences';
import {Checklist} from '../src/main/checklist';
import {Projects} from '../src/main/projects';

// Isolated generated notes/PDFs and real packaged IPC/files/SQLite. No personal data.
const f=prepareFixture('home-white'),data=path.join(f.dir,'data'),out='.local/evidence/home-white';fs.mkdirSync(out,{recursive:true});
const seed=new Store(data);seed.renameSubject({id:f.a.id,name:'Matemática'});seed.renameSubject({id:f.b.id,name:'Programação'});
new UserPreferences(seed).update({name:'Rafael · demonstração',theme:'editorial'});new Checklist(seed).create(f.a.id,'Continuar meu estudo de hoje');
const projectRoot=path.join(f.dir,'Projeto de demonstração');fs.mkdirSync(projectRoot);const code='// Um exemplo de estudo\nexport function calcularArea(base: number, altura: number) {\n  const unidade = "cm²";\n  return { area: base * altura / 2, unidade };\n}\n';const projectFile=path.join(projectRoot,'area.ts');fs.writeFileSync(projectFile,code);new Projects(seed).chooseRoot(projectRoot);seed.close();
const original=fs.readFileSync(path.join(f.root,f.noteA.ref.path)),env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
let app=await electron.launch({executablePath:path.resolve('release/win-unpacked/App Estudos.exe'),args:[`--user-data-dir=${data}`],env}),page=await app.firstWindow();
const errors:string[]=[],graphicsErrors:string[]=[],checks:string[]=[],screenshots:string[]=[],metrics:Record<string,unknown>={};
function listen(){page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/WebGL|shader|THREE/i.test(m.text()))graphicsErrors.push(m.text());});}listen();
async function idle(){await page.locator('.area-stage[data-motion=idle]').waitFor();await page.locator('.activity-rail[aria-busy=false]').waitFor();}
async function home(){await page.getByRole('button',{name:'Abrir início',exact:true}).click();await idle();await page.locator('[data-testid=home-workspace]:not([data-component-motion=entering])').waitFor();await page.locator('canvas[data-testid=home-background][data-ready=true]').waitFor();}
async function shot(name:string){await page.screenshot({path:path.join(out,name+'.png')});screenshots.push(name+'.png');console.log('CAPTURE '+name);}
async function background(){return page.locator('canvas[data-testid=home-background]').evaluate(el=>({...((el as HTMLElement).dataset),rect:{x:el.getBoundingClientRect().x,y:el.getBoundingClientRect().y,width:el.getBoundingClientRect().width,height:el.getBoundingClientRect().height}}));}
async function draftText(){return (await page.getByRole('textbox',{name:'Conteúdo da nota',exact:true}).locator('.cm-line').allTextContents()).join('\n');}
async function animationSetting(enabled:boolean){await page.getByRole('button',{name:'Abrir configurações',exact:true}).click();await idle();await page.getByRole('button',{name:'Aparência',exact:true}).click();await page.getByRole('switch',{name:'Animações da interface',exact:true}).setChecked(enabled);await page.waitForFunction(value=>document.documentElement.dataset.animations===value,enabled?'on':'off');await home();}
async function record(){const bytes=await page.evaluate(async()=>{const canvas=document.querySelector<HTMLCanvasElement>('canvas[data-testid=home-background]')!,stream=canvas.captureStream(15),chunks:Blob[]=[];const recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp9'});const done=new Promise<void>(r=>{recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>r();});recorder.start();await new Promise(r=>setTimeout(r,4000));recorder.stop();await done;stream.getTracks().forEach(t=>t.stop());return [...new Uint8Array(await new Blob(chunks).arrayBuffer())];});assert.ok(bytes.length>1000);fs.writeFileSync(path.join(out,'fundo-home.webm'),Buffer.from(bytes));}
try{
 await page.getByRole('textbox',{name:'Título da nota',exact:true}).waitFor();await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1440,1000));
 await page.getByRole('button',{name:'Abrir início',exact:true}).click();await page.locator('[data-testid=home-workspace][data-component-motion=entering]').waitFor();const entrance=await page.locator('[data-home-enter]').evaluateAll(els=>els.map(el=>({opacity:Number(getComputedStyle(el).opacity),transform:getComputedStyle(el).transform})));assert.ok(entrance.some(p=>p.opacity<.99&&p.transform!=='none'));metrics.entrance=entrance;await idle();await page.locator('[data-testid=home-workspace][data-component-motion=idle]').waitFor();await page.locator('canvas[data-testid=home-background][data-ready=true]').waitFor();const first=await background();await page.waitForTimeout(850);const next=await background();assert.ok(Number(next.time)>Number(first.time));metrics.frames=Number(next.frames)-Number(first.frames);
 const card=page.getByRole('button',{name:'Abrir caderno pela Home',exact:true});await card.hover();await page.waitForTimeout(330);assert.notEqual(await card.evaluate(el=>getComputedStyle(el).transform),'none');await page.mouse.move(200,90);await page.waitForTimeout(350);await shot('home-editorial');
 await page.locator('.home-scroll').evaluate(el=>{el.scrollTop=550;});await page.waitForTimeout(200);assert.deepEqual((await background()).rect,next.rect);await shot('home-rolagem');await page.locator('.home-scroll').evaluate(el=>{el.scrollTop=0;});
 checks.push('Home/contexto/atalhos reais; fundo WebGL avança, hover transforma cartão e posição do canvas permanece idêntica na rolagem.');
 await page.getByRole('button',{name:'Abrir configurações',exact:true}).click();await idle();await page.getByRole('button',{name:'Aparência',exact:true}).click();await page.locator('[data-preview=white]').click();await page.waitForFunction(()=>document.documentElement.dataset.theme==='white');await shot('tema-branco-ajustes');
 const pref=await page.evaluate(()=>window.desktop.getPreferences());assert.ok(pref.ok&&pref.value.theme==='white');await home();await shot('home-branca');
 await page.getByRole('button',{name:'Adicionar conteúdo',exact:true}).first().click();await page.locator('dialog[open]').waitFor();await page.waitForTimeout(500);await shot('conteudo-branco');await page.keyboard.press('Escape');await page.locator('dialog[open]').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Abrir caderno pela Home',exact:true}).click();await idle();const editor=page.getByRole('textbox',{name:'Conteúdo da nota',exact:true});const draft='# Demonstração do tema branco\n\nUma ideia de demonstração conservada ao navegar.';await editor.fill(draft);await shot('caderno-branco');await home();await page.getByRole('button',{name:'Abrir caderno pela Home',exact:true}).click();await idle();assert.equal((await draftText()).trim(),draft);
 for(const [label,name,wait] of [['Abrir PDF','pdf-branco','canvas[data-rendered-page="2"]'],['Abrir Vídeo','aulas-brancas','.video-library'],['Abrir revisões','revisao-branca','.review-workspace'],['Abrir grafo','conexoes-brancas','[data-testid=graph-canvas]'],['Abrir Explorer','projetos-brancos','.project-shell'],['Entrar na cidade','cidade-branca','canvas[data-testid=city-canvas][data-ready=true]']] as const){await page.getByRole('button',{name:label,exact:true}).first().click();await idle();await page.locator(wait).first().waitFor();await page.waitForTimeout(200);await shot(name);}
 await page.getByRole('button',{name:'Abrir Explorer',exact:true}).click();await idle();await page.getByRole('button',{name:'Explorar Projeto de demonstração',exact:true}).click();await page.getByRole('button',{name:'Arquivo area.ts',exact:true}).click();const codeEditor=page.getByRole('textbox',{name:'Conteúdo do arquivo',exact:true});await codeEditor.waitFor();assert.equal((await codeEditor.locator('.cm-line').allTextContents()).join('\n'),code);const keyword=await codeEditor.locator('span').filter({hasText:/^export$/}).first().evaluate(el=>getComputedStyle(el).color);assert.equal(keyword,'rgb(113, 71, 128)');metrics.codeKeyword=keyword;await shot('editor-projeto-branco');assert.equal(fs.readFileSync(projectFile,'utf8'),code);
 await home();await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(250);const reduced=await background();await page.waitForTimeout(400);assert.equal((await background()).time,reduced.time);assert.equal(reduced.motion,'still');await page.emulateMedia({reducedMotion:'no-preference'});
 await animationSetting(false);await page.waitForTimeout(150);const off=await background();await page.waitForTimeout(350);assert.equal((await background()).time,off.time);await animationSetting(true);
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].minimize());await page.waitForTimeout(200);const minimized=await background();await page.waitForTimeout(300);assert.equal((await background()).frames,minimized.frames);await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].restore();BrowserWindow.getAllWindows()[0].show();});
 await page.getByRole('button',{name:'Voltar aos estudos',exact:true}).click();await idle();const inactive=await background();await page.waitForTimeout(400);assert.equal((await background()).frames,inactive.frames);await home();
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1040,760));await page.waitForTimeout(350);await shot('home-branca-compacta');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 checks.push('Branco escolhido nos Ajustes e aplicado ao conteúdo/caderno/PDF/revisão/conexões/projetos/cidade; rascunho, reduzido, desligado, minimização e área oculta preservados.');
 await app.close();app=await electron.launch({executablePath:path.resolve('release/win-unpacked/App Estudos.exe'),args:[`--user-data-dir=${data}`],env});page=await app.firstWindow();listen();await page.getByRole('heading',{name:'Seu ponto de partida.',exact:true}).waitFor();await idle();assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'white');await page.getByRole('button',{name:'Abrir caderno pela Home',exact:true}).click();await idle();assert.equal((await draftText()).trim(),draft);assert.deepEqual(fs.readFileSync(path.join(f.root,f.noteA.ref.path)),original);checks.push('Restart conserva tema branco, Home ativa e rascunho; Markdown original permanece intacto.');
 await home();await page.locator('canvas[data-testid=home-background]').evaluate(el=>(el as HTMLCanvasElement).getContext('webgl2')?.getExtension('WEBGL_lose_context')?.loseContext());await page.locator('.home-background[data-fallback=true]').waitFor();await page.getByRole('button',{name:'Abrir caderno pela Home',exact:true}).click();await idle();await page.getByRole('textbox',{name:'Conteúdo da nota',exact:true}).waitFor();checks.push('Perda real de WebGL conserva Home e navegação.');
 await app.close();const fresh=fs.mkdtempSync(path.resolve('.local/home-first-use-')),documents=path.join(fresh,'documents');fs.mkdirSync(documents);app=await electron.launch({executablePath:path.resolve('release/win-unpacked/App Estudos.exe'),args:[`--user-data-dir=${path.join(fresh,'data')}`],env});page=await app.firstWindow();listen();await app.evaluate(({app},dir)=>app.setPath('documents',dir),documents);await page.getByRole('heading',{name:'Seu ponto de partida.',exact:true}).waitFor();await idle();await page.locator('[data-testid=home-workspace]:not([data-component-motion=entering])').waitFor();await shot('home-primeiro-uso');await page.getByRole('button',{name:'Escrever agora',exact:true}).click();await page.getByRole('textbox',{name:'Nome da matéria',exact:true}).fill('Minha primeira matéria');await page.getByRole('button',{name:'Criar matéria',exact:true}).click();await page.getByRole('textbox',{name:'Conteúdo da nota',exact:true}).waitFor();checks.push('Perfil novo inicia na Home e Escrever agora prepara pasta/matéria/nota pelo fluxo real.');
 // Record after screenshots in a fresh process, avoiding known captureStream tiles.
 await app.close();app=await electron.launch({executablePath:path.resolve('release/win-unpacked/App Estudos.exe'),args:[`--user-data-dir=${data}`],env});page=await app.firstWindow();listen();await page.getByTestId('version').waitFor();await home();await record();assert.deepEqual(errors,[]);assert.deepEqual(graphicsErrors,[]);
 fs.writeFileSync(path.join(out,'windows.json'),JSON.stringify({at:new Date().toISOString(),platform:process.platform,packaged:true,fixture:'isolated generated study content; no personal data',checks,metrics,errors,graphicsErrors,screenshots,clip:'fundo-home.webm'},null,2));console.log(checks.join('\n'));
}catch(e){await shot('failure').catch(()=>{});throw e;}finally{await app.close().catch(()=>{});}
