import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {_electron as electron} from 'playwright';
import {prepareFixture,generatePdf} from './test-fixture';
import {Store} from '../src/main/store';
import {Videos} from '../src/main/videos';
import {Annotations} from '../src/main/annotations';
import {Desks} from '../src/main/desk';

// Isolated, explicitly named fixtures exercise real packaged Windows IPC/files/SQLite/PDF.js.
const f=prepareFixture('notes-ux'),data=path.join(f.dir,'data'),seed=new Store(data),videos=new Videos(seed);
const video=videos.add({subjectId:f.a.id,title:'Aula de demonstração',url:'https://www.youtube.com/watch?v=M7lc1UVf-VE'});
new Annotations(seed,new Desks(seed),videos).addMoment({subjectId:f.a.id,videoId:video.id,seconds:75,text:'Minha anotação de aula sem reescrever.'});new Desks(seed).save({subjectId:f.a.id,videoId:video.id});
new Annotations(seed,new Desks(seed),videos).addMark({subjectId:f.a.id,materialId:f.materialA.id,noteId:f.noteA.ref.id,fingerprint:createHash('sha256').update(fs.readFileSync(f.pdfA)).digest('hex'),page:2,x:.1,y:.1,width:.5,height:.05,color:'gold',comment:'Comentário de demonstração reutilizado na nota.'});
const emptySubject=seed.createSubject({name:'Matéria sem nota',color:'rose'}),emptyPdf=path.join(f.dir,'sem-nota.pdf');generatePdf(emptyPdf,'sem-nota');const emptyMaterial=new Desks(seed).choose(emptySubject.id,emptyPdf);new Desks(seed).save({subjectId:emptySubject.id,materialId:emptyMaterial.id,page:1});seed.close();
const originalPdf=fs.readFileSync(f.pdfA),originalOther=fs.readFileSync(path.join(f.root,f.noteB.ref.path));
const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
const evidence='.local/evidence/notes-ux';fs.mkdirSync(evidence,{recursive:true});
let app=await electron.launch({executablePath:path.resolve('release/win-unpacked/App Estudos.exe'),args:[`--user-data-dir=${data}`],env}),page=await app.firstWindow();
const errors:string[]=[],checks:string[]=[],screenshots:string[]=[];
function listen(){page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));}listen();
async function idle(){await page.locator('.area-stage[data-motion=idle]').waitFor();await page.locator('.activity-rail[aria-busy=false]').waitFor();}
async function shot(name:string){const file=path.join(evidence,name+'.png');await page.screenshot({path:file});screenshots.push(file);console.log('CAPTURE '+name);}
async function close(){const done=new Promise<void>(resolve=>app.once('close',()=>resolve()));await page.getByRole('button',{name:'Fechar janela',exact:true}).click();await done;}
async function current(){const desk=await page.evaluate(id=>window.desktop.openDesk({subjectId:id}),f.a.id);assert.ok(desk.ok&&desk.value.noteId);if(!desk.ok||!desk.value.noteId)throw Error();const note=await page.evaluate(id=>window.desktop.openNote({id}),desk.value.noteId);assert.ok(note.ok);if(!note.ok)throw Error();return note.value;}
try{
 await page.getByRole('textbox',{name:'Título da nota',exact:true}).waitFor();await idle();
 const invalid=await page.evaluate(input=>window.desktop.moveNote(input),{id:f.noteA.ref.id,subjectId:f.b.id,hash:'invalid'});assert.ok(!invalid.ok&&invalid.code==='INVALID_ARGUMENT');
 const denied=await app.evaluate(async({BrowserWindow},input)=>{const probe=new BrowserWindow({show:false,webPreferences:{nodeIntegration:true,contextIsolation:false,sandbox:false}});try{await probe.loadURL('data:text/html,<title>Isolated UX IPC probe</title>');return await probe.webContents.executeJavaScript(`Promise.all([['vault:setup',undefined],['notes:import',{subjectId:'${input.move.subjectId}'}],['note:move',${JSON.stringify(input.move)}],['player:at',${JSON.stringify(input.video)}]].map(([channel,input])=>require('electron').ipcRenderer.invoke(channel,input)))`);}finally{probe.destroy();}},{move:{id:f.noteA.ref.id,subjectId:f.b.id,hash:f.noteA.hash},video:{subjectId:f.a.id,id:video.id,seconds:75}});assert.ok(denied.every(r=>!r.ok&&r.code==='FORBIDDEN'));
 await page.locator('.rail-subject').getByRole('button',{name:'Nova nota',exact:true}).click();
 const title=page.getByRole('textbox',{name:'Título da nota',exact:true}),editor=page.getByRole('textbox',{name:'Conteúdo da nota',exact:true});
 await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('#note-title-input')?.value==='Sem título');assert.equal(await page.locator('dialog[open]').count(),0);
 assert.equal(await editor.textContent(),'');assert.equal(await editor.evaluate(el=>el.contains(document.activeElement)),true);
 await page.keyboard.insertText('Uma explicação simples.\n\nTermo exclusivo: quadrivetor.');await page.getByRole('button',{name:'Salvar nota',exact:true}).click();await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('#note-title-input')?.value==='Uma explicação simples.');
 await title.fill('Regra da cadeia');await page.getByRole('button',{name:'Salvar nota',exact:true}).click();let note=await current(),noteId=note.ref.id;assert.equal(note.ref.title,'Regra da cadeia');
 assert.ok(note.text.includes('study_id: '+noteId));assert.ok(!(await editor.textContent())?.includes('study_id'));await shot('writing');
 await page.getByText('Usar modelo',{exact:true}).click();await page.getByRole('button',{name:'Conceito',exact:true}).click();assert.ok((await editor.textContent())?.includes('Minha explicação'));await page.getByText('Usar modelo',{exact:true}).click();
 await page.getByText('Mais formatação e fonte',{exact:true}).click();await page.getByRole('button',{name:'Ver fonte completa',exact:true}).click();assert.ok((await editor.textContent())?.includes('study_id'));await page.getByRole('button',{name:'Ocultar metadados',exact:true}).click();await page.getByText('Mais formatação e fonte',{exact:true}).click();
 await editor.click();await page.keyboard.press('Control+End');await page.keyboard.insertText('\nRascunho pesquisável: eletrolise.');await page.keyboard.press('Control+k');await page.getByRole('textbox',{name:'Busca global',exact:true}).fill('eletrolise');await page.getByRole('option').filter({hasText:'Regra da cadeia'}).waitFor();await shot('search');await page.keyboard.press('Escape');
 checks.push('Nota em um clique/foco imediato; título sugerido/editável; modelo e fonte completa preservam identidade; busca encontra rascunho pelo corpo.');
 await page.getByRole('button',{name:'Relacionar nota',exact:true}).click();await page.getByRole('combobox',{name:'Nota relacionada',exact:true}).selectOption(f.noteA.ref.id);await page.getByRole('button',{name:'Conectar notas',exact:true}).click();await page.locator('dialog[open]').waitFor({state:'hidden'});
 await editor.click();await page.keyboard.press('Control+a');await page.getByRole('button',{name:'Criar cartão do trecho',exact:true}).click();await page.getByRole('textbox',{name:'Pergunta do flashcard',exact:true}).fill('O que é um quadrivetor?');assert.equal(await page.getByRole('combobox',{name:'Matéria do novo flashcard',exact:true}).count(),0);await page.getByRole('button',{name:'Salvar flashcard',exact:true}).click();await page.locator('dialog[open]').waitFor({state:'hidden'});await idle();
 const cards=await page.evaluate(()=>window.desktop.listFlashcards({}));assert.ok(cards.ok&&cards.value.some(c=>c.noteId===noteId));
 await page.getByRole('button',{name:'Voltar aos estudos',exact:true}).click();await idle();await page.getByRole('button',{name:'Dividir com PDFs',exact:true}).click();await idle();
 await page.locator('.textLayer span').first().waitFor();const textSpan=await page.locator('.textLayer span').first().boundingBox();assert.ok(textSpan);await page.mouse.dblclick(textSpan.x+textSpan.width*.1,textSpan.y+textSpan.height*.5);await page.getByRole('button',{name:'Adicionar à nota',exact:true}).waitFor({state:'visible'});assert.equal(await page.getByRole('button',{name:'Adicionar à nota',exact:true}).isEnabled(),true);await shot('pdf-selection');await page.getByRole('button',{name:'Adicionar à nota',exact:true}).click();await page.getByRole('button',{name:'Salvar nota',exact:true}).click();note=await current();assert.ok(note.text.includes('nodus-source:pdf/'+f.materialA.id+'?page=2&version='));assert.equal(note.ref.id,noteId);await shot('captured');
 await page.getByRole('button',{name:'Praticar este material',exact:true}).click();await idle();await page.getByRole('checkbox').first().waitFor();assert.equal(await page.locator('input[type=checkbox]:checked').count(),1);assert.ok((await page.locator('input[type=checkbox]:checked').locator('..').textContent())?.includes('fixture-A.pdf'));await shot('practice');
 await page.getByRole('button',{name:'Voltar aos estudos',exact:true}).click();await idle();await page.getByRole('button',{name:'Dividir com PDFs',exact:true}).click();await idle();await page.getByRole('button',{name:'Adicionar comentário à nota',exact:true}).click();await page.getByRole('button',{name:'Salvar nota',exact:true}).click();assert.ok((await current()).text.includes('Comentário de demonstração reutilizado na nota.'));await page.getByRole('button',{name:'Leitura',exact:true}).click();await page.locator('.markdown-preview').getByRole('button',{name:'fixture-A.pdf · página 2',exact:true}).first().click();await page.locator('canvas[data-rendered-page="2"]').waitFor();await page.getByRole('button',{name:'Editar',exact:true}).click();
 checks.push('Conexão e cartão por seleção, formulário curto; seleção real no PDF e inserção com página/versão; prática abre PDF pré-selecionado.');
 assert.ok(!(await editor.textContent())?.includes('nodus-source:'));await editor.click();await page.keyboard.press('Control+End');await page.keyboard.insertText('Minha explicação após capturar.');await page.getByRole('button',{name:'Salvar nota',exact:true}).click();assert.ok((await current()).text.includes('nodus-source:pdf/'+f.materialA.id));
 await page.getByRole('button',{name:'Abrir Vídeo',exact:true}).click();await idle();await page.getByRole('button',{name:'Adicionar à nota',exact:true}).click();await idle();await page.getByRole('button',{name:'Salvar nota',exact:true}).click();note=await current();assert.ok(note.text.includes('nodus-source:video/'+video.id+'?seconds=75'));await shot('video-note');
 const beforeMove=note.text;await page.getByRole('combobox',{name:'Matéria da nota',exact:true}).selectOption(f.b.id);await page.waitForFunction(id=>document.querySelector<HTMLSelectElement>('[aria-label="Matéria atual"]')?.value===id,f.b.id);await idle();
 const moved=await page.evaluate(id=>window.desktop.openNote({id}),noteId);assert.ok(moved.ok&&moved.value.ref.subjectId===f.b.id);if(!moved.ok)throw Error();assert.equal(moved.value.text.replace(f.b.id,f.a.id),beforeMove);await shot('moved');
 const links=await page.evaluate(id=>window.desktop.noteLinks({subjectId:id}),f.b.id);assert.ok(links.ok&&links.value.some(l=>l.sourceId===noteId));await page.getByRole('button',{name:'Abrir grafo',exact:true}).click();await idle();await page.getByTestId('graph-canvas').waitFor();await page.getByRole('button',{name:'Mostrar notas e relações',exact:true}).click();await page.getByRole('button',{name:'Regra da cadeia',exact:true}).first().waitFor();await page.getByRole('button',{name:'Nota A',exact:true}).first().waitFor();
 await page.getByRole('button',{name:'Voltar aos estudos',exact:true}).click();await idle();await page.getByRole('button',{name:'Nova aba',exact:true}).click();await idle();await page.getByRole('button',{name:'Dividir com PDFs',exact:true}).click();await idle();await page.getByRole('button',{name:'Dividir com Conexões',exact:true}).click();await idle();await page.getByTestId('graph-canvas').waitFor();
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1040,760));await page.waitForTimeout(600);await shot('compact');
 const geometry=await page.locator('.workspace-body').evaluate(el=>{const r=el.getBoundingClientRect();return {bottom:r.bottom,height:innerHeight,overflow:document.documentElement.scrollWidth>innerWidth};});assert.ok(geometry.bottom<=geometry.height&&!geometry.overflow);
 await page.getByRole('button',{name:'Recolher menu lateral',exact:true}).click();await page.getByRole('button',{name:'Expandir menu lateral',exact:true}).click();
 checks.push('Momento de aula reutilizado; mudança de matéria conserva nota/cartão/relação; grafo mostra conexões antigas; abas/divisões e menu em1040×760.');
 await close();app=await electron.launch({executablePath:path.resolve('release/win-unpacked/App Estudos.exe'),args:[`--user-data-dir=${data}`],env});page=await app.firstWindow();listen();await page.getByRole('textbox',{name:'Título da nota',exact:true}).waitFor();await idle();assert.equal(await page.getByRole('tab').count(),2);const restarted=await page.evaluate(id=>window.desktop.openNote({id}),noteId);assert.ok(restarted.ok&&restarted.value.text===moved.value.text);await shot('restart');
 await page.getByRole('combobox',{name:'Matéria atual',exact:true}).selectOption(emptySubject.id);await page.getByRole('button',{name:'Abrir PDF',exact:true}).click();await idle();await page.locator('canvas[aria-label="Página 1 do PDF sem-nota.pdf"][data-rendered-page="1"]').waitFor();const emptyText=page.locator('.textLayer span').filter({hasText:'Test fixture sem-nota'}).first();await emptyText.waitFor();await emptyText.dblclick();await page.getByRole('button',{name:'Criar nota do trecho',exact:true}).click();await page.getByRole('textbox',{name:'Título da nota',exact:true}).waitFor();await page.getByRole('button',{name:'Salvar nota',exact:true}).click();const capturedNotes=await page.evaluate(subjectId=>window.desktop.listNotes({subjectId}),emptySubject.id);assert.ok(capturedNotes.ok&&capturedNotes.value.length===1);const created=await page.evaluate(id=>window.desktop.openNote({id}),capturedNotes.value[0].id);assert.ok(created.ok&&created.value.text.includes('nodus-source:pdf/'+emptyMaterial.id));await shot('capture-new-note');await close();
 assert.deepEqual(fs.readFileSync(f.pdfA),originalPdf);assert.deepEqual(fs.readFileSync(path.join(f.root,f.noteB.ref.path)),originalOther);
 const fresh=fs.mkdtempSync(path.resolve('.local/notes-ux-first-')),documents=path.join(fresh,'documents');fs.mkdirSync(documents);
 app=await electron.launch({executablePath:path.resolve('release/win-unpacked/App Estudos.exe'),args:[`--user-data-dir=${path.join(fresh,'data')}`],env});page=await app.firstWindow();listen();await app.evaluate(({app},dir)=>app.setPath('documents',dir),documents);await page.getByRole('button',{name:'Voltar aos estudos',exact:true}).click();await idle();await page.getByRole('button',{name:'Preparar pasta de notas',exact:true}).waitFor();await shot('first-use');await page.getByRole('button',{name:'Preparar pasta de notas',exact:true}).click();await page.getByRole('button',{name:'Criar primeira matéria',exact:true}).click();await page.getByRole('textbox',{name:'Nome da matéria',exact:true}).fill('Minha primeira matéria');await page.getByRole('button',{name:'Criar matéria',exact:true}).click();await page.locator('.rail-subject').getByRole('button',{name:'Nova nota',exact:true}).click();await page.getByRole('textbox',{name:'Conteúdo da nota',exact:true}).waitFor();assert.ok(fs.existsSync(path.join(documents,'NodusNotes')));await shot('first-note');await close();
 checks.push('Reinício conserva dados/abas; primeiro uso real prepara pasta isolada, matéria e nota sem formulário de título.');assert.deepEqual(errors,[]);
 checks.push('Captura sem nota cria arquivo real; comentário do PDF reutilizado e fonte volta à página2; edição mostra nome/página enquanto Markdown conserva UUID/hash; quatro novos canais negam outra janela e move rejeita hash inválido.');
 fs.writeFileSync(path.join(evidence,'results.json'),JSON.stringify({platform:process.platform,fixture:f.dir,checks,errors,screenshots},null,2));console.log(JSON.stringify({checks,errors},null,2));
}finally{await app.close().catch(()=>{});}
