import { useEffect,useRef,useState } from 'react';
import type { Subject,Result } from '../shared/contracts';
import { DEFAULT_PROMPT_LIMIT,IMPORT_BYTES,type ActivityType,type ActivityRequest,type ActivitySummary,type SourceStatus,type ValidationReport,type QuizSession,type ActivityCard,type Provenance,type SourceContext } from '../shared/study-activity';
import { MotionDialog } from './MotionDialog';
import './activities.css';
export type ActivityLaunch={subjectId:string;type:ActivityType|null;nonce:string;source?:{kind:'note'|'pdf'|'video';id:string}};
export function ActivitiesWorkspace({launch,activeSubjectId,openSource}:{launch:ActivityLaunch|null;activeSubjectId:string|null;openSource(subjectId:string,context:SourceContext):Promise<void>}){
  const [subjects,setSubjects]=useState<Subject[]>([]),[subject,setSubject]=useState(launch?.subjectId??activeSubjectId??''),[view,setView]=useState<'library'|'prepare'|'practice'>(launch?.type?'prepare':'library');
  const [sources,setSources]=useState<SourceStatus[]>([]),[selected,setSelected]=useState<string[]>([]),[type,setType]=useState<ActivityType>(launch?.type??'quiz'),[level,setLevel]=useState<'easy'|'medium'|'hard'>('medium'),[limit,setLimit]=useState(DEFAULT_PROMPT_LIMIT);
  const [requests,setRequests]=useState<Omit<ActivityRequest,'packet'|'prompt'|'sourceSizes'>[]>([]),[request,setRequest]=useState<ActivityRequest|null>(null),[activities,setActivities]=useState<ActivitySummary[]>([]),[activity,setActivity]=useState<ActivitySummary|null>(null);
  const [raw,setRaw]=useState(''),[report,setReport]=useState<ValidationReport|null>(null),[repair,setRepair]=useState<{text:string;short:boolean}|null>(null),[copied,setCopied]=useState<'prompt'|'correction'|null>(null),[manual,setManual]=useState(false);
  const [quiz,setQuiz]=useState<QuizSession|null>(null),[cards,setCards]=useState<ActivityCard[]>([]),[index,setIndex]=useState(0),[revealed,setRevealed]=useState(false),[context,setContext]=useState<SourceContext|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const guard=useRef(false),file=useRef<HTMLInputElement>(null),pendingRequest=useRef<ActivityRequest|null>(null);
  useEffect(()=>{void window.desktop.bootstrap().then(r=>{if(r.ok){setSubjects(r.value.subjects);if(!subject)setSubject(r.value.activeSubjectId??r.value.subjects[0]?.id??'');}else setError(r.message);});},[]);
  useEffect(()=>{if(!launch)return;setSubject(launch.subjectId);setView(launch.type?'prepare':'library');if(launch.type)setType(launch.type);setRequest(null);setReport(null);setSelected(launch.source?[`${launch.source.kind}:${launch.source.id}`]:[]);},[launch?.nonce]);
  useEffect(()=>{let stopped=false;if(!subject)return;const pending=pendingRequest.current;pendingRequest.current=null;setRequest(pending?.subjectId===subject?pending:null);setReport(null);setSelected(pending?.subjectId===subject?pending.packet.sources.map(s=>`${s.kind}:${s.id}`):launch?.subjectId===subject&&launch.source?[`${launch.source.kind}:${launch.source.id}`]:[]);void Promise.all([window.desktop.activitySources({subjectId:subject}),window.desktop.activityRequests({subjectId:subject}),window.desktop.listActivities({subjectId:subject})]).then(([s,r,a])=>{if(stopped)return;if(s.ok)setSources(s.value);else setError(s.message);if(r.ok)setRequests(r.value);else setError(r.message);if(a.ok)setActivities(a.value);else setError(a.message);}).catch(()=>{if(!stopped)setError('Não foi possível carregar as atividades.');});return()=>{stopped=true;};},[subject]);
  function unwrap<T>(result:Result<T>):T{if(!result.ok)throw Error(result.message);return result.value;}
  async function run(action:()=>Promise<void>){if(guard.current)return;guard.current=true;setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir. Seu texto foi conservado.');}finally{guard.current=false;setBusy(false);}}
  const key=(s:Pick<SourceStatus,'kind'|'id'>)=>`${s.kind}:${s.id}`;
  function invalidate(){setRequest(null);setReport(null);setRepair(null);setCopied(null);}
  function begin(kind:ActivityType){setType(kind);setView('prepare');invalidate();}
  async function refresh(){const [r,a]=await Promise.all([window.desktop.activityRequests({subjectId:subject}),window.desktop.listActivities({subjectId:subject})]);setRequests(unwrap(r));setActivities(unwrap(a));}
  async function prepare(){await run(async()=>{const next=unwrap(await window.desktop.prepareActivity({subjectId:subject,type,difficulty:level,promptLimit:limit,sources:sources.filter(s=>selected.includes(key(s))).map(({kind,id})=>({kind,id}))}));setRequest(next);setRaw('');setReport(null);setRepair(null);setCopied(null);setManual(false);await refresh();});}
  async function resume(id:string,keepText=false,owner=subject){await run(async()=>{const next=unwrap(await window.desktop.activityRequest({subjectId:owner,requestId:id}));if(owner!==subject){pendingRequest.current=next;setSubject(owner);}setRequest(next);setType(next.type);setLevel(next.difficulty);setLimit(next.promptLimit);setSelected(next.packet.sources.map(s=>`${s.kind}:${s.id}`));setView('prepare');setReport(null);setRepair(null);setCopied(null);if(!keepText)setRaw(next.originalResponse??'');});}
  async function validate(text=raw){if(!request)return;await run(async()=>{setRaw(text);const result=unwrap(await window.desktop.validateActivity({subjectId:subject,requestId:request.id,text}));setReport(result);setRepair(result.valid?null:unwrap(await window.desktop.activityCorrection({subjectId:subject,requestId:request.id,text})));setCopied(null);});}
  async function copy(mode:'prompt'|'correction'){if(!request)return;await run(async()=>{setCopied(null);if(mode==='prompt')setManual(true);const result=unwrap(await window.desktop.copyActivityPrompt({subjectId:subject,requestId:request.id,mode,text:mode==='correction'?raw:undefined}));if(result.copied)setCopied(mode);});}
  async function importAndStart(){if(!request)return;await run(async()=>{const result=unwrap(await window.desktop.importActivity({subjectId:subject,requestId:request.id,text:raw}));await refresh();await practice(result.activity);});}
  async function practice(item:ActivitySummary,restart=false){setActivity(item);setIndex(0);setRevealed(false);if(item.type==='quiz'){const result=unwrap(await window.desktop.startQuiz({subjectId:subject,activityId:item.id,restart}));setQuiz(result);setIndex(Math.max(0,result.items.findIndex(q=>!result.answers[q.id])));setCards([]);}else{setCards(unwrap(await window.desktop.activityCards({subjectId:subject,activityId:item.id})));setQuiz(null);}setView('practice');}
  async function answer(optionId:'A'|'B'|'C'|'D'){if(!quiz)return;await run(async()=>{setQuiz(unwrap(await window.desktop.answerQuiz({subjectId:subject,sessionId:quiz.id,version:quiz.version,itemId:quiz.items[index].id,optionId})));});}
  async function finish(){if(!quiz)return;await run(async()=>setQuiz(unwrap(await window.desktop.finishQuiz({subjectId:subject,sessionId:quiz.id,version:quiz.version}))));}
  async function rate(rating:'again'|'hard'|'good'|'easy'){const card=cards[index];if(!activity||!card.review||!revealed)return;await run(async()=>{const review=unwrap(await window.desktop.rateActivityCard({subjectId:subject,activityId:activity.id,itemId:card.id,version:card.review!.version,rating,operationId:crypto.randomUUID()}));setCards(current=>current.map(c=>c.id===card.id?{...c,review}:c));setRevealed(false);setIndex(i=>(i+1)%cards.length);});}
  async function reference(sourceId:string,chunkId:string,requestId=request?.id??activity?.requestId){if(!requestId)return;await run(async()=>setContext(unwrap(await window.desktop.activityReference({subjectId:subject,requestId,sourceId,chunkId}))));}
  function provenance(value:Provenance){return <div className="activity-provenance">{value.basis!=='material'&&<><strong>Complemento de conhecimento geral</strong><p>{value.supplement}</p></>}{value.references.map((ref,i)=><button key={`${ref.sourceId}:${ref.chunkId}:${i}`} disabled={busy} onClick={()=>void reference(ref.sourceId,ref.chunkId)}>Conferir trecho {i+1}</button>)}</div>;}
  const title=subjects.find(s=>s.id===subject)?.name??'Matéria';
  return <section className="activities-workspace" data-area-ready="true"><header><small>PRÁTICA / {title}</small><h1>Atividades de estudo</h1><p>Cole em qualquer IA, copie o JSON da resposta e importe aqui.</p><div className="activity-actions"><label>Matéria<select aria-label="Matéria das atividades" disabled={busy} value={subject} onChange={e=>{setSubject(e.target.value);setView('library');}}><option value="" disabled>Escolha uma matéria</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button disabled={busy||!subject} onClick={()=>begin('quiz')}>Criar questionário</button><button disabled={busy||!subject} onClick={()=>begin('flashcards')}>Criar flashcards</button><button disabled={busy} onClick={()=>setView('library')}>Minhas atividades</button></div></header>
    {error&&<p className="settings-error" role="alert">{error}</p>}
    {view==='library'&&<div className="activity-library"><section><h2>Para estudar</h2>{!activities.length&&<p>As atividades importadas aparecem aqui. Você pode retomar tentativas e revisões.</p>}{activities.map(a=><article key={a.id}><div><strong>{a.title}</strong><small>{a.type==='quiz'?'Questionário':'Flashcards'} · 10 itens · {a.difficulty==='easy'?'Fácil':a.difficulty==='medium'?'Médio':'Difícil'} · revisão {a.revision}{a.supplements>0&&` · ${a.supplements} complementos`}</small></div><button disabled={busy} onClick={()=>void run(()=>practice(a))}>Estudar {a.title}</button></article>)}</section><section><h2>Pedidos preparados</h2><p>O prompt e suas fontes ficam salvos aqui para importar a resposta depois.</p>{requests.map(r=><article key={r.id}><div><strong>{r.type==='quiz'?'Questionário':'Flashcards'} · {new Date(r.createdAt).toLocaleString('pt-BR')}</strong><small>{r.id.slice(0,8)} · {r.difficulty}</small></div><button disabled={busy} onClick={()=>void resume(r.id)}>Continuar pedido {r.id.slice(0,8)}</button></article>)}</section></div>}
    {view==='prepare'&&<div className="activity-preparation"><section><h2>1. Selecionar materiais</h2><p>Somente fontes desta matéria. Notas usam o arquivo salvo; salve seus rascunhos antes de preparar.</p><div className="activity-parameters"><label>Tipo<select aria-label="Tipo da atividade" value={type} disabled={busy} onChange={e=>{setType(e.target.value as ActivityType);invalidate();}}><option value="quiz">Questionário · 10 questões</option><option value="flashcards">Flashcards · 10 cartões</option></select></label><label>Dificuldade<select aria-label="Dificuldade da atividade" disabled={busy} value={level} onChange={e=>{setLevel(e.target.value as typeof level);invalidate();}}><option value="easy">Fácil</option><option value="medium">Médio</option><option value="hard">Difícil</option></select></label><label>Limite do prompt (caracteres)<input aria-label="Limite do prompt" type="number" min={2000} max={1000000} disabled={busy} value={limit} onChange={e=>{setLimit(e.target.valueAsNumber);invalidate();}}/></label></div><p className="activity-muted">O limite é local e não garante compatibilidade com toda IA.</p>
      <div className="activity-sources">{sources.map(s=><label key={key(s)}><input type="checkbox" aria-label={`Selecionar ${s.title}`} disabled={busy||!s.available} checked={selected.includes(key(s))} onChange={e=>{setSelected(current=>e.target.checked?[...current,key(s)]:current.filter(k=>k!==key(s)));invalidate();}}/><span><strong>{s.title}</strong><small>{s.kind==='note'?'Markdown':s.kind==='pdf'?'PDF':'Anotações do vídeo'} · {s.detail}</small></span></label>)}</div><button className="primary" disabled={busy||selected.length===0||!Number.isInteger(limit)||limit<2000||limit>1000000} onClick={()=>void prepare()}>{busy?'Preparando…':'Preparar prompt'}</button>
      {request&&<div className="activity-prompt"><h2>2. Copiar prompt</h2><p>{request.prompt.length.toLocaleString('pt-BR')} / {request.promptLimit.toLocaleString('pt-BR')} caracteres · 10 itens · snapshot salvo.</p>{request.prompt.length>request.promptLimit?<><p role="alert">O prompt excede o limite. Desmarque materiais e prepare novamente. Nenhum conteúdo foi cortado.</p><ul>{request.sourceSizes.map((s,i)=><li key={i}>{s.title}: {s.characters.toLocaleString('pt-BR')} caracteres no pacote</li>)}</ul></>:<><button disabled={busy} onClick={()=>void copy('prompt')}>{copied==='prompt'?'Copiado':'Copiar prompt'}</button><details open={manual}><summary>Texto para cópia manual e conferência</summary><textarea readOnly aria-label="Prompt completo" value={request.prompt}/></details><details><summary>Conferir fontes selecionadas ({request.packet.sources.length})</summary>{request.packet.sources.map(s=><div key={s.sourceId}><strong>{s.title}</strong>{s.chunks.map(c=><button key={c.id} disabled={busy} onClick={()=>void reference(s.sourceId,c.id)}>{c.location.kind==='page'?`Página ${c.location.page}`:c.location.kind==='seconds'?`${c.location.seconds}s`:`Linhas ${c.location.start}–${c.location.end}`}</button>)}</div>)}</details></>}</div>}
    </section><section><h2>3. Importar resposta</h2>{!request?<p>Selecione fontes e prepare o pedido primeiro. Para continuar após reiniciar, abra um pedido salvo em Minhas atividades.</p>:<><p>Pedido {request.id.slice(0,8)} · {request.type==='quiz'?'Questionário':'Flashcards'} · {title}</p><label>Colar resposta<textarea aria-label="JSON da resposta" value={raw} onChange={e=>{setRaw(e.target.value);setReport(null);setRepair(null);setCopied(null);}}/></label><input ref={file} type="file" accept=".json,application/json" aria-label="Arquivo JSON da atividade" hidden onChange={event=>{const chosen=event.target.files?.[0];event.target.value='';if(!chosen)return;void run(async()=>{if(chosen.size>IMPORT_BYTES)throw Error('O arquivo excede 2 MiB. Peça um JSON completo mais conciso.');const text=new TextDecoder('utf-8',{fatal:true}).decode(await chosen.arrayBuffer());setRaw(text);const next=unwrap(await window.desktop.validateActivity({subjectId:subject,requestId:request.id,text}));setReport(next);setRepair(next.valid?null:unwrap(await window.desktop.activityCorrection({subjectId:subject,requestId:request.id,text})));setCopied(null);});}}/><div className="activity-actions"><button disabled={busy} onClick={()=>file.current?.click()}>Abrir arquivo JSON</button><button className="primary" disabled={busy||!raw.trim()} onClick={()=>void validate()}>Validar resposta</button></div>
      {report&&!report.valid&&<div className="activity-errors" role="alert"><h3>Não foi possível importar</h3><p>O texto original foi conservado. Cole o pedido de correção na mesma conversa da IA e importe a nova resposta.</p><ol>{report.problems.slice(0,20).map((p,i)=><li key={i}><strong>{p.path}{p.line&&` · linha ${p.line}, coluna ${p.column}`}</strong><p>{p.message}</p><small>Esperado: {p.expected}<br/>Recebido: {JSON.stringify(p.received)}</small><p>{p.suggestion}</p>{p.excerpt&&<pre>{p.excerpt}</pre>}</li>)}</ol>{report.problems.length>20&&<p>Mais {report.problems.length-20} problemas; o relatório de correção inclui o restante quando couber no orçamento.</p>}{report.matchingRequestId&&<button disabled={busy} onClick={()=>void resume(report.matchingRequestId!,true,report.matchingSubjectId??subject)}>Escolher pedido correspondente {report.matchingRequestId.slice(0,8)} · {report.matchingSubjectName}</button>}<button disabled={busy} onClick={()=>void copy('correction')}>{copied==='correction'?'Copiado':'Copiar pedido de correção'}</button>{repair&&<details><summary>Pedido de correção para cópia manual{repair.short?' · relatório curto para a mesma conversa':''}</summary><textarea readOnly aria-label="Pedido de correção" value={repair.text}/></details>}<button disabled={busy||request.prompt.length>request.promptLimit} onClick={()=>void copy('prompt')}>Copiar prompt original novamente</button></div>}
      {report?.valid&&report.preview&&<section className="activity-preview"><h3>Prévia da atividade</h3><strong>{report.preview.title}</strong><p>{report.preview.type==='quiz'?'Questionário':'Flashcards'} · {report.preview.count} itens · {report.preview.subject}</p><p>{report.preview.supplements?`${report.preview.supplements} itens com complemento de conhecimento geral`:'Todos os itens referenciam os materiais.'}</p><small>Origem: IA externa escolhida por você. Você pode conferir os trechos do snapshot antes de estudar.</small><button className="primary" disabled={busy} onClick={()=>void importAndStart()}>Importar e começar</button></section>}</>}
    </section></div>}
    {view==='practice'&&activity&&<section className="activity-practice"><header><h2>{activity.title}</h2><small>{title} · revisão {activity.revision} · origem: IA externa</small><button disabled={busy} onClick={()=>setView('library')}>Voltar às atividades</button></header>
      {quiz&&(!quiz.results?<><nav aria-label="Questões da tentativa">{quiz.items.map((q,i)=><button key={q.id} aria-label={`Ir para questão ${i+1}`} aria-current={i===index?'step':undefined} disabled={busy} onClick={()=>setIndex(i)}>{i+1}{quiz.answers[q.id]?' ·':''}</button>)}</nav><small>Questão {index+1}/10 · {Object.keys(quiz.answers).length} respondidas</small><h3>{quiz.items[index].question}</h3><div className="quiz-options">{quiz.items[index].options.map(o=><button key={o.id} aria-label={`Alternativa ${o.id}`} aria-pressed={quiz.answers[quiz.items[index].id]===o.id} disabled={busy} onClick={()=>void answer(o.id as 'A'|'B'|'C'|'D')}><strong>{o.id}</strong><span>{o.text}</span></button>)}</div><div className="activity-actions"><button disabled={busy||index===0} onClick={()=>setIndex(i=>i-1)}>Anterior</button><button disabled={busy||index===9} onClick={()=>setIndex(i=>i+1)}>Próxima</button><button disabled={busy||Object.keys(quiz.answers).length!==10} onClick={()=>void finish()}>Finalizar questionário</button></div><p className="activity-muted">Suas respostas são salvas. Gabarito e explicações aparecem após finalizar.</p></>:<><h3>Resultado do questionário</h3><div className="quiz-kpis"><span><strong>{quiz.results.correct}/10</strong>Acertos</span><span><strong>{quiz.results.percent}%</strong>Aproveitamento</span><span><strong>{Math.round(quiz.results.durationMs/1000)}s</strong>Tempo da tentativa</span></div>{quiz.results.items.map(result=><article className="quiz-result" key={result.id}><strong>{quiz.items.find(q=>q.id===result.id)?.question}</strong><p>Sua resposta: {result.selected} · correta: {result.correctOptionId} · {result.correct?'Acertou':'Rever'}</p><p>{result.explanation}</p>{provenance(result.provenance)}</article>)}<button disabled={busy} onClick={()=>void run(()=>practice(activity,true))}>Nova tentativa</button></>)}
      {cards.length>0&&<><nav aria-label="Cartões da atividade">{cards.map((card,i)=><button key={card.id} aria-label={`Ir para cartão ${i+1}`} aria-current={index===i?'step':undefined} disabled={busy} onClick={()=>{setIndex(i);setRevealed(false);}}>{i+1}</button>)}</nav><small>Cartão {index+1}/10 · {cards[index].review?.reviews??0} revisões</small><h3>{cards[index].front}</h3>{revealed?<><div className="activity-card-back"><strong>Resposta</strong><p>{cards[index].back}</p><strong>Explicação</strong><p>{cards[index].explanation}</p>{provenance(cards[index].provenance)}</div>{cards[index].review?<div className="activity-actions">{([['again','Ainda não'],['hard','Difícil'],['good','Lembrei'],['easy','Fácil']] as const).map(([rating,label])=><button key={rating} disabled={busy} onClick={()=>void rate(rating)}>{label}</button>)}</div>:<p>Este cartão foi removido da revisão. Seu conteúdo e referências permanecem aqui.</p>}<p className="activity-muted">Autoavaliação: use a revisão existente; esta ação não é um acerto de múltipla escolha.</p></>:<button className="primary" onClick={()=>setRevealed(true)}>Revelar resposta</button>}</>}
    </section>}
    {context&&<MotionDialog title={`Fonte: ${context.title}`} close={()=>setContext(null)}>{()=> <div className="activity-source-context"><p>{context.status==='changed'?'A fonte mudou. Este trecho preserva o snapshot exportado.':context.status==='missing'?'Fonte atual ausente. O snapshot conserva o contexto exportado.':'Fonte atual corresponde ao snapshot.'}</p><small>{context.chunk.location.kind==='page'?`Página ${context.chunk.location.page}`:context.chunk.location.kind==='seconds'?`${context.chunk.location.seconds}s`:`Linhas ${context.chunk.location.start}–${context.chunk.location.end}`}</small><pre>{context.chunk.text}</pre>{context.status!=='missing'&&<button disabled={busy} onClick={()=>void run(async()=>{await openSource(subject,context);setContext(null);})}>Abrir fonte local</button>}</div>}</MotionDialog>}
  </section>;
}
