import { useEffect, useRef, useState } from 'react';
import { challengeTotal, challengeReadyAt, challengePhase, skillPosition, type GameState, type GameAction } from '../shared/game';
import { formatAmount } from '../shared/amount';
export function Arcade({ state, busy, execute, visible = true,inputActive=true }: { visible?: boolean;inputActive?:boolean; state: GameState; busy: boolean; execute(action: GameAction): void }) {
  const [pace, setPace] = useState<'relaxed' | 'normal'>('relaxed'), [now, setNow] = useState(state.now);
  const clock = useRef({ server: state.now, received: performance.now() });
  useEffect(() => { clock.current = { server: state.now, received: performance.now() }; setNow(state.now); }, [state]);
  const c = state.challenge, active = c?.status === 'active', paused = c?.status === 'paused', inProgress = active || paused;
  useEffect(() => { if (!visible || !active) return; let frame = 0; const tick = () => { if (!document.hidden) setNow(clock.current.server + performance.now() - clock.current.received); frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [visible, active]);
  const live = useRef({ c, busy, execute, visible:visible&&inputActive, now }); live.current = { c, busy, execute, visible:visible&&inputActive, now };
  useEffect(() => { const key = (e: KeyboardEvent) => { const { c, busy, execute, visible, now } = live.current; if (!visible || document.hidden || !c || c.status !== 'active' || now < challengeReadyAt(c) || busy || e.repeat || (e.target instanceof HTMLElement && (e.target.closest('input,select,textarea,[contenteditable]') || e.code==='Space' && e.target.closest('button')))) return;
    const k = e.key.toUpperCase(); if (c.kind === 'qte' && ['A', 'S', 'D', 'W'].includes(k)) { e.preventDefault(); execute({ kind: 'qte-input', challengeId: c.id, key: k as 'A' }); }
    if (c.kind === 'skillcheck' && e.code === 'Space') { e.preventDefault(); execute({ kind: 'skill-input', challengeId: c.id }); }
  }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, []);
  const target = c?.targets[c.stage] ?? 50, readyAt = c ? challengeReadyAt(c) : 0, preparing = active && now < readyAt;
  const pos = c ? skillPosition(now, readyAt, c.stepMs) : 0, total = c ? challengeTotal(c) : 36;
  return <section className={`arcade-stage ${inProgress?'playing':''}`}><span className="game-kicker">OFICINA / TRÊS FASES</span><h1>Acerte o momento.</h1><p>36 etapas consecutivas · dificuldade gradual · preparação somente no início.</p>
    <div className="arcade-choices"><button disabled={busy || inProgress} onClick={() => execute({ kind: 'start-challenge', game: 'qte', pace })}><span>01 / QTE</span><h2>Sincronizar o motor</h2><p>Responda ao sinal. A janela fica menor a cada fase; até 6 erros.</p><b>Até {pace === 'normal' ? 300 : 240} de Produção · 60 XP →</b></button><button disabled={busy || inProgress} onClick={() => execute({ kind: 'start-challenge', game: 'skillcheck', pace })}><span>02 / SKILLCHECK</span><h2>Calibrar a válvula</h2><p>Pare o marcador na faixa. Mais velocidade e precisão por fase; até 10 erros.</p><b>Até {pace === 'normal' ? 375 : 300} de Produção · 60 XP →</b></button></div>
    <label className="arcade-pace">Seu ritmo <select aria-label="Ritmo dos desafios" disabled={inProgress} value={pace} onChange={e => setPace(e.target.value as typeof pace)}><option value="relaxed">Tranquilo · preparação maior e faixa ampla</option><option value="normal">Normal · precisão extra e bônus de 25%</option></select></label>
    {c && <div className="challenge-panel" data-testid="challenge-panel"><div className="challenge-progress"><span>{c.kind === 'qte' ? 'SINCRONIZAÇÃO' : 'CALIBRAÇÃO'} / FASE {challengePhase(c)}</span><span>{Math.min(total, c.stage + 1)} / {total}</span></div><div className="workshop-phases">{['Preparação','Aceleração','Precisão'].map((name,i)=><span key={name} className={challengePhase(c)===i+1?'selected':''}>{String(i+1).padStart(2,'0')} / {name}</span>)}</div><p className="challenge-score">{c.hits} acertos · {c.misses ?? c.stage-c.hits} erros · ritmo {c.pace === 'relaxed' ? 'tranquilo' : 'normal'}</p>
      {paused ? <div className="workshop-preparing"><h2>Partida pausada.</h2><p>Sua etapa e seu tempo foram preservados.</p><button className="primary" disabled={busy} onClick={()=>execute({kind:'resume-challenge',challengeId:c.id})}>Retomar partida</button></div> : preparing ? <div className="workshop-preparing" data-testid="workshop-preparing"><span>PREPARE-SE</span><strong>{Math.max(1,Math.ceil((readyAt-now)/1000))}</strong><p>Uma contagem. Depois, um sinal atrás do outro.</p></div> : active ? c.kind === 'qte' ? <><div className="qte-key" data-testid="qte-key">{c.sequence[c.stage]}</div><div className="qte-time"><div style={{ width: `${Math.max(0, 100 * (1 - (now - readyAt) / c.stepMs))}%` }}/></div><p>Teclado A / S / D / W ou clique na tecla abaixo.</p><div className="qte-buttons">{(['A', 'S', 'D', 'W'] as const).map(key => <button key={key} aria-label={`Tecla ${key}`} disabled={busy} onClick={() => execute({ kind: 'qte-input', challengeId: c.id, key })}>{key}</button>)}</div></> : <><h2>Calibre agora.</h2><div className="skill-track" data-testid="skill-track" data-position={pos} data-target={target}><div className="skill-zone" style={{ left: `${target - c.zone / 2}%`, width: `${c.zone}%` }}/><div className="skill-marker" style={{ left: `${pos}%` }}/></div><p>Quando o marcador entrar na faixa, pressione Espaço ou:</p><button className="primary" disabled={busy} onClick={() => execute({ kind: 'skill-input', challengeId: c.id })}>Calibrar válvula</button></> : <div role="status"><h2>{c.status === 'completed' ? 'Desafio concluído.' : 'Vamos tentar de novo?'}</h2><p>{c.status === 'completed' ? `+${formatAmount(c.coins)} de Produção · +${c.xp} XP · ${c.hits}/${total} acertos` : 'Tentativa encerrada. Sua Produção foi preservada; você pode começar de novo.'}</p></div>}
      {inProgress && <div className="challenge-actions">{active && <button disabled={busy} onClick={()=>execute({kind:'pause-challenge',challengeId:c.id})}>Pausar partida</button>}<button className="challenge-cancel" disabled={busy} onClick={() => execute({ kind: 'cancel-challenge', challengeId: c.id })}>Encerrar tentativa · sem custo</button></div>}
    </div>}
  </section>;
}
