import { useEffect, useState, type FormEvent } from 'react';
import type { StudyTask } from '../shared/contracts';
export function ChecklistPanel({ subjectId, nextStepId, onNext, onError }: { subjectId: string; nextStepId: string | null; onNext(id: string): void; onError(message: string): void }) {
  const [tasks, setTasks] = useState<StudyTask[]>([]); const [text, setText] = useState('');
  const [stepText, setStepText] = useState<Record<string, string>>({}); const [editing, setEditing] = useState<string | null>(null); const [editText, setEditText] = useState('');
  useEffect(() => { let stopped = false; void window.desktop.listTasks({ subjectId }).then(r => { if (!stopped) { if (r.ok) setTasks(r.value); else onError(r.message); } }); return () => { stopped = true; }; }, [subjectId]);
  async function create(event: FormEvent) { event.preventDefault(); const r = await window.desktop.createTask({ subjectId, text }); if (r.ok) { setTasks(t => [...t, r.value]); setText(''); } else onError(r.message); }
  async function add(event: FormEvent, taskId: string) { event.preventDefault(); const r = await window.desktop.createStep({ subjectId, taskId, text: stepText[taskId] ?? '' }); if (r.ok) { setTasks(t => t.map(v => v.id === taskId ? { ...v, steps: [...v.steps, r.value] } : v)); setStepText(t => ({ ...t, [taskId]: '' })); } else onError(r.message); }
  async function update(id: string, patch: { text?: string; done?: boolean }) { const r = await window.desktop.updateStep({ subjectId, id, ...patch }); if (r.ok) { setTasks(t => t.map(v => ({ ...v, steps: v.steps.map(s => s.id === id ? r.value : s) }))); setEditing(null); } else onError(r.message); }
  const all = tasks.flatMap(t => t.steps), completed = all.filter(s => s.done).length, next = all.find(s => s.id === nextStepId);
  return <div className="checklist-body"><div className="checklist-summary"><span>{completed} / {all.length} concluídas</span><span>{all.length ? Math.round(completed / all.length * 100) : 0}%</span></div><div className="progress-track" role="progressbar" aria-label="Etapas concluídas" aria-valuemin={0} aria-valuemax={100} aria-valuenow={all.length ? Math.round(completed / all.length * 100) : 0}><div style={{ width: `${all.length ? completed / all.length * 100 : 0}%` }}/></div>{next && <p className="next-action"><span className="next-caption">PRÓXIMA AÇÃO</span>Retomar: {next.text}</p>}
    {tasks.map(task => <div className="study-task" key={task.id}><div className="task-heading"><h3>{task.text}</h3><small>{task.steps.filter(s => s.done).length}/{task.steps.length}</small></div>{task.steps.map(step => <div className={`step-row ${step.id === nextStepId ? 'next' : ''}`} key={step.id}><input type="checkbox" checked={step.done} aria-label={`Concluir ${step.text}`} onChange={e => update(step.id, { done: e.target.checked })}/>{editing === step.id ? <form className="step-edit" onSubmit={e => { e.preventDefault(); void update(step.id, { text: editText }); }}><input aria-label="Editar texto da etapa" autoFocus required maxLength={300} value={editText} onChange={e => setEditText(e.target.value)}/><button aria-label="Salvar etapa">✓</button><button type="button" aria-label="Cancelar edição de etapa" onClick={() => setEditing(null)}>×</button></form> : <><span className={step.done ? 'done' : ''}>{step.text}</span><button aria-label={`Editar ${step.text}`} onClick={() => { setEditing(step.id); setEditText(step.text); }}>✎</button><button aria-label={`Retomar ${step.text}`} onClick={() => onNext(step.id)}>→</button></>}</div>)}<form className="step-form" onSubmit={e => add(e, task.id)}><input required maxLength={300} aria-label={`Nova etapa em ${task.text}`} placeholder="Adicionar etapa…" value={stepText[task.id] ?? ''} onChange={e => setStepText(t => ({ ...t, [task.id]: e.target.value }))}/><button aria-label={`Adicionar etapa em ${task.text}`}>+</button></form></div>)}
    <form className="task-form" onSubmit={create}><input required maxLength={200} aria-label="Nova tarefa" placeholder="Nova tarefa de estudo…" value={text} onChange={e => setText(e.target.value)}/><button aria-label="Criar tarefa">+</button></form>
  </div>;
}
