import { useEffect, useState } from 'react';
import { MotionDialog } from './MotionDialog';
import type { SearchHit } from '../shared/study';
import { Icon } from './Icon';
export type Command = 'home'|'review'|'graph'|'study'|'explorer'|'city'|'settings'|'new-note'|'new-subject';
const commands:[Command,string][]=[['home','Abrir início'],['review','Revisar flashcards'],['graph','Explorar conexões'],['study','Voltar aos estudos'],['explorer','Ver projetos'],['city','Entrar na cidade'],['settings','Abrir configurações'],['new-note','Criar nota'],['new-subject','Criar matéria']];
export function CommandPalette({ close,onHit,onCommand }:{close():void;onHit(hit:SearchHit):Promise<void>;onCommand(command:Command):Promise<void>}) {
  const [query,setQuery]=useState(''),[hits,setHits]=useState<SearchHit[]>([]),[error,setError]=useState(''),[index,setIndex]=useState(0),[busy,setBusy]=useState(false);
  const actions=commands.filter(([,label])=>label.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  useEffect(()=>{let stopped=false;setIndex(0);const timer=setTimeout(()=>{void window.desktop.globalSearch({query}).then(r=>{if(stopped)return;if(r.ok){setHits(r.value);setError('');}else setError(r.message);}).catch(()=>{if(!stopped)setError('Não foi possível buscar.');});},120);return()=>{stopped=true;clearTimeout(timer);};},[query]);
  const rows=[...actions.map(([command,title])=>({command,title})),...hits.map(hit=>({hit,title:hit.title}))];
  async function choose(i:number,requestClose:()=>void){if(busy||!rows[i])return;setBusy(true);try{const row=rows[i];if('command'in row)await onCommand(row.command);else await onHit(row.hit);requestClose();}catch{setError('Não foi possível abrir este resultado.');}finally{setBusy(false);}}
  return <MotionDialog title="Encontrar e continuar" close={close}>{requestClose=><div className="command-palette"><input autoFocus aria-label="Busca global" placeholder="Procure uma palavra, nota, matéria ou ação…" maxLength={160} value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setIndex(v=>(v+(e.key==='ArrowDown'?1:-1)+Math.max(1,rows.length))%Math.max(1,rows.length));}if(e.key==='Enter'){e.preventDefault();void choose(index,requestClose);}}}/><div className="command-results" role="listbox" aria-label="Resultados da busca">{rows.map((row,i)=><button role="option" aria-selected={i===index} className={i===index?'selected':''} disabled={busy} key={'command'in row?row.command:row.hit.kind+row.hit.id} onPointerEnter={()=>setIndex(i)} onClick={()=>void choose(i,requestClose)}><Icon kind={'hit'in row&&row.hit.kind==='video'?'video':'arrow'}/><span><strong>{row.title}</strong><small>{'hit'in row?row.hit.detail:'Ação do app'}</small></span></button>)}{!rows.length&&<p>Nenhum resultado. Tente uma palavra do conteúdo, título ou matéria.</p>}</div>{error&&<p role="alert">{error}</p>}<p className="study-muted">↑ ↓ selecionar · Enter abrir · Esc fechar · busca no texto, títulos e matérias</p></div>}</MotionDialog>;
}
