import {useEffect,useRef,useState} from 'react';
import type {TodayState} from '../shared/study';
import {studyNextStep} from '../shared/study-navigation';
import {Icon} from './Icon';
import {useSurfaceMotion} from './motion';
import {Avatar,usePreferences} from './preferences';
import {StudySculpture} from './StudySculpture';
import type {WorkspaceArea} from '../shared/workspace';
export function DayOverview({activeArea,openSubject,openTask,review,search,newSubject,newNote,addContent,home=false,explore}:{activeArea:boolean;openSubject(id:string):Promise<void>;openTask(id:string):Promise<void>;review():void;search():void;newSubject():void;newNote():void;addContent():void;home?:boolean;explore?(area:WorkspaceArea):void}){
 const [data,setData]=useState<TodayState|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),host=useRef<HTMLDivElement>(null);useSurfaceMotion(host,String(revision),activeArea);
 useEffect(()=>{if(!activeArea)return;let stopped=false;async function load(){const r=await window.desktop.today();if(stopped)return;if(r.ok){setData(r.value);setError('');}else setError(r.message);}void load().catch(()=>{if(!stopped)setError('Não foi possível consultar o dia.');});const timer=setInterval(()=>void load().catch(()=>{}),15000);return()=>{stopped=true;clearInterval(timer);};},[activeArea,revision]);
 const {value:profile}=usePreferences(),next=data?studyNextStep(data):null;
 function continueNext(){if(!next)return;if(next.kind==='create')newSubject();else if(next.kind==='review')review();else void(next.task?openTask(next.subjectId):openSubject(next.subjectId));}
 return <div className="study-workspace today-workspace experience-today" data-area-ready="true" ref={host}>
 <header className="dashboard-header" data-home-enter><div className="dashboard-identity"><Avatar profile={profile}/><div><span className="eyebrow">{home?'NODUS / INÍCIO':'NODUS / SEU DIA'}</span><h1>{home?'Seu ponto de partida.':'Um passo de cada vez.'}</h1><p>{profile.name?`${profile.name}, seu espaço está pronto.`:'Seu espaço está pronto.'}</p></div></div><div className="dashboard-date"><time>{new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</time><button onClick={()=>setRevision(n=>n+1)}><Icon kind="refresh"/> Atualizar Hoje</button></div></header>
 {error&&<p role="alert">{error}</p>}
 <section data-home-enter className="today-next" aria-label="Próximo passo sugerido"><div className="today-next-copy"><span className="eyebrow">SEU PRÓXIMO PASSO</span><h2>{next?.title??'Preparando seu dia…'}</h2><p>{next?.detail??'Consultando suas matérias, revisões e checklist.'}</p><button className="primary" disabled={!next} onClick={continueNext}>{next?.action??'Carregando'} <Icon kind="arrow"/></button><span className="today-next-hint">Uma sugestão. Você escolhe o ritmo.</span></div><StudySculpture active={activeArea}/></section>
 <nav data-home-enter className="today-capture" aria-label="Ações rápidas de conteúdo"><span>Uma ideia nova?</span><button onClick={newNote}><Icon kind="note"/> Escrever agora</button><button onClick={addContent}><Icon kind="plus"/> Adicionar conteúdo</button><button onClick={search}><Icon kind="search"/> Encontrar uma nota <kbd>Ctrl K</kbd></button></nav>
 {home&&explore&&<nav className="home-destinations" data-home-enter aria-label="Explore seu espaço">{([['study','book','Caderno','Escreva, organize e continue suas notas.','Abrir caderno pela Home'],['pdf','note','Materiais','Leia PDFs e capture ideias para estudar.','Abrir materiais pela Home'],['review','memory','Revisão','Relembre e pratique no seu ritmo.','Abrir revisão pela Home'],['city','city','Cidade','Construa e acompanhe sua vila.','Abrir cidade pela Home']] as const).map(([area,icon,title,detail,label],i)=><button key={area} onClick={()=>explore(area)} aria-label={label}><span className="home-destination-icon"><Icon kind={icon}/></span><span className="home-destination-index">0{i+1}</span><strong>{title}</strong><small>{detail}</small><Icon kind="arrow"/></button>)}</nav>}
 <div data-home-enter className="today-stats"><div><small>01 / FOCO HOJE</small><strong>{data?Math.floor(data.focusMs/60000):'—'}<span> min</span></strong><p>Tempo registrado, sem pausas.</p></div><div><small>02 / REVISÕES</small><strong>{data?.due??'—'}<span> cartões</span></strong><button onClick={review}>Abrir revisões <Icon kind="arrow"/></button></div><div><small>03 / PRÓXIMAS AÇÕES</small><strong>{data?.tasks.length??'—'}<span> tarefas</span></strong><p>No checklist das suas matérias.</p></div><div><small>04 / ACERVO</small><strong>{data?.subjects.length??'—'}<span> matérias</span></strong><button onClick={newSubject}>+ Nova matéria</button></div></div>
 <section data-home-enter><div className="study-section-heading"><h2>Próximos passos</h2><span>{data?.tasks.length??0} em aberto</span></div>{data&&!data.tasks.length&&<div className="experience-empty"><Icon kind="check"/><p>Seu checklist está livre. Retome uma matéria para planejar a próxima ação.</p></div>}<div className="today-tasks">{data?.tasks.map((task,index)=><button key={task.id} onClick={()=>void openTask(task.subjectId)}><span className="row-index">{String(index+1).padStart(2,'0')}</span><span><strong>{task.text}</strong><small>{task.subject} · {task.total?`${task.done}/${task.total} etapas`:'Próxima ação'}</small></span><Icon kind="arrow"/></button>)}</div></section>
 <section><div className="study-section-heading"><h2>Suas matérias</h2><button onClick={newSubject}>+ Nova matéria</button></div><div className="today-subjects">{data?.subjects.map((s,index)=><button key={s.id} data-color={s.color} onClick={()=>void openSubject(s.id)}><span className="subject-card-meta"><span>{String(index+1).padStart(2,'0')} / MATÉRIA</span><Icon kind="book"/></span><strong>{s.name}</strong><span className="subject-card-action">Abrir mesa <Icon kind="arrow"/></span></button>)}</div>{data&&!data.subjects.length&&<div className="experience-empty"><Icon kind="book"/><p>Uma matéria reúne suas notas, PDFs e aulas.</p><button onClick={newSubject}>Criar primeira matéria →</button></div>}</section>
 <footer data-home-enter className="dashboard-foot"><span>SEU CONTEÚDO / NO SEU COMPUTADOR</span><button onClick={search}>Busca e ações <kbd>Ctrl K</kbd></button></footer>
 </div>;
}
