import { useEffect, useState } from 'react';
import { PRODUCERS, UPGRADES, ACHIEVEMENTS, PERMANENT, SIGNALS, BALANCE } from '../shared/economy';
import { amount, add, dec, enough, formatAmount as n } from '../shared/amount';
import type { GameState, GameAction } from '../shared/game';
import { MotionDialog } from './MotionDialog';
type Tab='production'|'upgrades'|'achievements'|'signals'|'legacy';
export function EconomyWorkspace({state,busy,execute,target}:{state:GameState;busy:boolean;execute(a:GameAction):void;target?:GameState['farm']['reinvestment']}) {
  const [tab,setTab]=useState<Tab>('production'),[quantity,setQuantity]=useState<1|10|100|'max'>(1),[confirm,setConfirm]=useState(false),[understood,setUnderstood]=useState(false),[showOwned,setShowOwned]=useState(false),[achievementFilter,setAchievementFilter]=useState('next');
  const e=state.economy,b=e.breakdown;
  const targetAvailable=target&&(target.kind==='installation'||!e.upgrades.includes(target.id));
  const targetCost=target?.kind==='installation'?e.producersView.find(v=>v.id===target.id)?.cost:target?.cost;
  useEffect(()=>{if(target)setTab(target.kind==='upgrade'?'upgrades':'production');},[target?.id]);
  const families=PRODUCERS.filter(p=>e.producersView.find(v=>v.id===p.id)!.unlocked);
  const nextFamily=PRODUCERS.find(p=>!e.producersView.find(v=>v.id===p.id)!.unlocked);
  const visibleFamilies=[...families,...(nextFamily?[nextFamily]:[])];
  const technologies=UPGRADES.filter(u=>{const v=e.upgradesView.find(v=>v.id===u.id)!;return showOwned?v.owned:!v.owned&&(v.unlocked||u.producer&&e.producers[u.producer]>0&&(!u.prior||e.upgrades.includes(u.prior)));});
  const nearbyUpgrade=UPGRADES.find(u=>!e.upgrades.includes(u.id)&&e.upgradesView.find(v=>v.id===u.id)!.unlocked);
  const normal=ACHIEVEMENTS.filter(a=>!a.secret),earned=normal.filter(a=>e.achievements.includes(a.id));
  const achievementRows=achievementFilter==='secret'?ACHIEVEMENTS.filter(a=>a.secret&&e.achievements.includes(a.id)):achievementFilter==='earned'?earned:normal.filter(a=>!e.achievements.includes(a.id)).sort((a,b)=>{
    const ratio=(id:string,target:number|string)=>Math.min(1,dec(e.achievementsView.find(v=>v.id===id)!.progress).div(target).toNumber());return ratio(b.id,b.target)-ratio(a.id,a.target);
  }).slice(0,12);
  const tabs: [Tab,string][]=[['production','Instalações'],['upgrades','Melhorias'],...(e.achievements.length?[['achievements','Descobertas'] as [Tab,string]]:[]),...(families.length||e.signals.length?[['signals',`Sinais${e.signals.length?` · ${e.signals.length}`:''}`] as [Tab,string]]:[]),...(dec(e.lifetime).gte(1000000)||e.cycles?[['legacy','Legado'] as [Tab,string]]:[])];
  return <section className="economy-workspace deep-economy">
    {targetAvailable&&<p className="economy-target" role="status">Próximo objetivo: {target.name} · {n(targetCost??target.cost)} de Produção</p>}
    <header className="economy-heading"><div><span className="game-kicker">OBSERVATÓRIO / CICLO {e.cycles+1}</span><h1>Uma hipótese que cresce.</h1><p>Estude, construa e descubra como a rede se conecta.</p></div><span className="economy-version">REGRAS {BALANCE.version} / {families.length} DE {PRODUCERS.length} FAMÍLIAS</span></header>
    <div className="economy-metrics"><div><small>PRODUÇÃO / SEGUNDO</small><strong data-testid="production-rate">{n(amount(dec(e.rate).div(60)))}</strong><span>{n(e.rate)} / min</span></div><div><small>PRODUZIDO NA JORNADA</small><strong>{n(e.lifetime)}</strong><span>{n(e.cycleEarned)} neste ciclo</span></div><div><small>ÍNDICE DE DESCOBERTA</small><strong>{e.index}</strong><span>{earned.length} conquistas elegíveis</span></div><div><small>ESTUDO CONECTADO</small><strong>{e.focusMinutes}<span> min</span></strong><span>{e.reviews} revisões · {e.study.streak} dias de consistência</span></div></div>
    {e.returnReport&&<div className="economy-return" role="status"><div><small>RETORNO AO OBSERVATÓRIO</small><p>{Math.floor(e.returnReport.elapsedMs/3600000)}h {Math.floor(e.returnReport.elapsedMs/60000)%60}min de ausência · <strong>+{n(e.returnReport.credited)}</strong>{e.returnReport.capped?' · limite offline aplicado':''} · {e.returnReport.signals} sinais guardados · {e.returnReport.milestones} descobertas</p></div><button aria-label="Dispensar resumo de retorno" disabled={busy} onClick={()=>execute({kind:'dismiss-return'})}>×</button></div>}
    <div className="economy-next"><span>PRÓXIMA DESCOBERTA</span><p>{nearbyUpgrade?<><strong>{nearbyUpgrade.name}</strong> · {n(nearbyUpgrade.cost)} de Produção</>:nextFamily?<><strong>{nextFamily.name}</strong> · após {n(nextFamily.unlock)} produzidos</>:'A próxima unidade fortalece sua rede.'}</p><button onClick={()=>setTab(nearbyUpgrade?'upgrades':'production')}>Explorar →</button></div>
    <nav className="economy-tabs" aria-label="Economia da cidade">{tabs.map(([id,name])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{name}</button>)}</nav>
    {tab==='production'&&<>
      <div className="economy-section-label"><span>INSTALAÇÕES / UMA REDE, MUITAS ESCALAS</span><label>Comprar <select aria-label="Quantidade de produtores" value={quantity} onChange={event=>setQuantity(event.target.value==='max'?'max':Number(event.target.value) as 1|10|100)}><option value={1}>×1</option><option value={10}>×10</option><option value={100}>×100</option><option value="max">MAX</option></select></label></div>
      <div className="installation-list">{visibleFamilies.map(p=>{const v=e.producersView.find(v=>v.id===p.id)!,q=quantity==='max'?v.max:quantity,cost=quantity==='max'?(v.max?v.costMax:v.cost):quantity===100?v.cost100:quantity===10?v.cost10:v.cost;return <article key={p.id} className={`installation-row ${!v.unlocked?'locked':''}`}>
        <div className={`installation-emblem visual-${p.visual}`} aria-hidden="true"><span>{String(p.order+1).padStart(2,'0')}</span><i/></div><div className="installation-copy"><small>{p.location.toUpperCase()}</small><h2>{p.name}</h2><p>{p.description}</p><details><summary>Produção e conexões</summary><dl className="installation-facts"><dt>Por unidade / min</dt><dd>{n(v.individual)}</dd><dt>Participação na rede</dt><dd>{v.share.toFixed(1)}%</dd><dt>Estágio visual</dt><dd>{v.level} / 6</dd><dt>Próximo marco</dt><dd>{BALANCE.tierMilestones.find(t=>t>v.count)??'500 alcançado'}</dd><dt>Melhorias ativas</dt><dd>{v.activeUpgrades.length}</dd><dt>Sinergias</dt><dd>{v.partners.map(id=>PRODUCERS.find(p=>p.id===id)?.name).join(', ')||'Ainda não conectada'}</dd></dl></details></div><div className="installation-output"><strong>{v.count}<small> unidades</small></strong><span>{n(v.rate)} / min</span><small>{v.share.toFixed(1)}% da rede</small></div><div className="installation-buy"><button className="primary" aria-label={`Comprar ${quantity} ${p.name}`} disabled={busy||!v.unlocked||!q||v.count+q>BALANCE.maxUnits||!enough(state.coins,cost)} onClick={()=>execute({kind:'producer-buy',producer:p.id,quantity})}>{v.unlocked?<>{n(cost)}<small>{q?`Comprar ×${q}`:v.count>=BALANCE.maxUnits?'Limite de unidades':'Saldo insuficiente'}</small></>:<>Em {n(p.unlock)}<small>produzidos na jornada</small></>}</button></div>
      </article>;})}</div>
      <details className="economy-breakdown"><summary>Por que produzo {n(e.rate)} por minuto?</summary><div className="breakdown-grid"><div><small>BASE DA REDE</small><strong>{n(b.base)} / min</strong></div>{b.layers.map(layer=><div key={layer.name}><small>{layer.name.toUpperCase()}</small><strong title={String(layer.factor)}>×{dec(layer.factor).toSignificantDigits(5).toString().replace('.',',')}</strong></div>)}</div><p>Base × especializações × sinergias × descoberta × build × rede global × sinais × legado. A participação de cada família considera seus próprios parceiros.</p></details>
      <details className="economy-breakdown"><summary>Como meu estudo e minha build participam?</summary><p>Agora, um minuto efetivo de Foco rende {n(e.activityQuotes.focusMinute)} e uma revisão devida rende {n(e.activityQuotes.review)} de Produção. Pausas não contam; repetir uma revisão no mesmo dia não multiplica o ganho.</p><p>Foco e Revisão ampliam suas atividades. Planejamento reduz custos; Prática amplia minigames e expedições. Foco fortalece a produção passiva; os bônus de atividades chegam a 30% por especialização. Consistência oferece até 30% de bônus e nunca retira Produção conquistada. XP e critérios de aprendizagem seguem suas regras próprias.</p></details>
      <p className="economy-footnote">Custos crescem 15% por unidade; 1/10/100/MAX seguem a mesma curva. Produção offline até {e.offlineDays} dias. Os marcos mudam o cenário, sem desenhar milhares de objetos.</p>
    </>}
    {tab==='upgrades'&&<><div className="economy-section-label"><span>{e.upgrades.length} MELHORIAS NO CICLO / {UPGRADES.length} NO CATÁLOGO</span><label><input type="checkbox" checked={showOwned} onChange={event=>setShowOwned(event.target.checked)}/> Mostrar adquiridas</label></div><p className="economy-footnote">Novas possibilidades aparecem conforme suas instalações e descobertas avançam. Sinergias beneficiam as duas pontas da rede.</p><div className="technology-grid">{technologies.map(u=>{const v=e.upgradesView.find(v=>v.id===u.id)!;return<article key={u.id} className={v.owned?'earned':!v.unlocked?'locked':''}><span className="technology-status">{u.category.toUpperCase()} / {v.owned?'ADQUIRIDA':v.unlocked?'DISPONÍVEL':'PRÓXIMO MARCO'}</span><h2>{u.name}</h2><p>{u.description}</p><button aria-label={`Adquirir ${u.name}`} disabled={busy||v.owned||!v.unlocked||!enough(state.coins,u.cost)} onClick={()=>execute({kind:'economy-upgrade',id:u.id})}>{v.owned?'✓ Incorporada':`${n(u.cost)} · Adquirir`}</button></article>;})}</div>{!technologies.length&&<p className="economy-empty">A próxima instalação abre novas hipóteses. Explore a rede.</p>}</>}
    {tab==='achievements'&&<><div className="economy-section-label"><span>{earned.length} / {normal.length} CONQUISTAS NORMAIS · ÍNDICE {e.index}</span><select aria-label="Filtro de conquistas" value={achievementFilter} onChange={event=>setAchievementFilter(event.target.value)}><option value="next">Próximas descobertas</option><option value="earned">Conquistadas</option><option value="secret">Notas secretas descobertas</option></select></div><p className="economy-footnote">Cada conquista normal aumenta o índice. Melhorias de descoberta amplificam sua influência. Notas secretas revelam suas condições somente após serem encontradas.</p><div className="achievement-grid">{achievementRows.map(a=>{const v=e.achievementsView.find(v=>v.id===a.id)!,ratio=Math.min(1,dec(v.progress).div(a.target).toNumber());return<article key={a.id} className={v.unlocked?'earned':''}><span>{v.unlocked?'✓ CONQUISTADA':'EM PROGRESSO'}</span><h2>{a.name}</h2><p>{a.description}</p><progress aria-label={`Progresso ${a.name}`} max={1} value={ratio}/><small>{n(v.progress)} / {n(a.target)}</small></article>;})}</div>{!achievementRows.length&&<p className="economy-empty">O arquivo ainda guarda algumas notas para você descobrir.</p>}</>}
    {tab==='signals'&&<><div className="economy-section-label"><span>{e.signals.length} SINAIS GUARDADOS / {e.activeEvents.length} ATIVOS</span><span>SEM EXPIRAÇÃO ENQUANTO GUARDADOS</span></div><p className="economy-footnote">O céu pode esperar. Durante o Foco, os sinais ficam guardados; depois, escolha até dois tipos diferentes para combinar. A rede guarda até {BALANCE.maxStoredSignals} oportunidades.</p><div className="signal-active">{e.activeEvents.map(event=><span key={event.id}>{SIGNALS.find(s=>s.id===event.type)?.name} · {Math.max(0,Math.ceil(((event.endsAt??0)-state.now)/1000))}s</span>)}</div><div className="technology-grid">{e.signals.map(event=>{const signal=SIGNALS.find(s=>s.id===event.type)!;return<article key={event.id}><span className="technology-status">{signal.rarity.toUpperCase()} / GUARDADO</span><h2>{signal.name}</h2><p>{signal.description}{event.producer?` Família: ${PRODUCERS.find(p=>p.id===event.producer)?.name}.`:''}</p><button aria-label={`Ativar ${signal.name}`} disabled={busy||e.focusActive||Boolean(signal.durationMs&&e.activeEvents.length>=2)||e.activeEvents.some(v=>v.type===event.type)} onClick={()=>execute({kind:'activate-signal',id:event.id})}>{e.focusActive?'Guardado até terminar o Foco':'Ativar quando quiser →'}</button></article>;})}</div>{!e.signals.length&&<p className="economy-empty">Instalações em atividade encontram sinais com o tempo, inclusive entre visitas.</p>}</>}
    {tab==='legacy'&&<><div className="prestige-summary"><div><span className="game-kicker">RECALIBRAÇÃO / SEM PRESSA</span><h2>O próximo horizonte.</h2><p>Troque a economia deste ciclo por insígnias e melhorias permanentes. Continuar produzindo aumenta o retorno.</p><strong>+{n(e.prestigeGain)} <small>insígnias neste reinício</small></strong><p>Próxima insígnia em {n(e.nextPrestigeAt)} produzidos na jornada.</p><button className="primary" disabled={busy||!enough(e.prestigeGain,1)} onClick={()=>{setUnderstood(false);setConfirm(true);}}>Revisar novo ciclo</button></div><dl><dt>Reinicia</dt><dd>Saldo de Produção, instalações, melhorias do ciclo, sinais ativos e nível do motor. Encerra a Oficina ativa.</dd><dt>Permanece</dt><dd>Estudo, XP, inventário, projetos e estoques dos postos, cultivos, mercado, skins, memória, conquistas, sinais guardados, desbloqueios e melhorias permanentes.</dd></dl></div><div className="economy-section-label"><span>LEGADO / {PERMANENT.length} MELHORIAS PERMANENTES</span><span>{n(e.tokens)} insígnias</span></div><div className="technology-grid">{PERMANENT.filter(u=>e.permanent.includes(u.id)||!u.conditions.some(c=>'owned' in c&&!e.permanent.includes(c.owned))).map(u=>{const owned=e.permanent.includes(u.id),ready=u.conditions.every(c=>'owned' in c?e.permanent.includes(c.owned):c.metric==='cycles'?e.cycles>=Number(c.target):true);return<article key={u.id} className={owned?'earned':''}><span className="technology-status">TODOS OS CICLOS</span><h2>{u.name}</h2><p>{u.description}</p><button aria-label={`Adquirir ${u.name}`} disabled={busy||owned||!ready||!enough(e.tokens,u.cost)} onClick={()=>execute({kind:'permanent-upgrade',id:u.id})}>{owned?'✓ Permanente':`${n(u.cost)} insígnias · Adquirir`}</button></article>;})}</div></>}
    {confirm&&<MotionDialog title="Iniciar novo ciclo?" close={()=>setConfirm(false)}>{close=><div className="prestige-confirm"><p>Você receberá <strong>{n(e.prestigeGain)} insígnias</strong>. Legado total: {n(add(e.prestige,e.prestigeGain))}.</p><p>Reinicia <strong>{n(state.coins)} de Produção</strong>, instalações, melhorias do ciclo, sinais ativos e motor. A Oficina ativa será encerrada.</p><p>Seu estudo, XP, fontes, projetos, inventário, cultivos, mercado, skins, memória, conquistas, sinais guardados e melhorias permanentes serão conservados.</p><label><input type="checkbox" checked={understood} onChange={event=>setUnderstood(event.target.checked)}/> Entendi quais partes da economia serão reiniciadas.</label><div className="dialog-buttons"><button disabled={busy} onClick={close}>Continuar neste ciclo</button><button className="primary" disabled={busy||!understood||!enough(e.prestigeGain,1)} onClick={()=>{execute({kind:'prestige',expectedCycles:e.cycles,expectedGain:e.prestigeGain});close();}}>Confirmar novo ciclo</button></div></div>}</MotionDialog>}
  </section>;
}
