import { useState } from 'react';
import { PRODUCERS, UPGRADES, ACHIEVEMENTS, PERMANENT } from '../shared/economy';
import type { GameState, GameAction } from '../shared/game';
import { MotionDialog } from './MotionDialog';
const number=(n:number)=>n.toLocaleString('pt-BR',{maximumFractionDigits:2});
export function EconomyWorkspace({state,busy,execute}:{state:GameState;busy:boolean;execute(a:GameAction):void}) {
  const [tab,setTab]=useState<'production'|'upgrades'|'achievements'|'legacy'>('production'),[quantity,setQuantity]=useState<1|10>(1),[confirm,setConfirm]=useState(false),[understood,setUnderstood]=useState(false);
  const e=state.economy;
  return <section className="economy-workspace"><header><span className="game-kicker">CIDADE / ECONOMIA INCREMENTAL</span><h1>Uma cidade que produz.</h1><p>Construa uma rede, especialize a produção e leve seu legado ao próximo ciclo.</p></header><div className="economy-metrics"><div><small>PRODUÇÃO / MIN</small><strong data-testid="production-rate">{number(e.rate)}</strong></div><div><small>PRODUZIDO NA JORNADA</small><strong>{number(e.lifetime)}</strong></div><div><small>CONQUISTAS</small><strong>{e.achievements.length}<span> / {ACHIEVEMENTS.length}</span></strong></div><div><small>LEGADO PERMANENTE</small><strong>+{e.prestige*5}%</strong></div></div><nav className="economy-tabs" aria-label="Economia da cidade">{([['production','Produção'],['upgrades','Tecnologias'],['achievements','Conquistas'],['legacy','Prestígio']] as const).map(([id,name])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{name}</button>)}</nav>
    {tab==='production'&&<><div className="economy-section-label"><span>PRODUTORES / CUSTO CRESCENTE</span><label>Comprar <select aria-label="Quantidade de produtores" value={quantity} onChange={event=>setQuantity(Number(event.target.value) as 1|10)}><option value={1}>×1</option><option value={10}>×10</option></select></label></div><div className="producer-grid">{PRODUCERS.map((p,i)=>{const v=e.producersView.find(v=>v.id===p.id)!;const cost=quantity===10?v.cost10:v.cost;return<article key={p.id} className={!v.unlocked?'locked':''}><div className="producer-top"><span>{String(i+1).padStart(2,'0')} / REDE</span><strong>{v.count}<small> unidades</small></strong></div><h2>{p.name}</h2><p>{p.description}</p><div className="producer-details"><span>{number(v.rate)} moedas/min</span><span>Próximo marco: {[5,15,30,100].find(n=>n>v.count)??'máximo'}</span></div><button className="primary" aria-label={`Comprar ${quantity} ${p.name}`} disabled={busy||!v.unlocked||v.count+quantity>100||state.coins<cost} onClick={()=>execute({kind:'producer-buy',producer:p.id,quantity})}>{v.unlocked?v.count+quantity>100?'Limite de 100 unidades':`${number(cost)} moedas · Comprar ×${quantity}`:`Desbloqueia em ${number(p.unlock)} moedas produzidas`}</button></article>;})}</div><p className="economy-footnote">As compras seguintes custam 17% mais. A produção é automática, inclusive com o app fechado, até {e.offlineDays} dias por visita. Melhorias são liquidadas pela taxa anterior antes de mudar a produção.</p></>}
    {tab==='upgrades'&&<><div className="economy-section-label"><span>CADEIAS DE ESPECIALIZAÇÃO</span><span>{e.upgrades.length} / {UPGRADES.length} adquiridas</span></div><div className="technology-grid">{UPGRADES.map(u=>{const v=e.upgradesView.find(v=>v.id===u.id)!;return<article key={u.id} className={v.owned?'earned':!v.unlocked?'locked':''}><span className="technology-status">{v.owned?'ADQUIRIDA':v.unlocked?'DISPONÍVEL':'REQUISITOS PENDENTES'}</span><h2>{u.name}</h2><p>{u.description}</p><button aria-label={`Adquirir ${u.name}`} disabled={busy||v.owned||!v.unlocked||state.coins<u.cost} onClick={()=>execute({kind:'economy-upgrade',id:u.id})}>{v.owned?'✓ Incorporada':`${number(u.cost)} moedas · Adquirir`}</button></article>;})}</div></>}
    {tab==='achievements'&&<><div className="economy-section-label"><span>MARCOS DA SUA JORNADA</span><span>+{e.achievements.length}% na produção automática</span></div><p className="economy-footnote">Cada conquista concede +1% de produção. Conquistas e contadores da jornada permanecem após o prestígio.</p><div className="achievement-grid">{ACHIEVEMENTS.map(a=>{const v=e.achievementsView.find(v=>v.id===a.id)!;return<article key={a.id} className={v.unlocked?'earned':''}><span>{v.unlocked?'✓ CONQUISTADA':'EM PROGRESSO'}</span><h2>{a.name}</h2><p>{a.description}</p><progress aria-label={`Progresso ${a.name}`} max={a.target} value={Math.min(a.target,v.progress)}/><small>{number(Math.min(a.target,v.progress))} / {number(a.target)}</small></article>;})}</div></>}
    {tab==='legacy'&&<><div className="prestige-summary"><div><span className="game-kicker">CICLO {e.cycles+1} / ASCENSÃO OPCIONAL</span><h2>O próximo horizonte.</h2><p>Troque parte da economia por insígnias e um bônus permanente de 5% por ponto de prestígio.</p><strong>+{e.prestigeGain} <small>insígnias disponíveis neste reinício</small></strong><p>Próxima insígnia em {number(e.nextPrestigeAt)} moedas produzidas na jornada.</p><button className="primary" disabled={busy||e.prestigeGain<1} onClick={()=>{setUnderstood(false);setConfirm(true);}}>Revisar novo ciclo</button></div><dl><dt>Reinicia</dt><dd>Saldo de moedas, produtores automáticos, tecnologias do ciclo e nível do motor. Uma partida ativa da Oficina é encerrada.</dd><dt>Permanece</dt><dd>XP, personagem, inventário, canteiros, compras do mercado, skins, conquistas, memória e melhorias permanentes. Notas, matérias, projetos e foco são preservados.</dd></dl></div><div className="economy-section-label"><span>MELHORIAS PERMANENTES</span><span>{e.tokens} insígnias para gastar</span></div><div className="technology-grid">{PERMANENT.map(u=>{const owned=e.permanent.includes(u.id);return<article key={u.id} className={owned?'earned':''}><span className="technology-status">LEGADO / TODOS OS CICLOS</span><h2>{u.name}</h2><p>{u.description}</p><button aria-label={`Adquirir ${u.name}`} disabled={busy||owned||e.tokens<u.cost} onClick={()=>execute({kind:'permanent-upgrade',id:u.id})}>{owned?'✓ Permanente':`${u.cost} insígnias · Adquirir`}</button></article>;})}</div></>}
    {confirm&&<MotionDialog title="Iniciar novo ciclo?" close={()=>setConfirm(false)}>{close=><div className="prestige-confirm"><p>Você receberá <strong>{e.prestigeGain} insígnias</strong>. O bônus permanente passará a <strong>+{(e.prestige+e.prestigeGain)*5}%</strong>.</p><p>Serão reiniciados: <strong>{number(state.coins)} moedas</strong>, todos os produtores automáticos, tecnologias do ciclo e nível {state.engine.level} do motor. A Oficina ativa será encerrada.</p><p>Seu estudo, XP, inventário, construções do mercado, cultivos, skins, memória, conquistas e melhorias permanentes serão conservados.</p><label><input type="checkbox" checked={understood} onChange={event=>setUnderstood(event.target.checked)}/> Entendi quais partes da economia serão reiniciadas.</label><div className="dialog-buttons"><button disabled={busy} onClick={close}>Continuar neste ciclo</button><button className="primary" disabled={busy||!understood||e.prestigeGain<1} onClick={()=>{execute({kind:'prestige',expectedCycles:e.cycles,expectedGain:e.prestigeGain});close();}}>Confirmar novo ciclo</button></div></div>}</MotionDialog>}
  </section>;
}
