import { useEffect,useRef,useState,type FormEvent } from 'react';
import { gsap } from 'gsap';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import type { NoteRef } from '../shared/contracts';
import type { StudyCatalog,NoteLink } from '../shared/study';
import { useReducedMotion } from './motion';
import { Icon } from './Icon';
import './graph.css';
export default function GraphWorkspace({activeArea,initialSubjectId,openNote}:{activeArea:boolean;initialSubjectId:string|null;openNote(subjectId:string,id:string):Promise<void>}){
  const [catalog,setCatalog]=useState<StudyCatalog|null>(null),[subject,setSubject]=useState(initialSubjectId??''),[links,setLinks]=useState<NoteLink[]>([]),[selected,setSelected]=useState(''),[preview,setPreview]=useState(''),[source,setSource]=useState(''),[target,setTarget]=useState(''),[label,setLabel]=useState('Relaciona'),[error,setError]=useState(''),[busy,setBusy]=useState(false);const guard=useRef(false),current=useRef(subject);current.current=subject;
  useEffect(()=>{if(!activeArea)return;let stopped=false;void window.desktop.studyCatalog().then(r=>{if(stopped)return;if(r.ok){setCatalog(r.value);setSubject(s=>r.value.subjects.some(v=>v.id===s)?s:r.value.subjects[0]?.id??'');}else setError(r.message);});return()=>{stopped=true;};},[activeArea]);
  const notes=catalog?.notes.filter(n=>n.subjectId===subject)??[],note=notes.find(n=>n.id===selected);
  useEffect(()=>{let stopped=false;setLinks([]);setSelected('');setSource('');setTarget('');setError('');if(subject)void window.desktop.noteLinks({subjectId:subject}).then(r=>{if(!stopped){if(r.ok)setLinks(r.value);else setError(r.message);}});return()=>{stopped=true;};},[subject]);
  useEffect(()=>{let stopped=false;setPreview('');if(note&&activeArea)void window.desktop.openNote({id:note.id}).then(r=>{if(!stopped){if(r.ok)setPreview(r.value.text.replace(/^\uFEFF?---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/,''));else setError(r.message);}});return()=>{stopped=true;};},[note?.id,activeArea]);
  async function link(e:FormEvent){e.preventDefault();if(guard.current)return;guard.current=true;setBusy(true);setError('');try{const r=await window.desktop.saveNoteLink({subjectId:subject,sourceId:source,targetId:target,label});if(current.current!==subject)return;if(r.ok)setLinks(r.value);else setError(r.message);}finally{guard.current=false;setBusy(false);}}
  async function remove(item:NoteLink){if(guard.current)return;guard.current=true;setBusy(true);try{const r=await window.desktop.removeNoteLink({subjectId:item.subjectId,id:item.id});if(current.current!==subject)return;if(r.ok)setLinks(r.value);else setError(r.message);}finally{guard.current=false;setBusy(false);}}
  return <div className="graph-workspace" data-area-ready={!!catalog||!!error}><header><span className="eyebrow">NOTAS / RELAÇÕES / DESCOBERTAS</span><h1>Uma ideia encontra a outra.</h1><p>Conecte suas notas e veja o caminho entre elas.</p><label>Matéria<select aria-label="Matéria do grafo" value={subject} disabled={busy} onChange={e=>setSubject(e.target.value)}>{catalog?.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></header>{error&&<p role="alert">{error}</p>}<div className="graph-layout"><section className="graph-visual"><GraphScene notes={notes.slice(0,200)} links={links} selected={selected} select={setSelected} active={activeArea}/>{!notes.length&&<div className="graph-empty"><h2>Uma conexão começa com suas notas.</h2><p>Crie notas em Estudos e volte para ligá-las.</p></div>}<p className="graph-help">Selecione uma nota. Arraste para explorar e use a roda para aproximar.{notes.length>200?' O cenário mostra as primeiras 200 notas; a lista permite acessar todas.':''}</p></section><aside className="graph-details"><h2>{note?.title??'Escolha uma nota'}</h2>{note&&<><button className="primary" onClick={()=>openNote(note.subjectId,note.id)}>Abrir no caderno <Icon kind="arrow"/></button><div className="graph-preview"><ReactMarkdown remarkPlugins={[remarkGfm]} skipHtml components={{a:({children})=><span>{children}</span>,img:({alt})=><span>[Imagem: {alt??'sem descrição'}]</span>}}>{preview.slice(0,30000)}</ReactMarkdown></div></>}<details open><summary>Suas notas · {notes.length}</summary><nav aria-label="Notas do grafo">{notes.map(n=><button key={n.id} aria-pressed={selected===n.id} onClick={()=>setSelected(n.id)}>{n.title}</button>)}</nav></details><form onSubmit={link}><h3>Criar relação</h3><label>Origem<select aria-label="Nota de origem da relação" value={source} onChange={e=>setSource(e.target.value)} required><option value="">Escolha uma nota</option>{notes.map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><label>Destino<select aria-label="Nota de destino da relação" value={target} onChange={e=>setTarget(e.target.value)} required><option value="">Escolha outra nota</option>{notes.filter(n=>n.id!==source).map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><label>Relação<input aria-label="Nome da relação" maxLength={120} value={label} onChange={e=>setLabel(e.target.value)} required/></label><button className="primary" disabled={busy||!source||!target||source===target}>Conectar notas</button></form><section aria-label="Relações salvas">{links.map(l=><div className="graph-link" key={l.id}><p>{notes.find(n=>n.id===l.sourceId)?.title} → {notes.find(n=>n.id===l.targetId)?.title}<small>{l.label}</small></p><button disabled={busy} onClick={()=>remove(l)} aria-label={`Excluir relação ${l.label}`}>×</button></div>)}</section></aside></div></div>;
}
function GraphScene({notes,links,selected,select,active}:{notes:NoteRef[];links:NoteLink[];selected:string;select(id:string):void;active:boolean}){
  const reduced=useReducedMotion(),host=useRef<HTMLDivElement>(null),labels=useRef<(HTMLButtonElement|null)[]>([]),live=useRef({active,selected,select,reduced});live.current={active,selected,select,reduced};const focus=useRef((id:string)=>{}),redraw=useRef(()=>{}),[error,setError]=useState('');
  useEffect(()=>{redraw.current();},[active,reduced]);useEffect(()=>{focus.current(selected);redraw.current();},[selected]);
  useEffect(()=>{let stopped=false,cleanup=()=>{};void Promise.all([import('three'),import('three/addons/controls/OrbitControls.js')]).then(([T,{OrbitControls}])=>{if(stopped||!host.current)return;const el=host.current;let renderer:InstanceType<typeof T.WebGLRenderer>;try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'low-power'});}catch{setError('O grafo 3D não abriu. Você pode usar a lista de notas e relações ao lado.');return;}renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.domElement.dataset.testid='graph-canvas';renderer.domElement.setAttribute('aria-label','Grafo de notas reais');el.prepend(renderer.domElement);const scene=new T.Scene();scene.background=new T.Color('#0c1210');const camera=new T.PerspectiveCamera(42,1,.1,1000);camera.position.set(0,0,20);const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=false;orbit.minDistance=4;orbit.maxDistance=45;orbit.enableRotate=false;orbit.mouseButtons={LEFT:T.MOUSE.PAN,MIDDLE:T.MOUSE.DOLLY,RIGHT:T.MOUSE.PAN};const geometry=new T.SphereGeometry(.18,16,10),materials:InstanceType<typeof T.MeshBasicMaterial>[]=[],nodes:InstanceType<typeof T.Mesh>[]=[];const positions=new Map<string,InstanceType<typeof T.Vector3>>();notes.forEach((n,i)=>{const angle=i*Math.PI*2/Math.max(1,notes.length),ring=2.5+Math.sqrt(notes.length)*.6;const p=new T.Vector3(Math.cos(angle)*ring,Math.sin(angle)*ring,Math.sin(i*2.3)*.7);positions.set(n.id,p);const m=new T.MeshBasicMaterial({color:'#91ad9a'});materials.push(m);const node=new T.Mesh(geometry,m);node.position.copy(p);node.userData.id=n.id;nodes.push(node);scene.add(node);});const lineGeometry=new T.BufferGeometry(),lineMaterial=new T.LineBasicMaterial({color:'#826f48',transparent:true,opacity:.7}),points:number[]=[];links.forEach(l=>{const a=positions.get(l.sourceId),b=positions.get(l.targetId);if(a&&b)points.push(...a.toArray(),...b.toArray());});lineGeometry.setAttribute('position',new T.Float32BufferAttribute(points,3));scene.add(new T.LineSegments(lineGeometry,lineMaterial));let raf=0;const pose={x:0,y:0},ray=new T.Raycaster(),pointer=new T.Vector2();
    function draw(){raf=0;orbit.enabled=live.current.active;nodes.forEach((n,i)=>{const chosen=n.userData.id===live.current.selected;(n.material as InstanceType<typeof T.MeshBasicMaterial>).color.set(chosen?'#edcf88':'#91ad9a');n.scale.setScalar(chosen?1.6:1);const p=n.position.clone().project(camera),label=labels.current[i];if(label){label.style.left=`${(p.x+1)*el.clientWidth/2}px`;label.style.top=`${(1-p.y)*el.clientHeight/2}px`;label.style.visibility=p.z>1||p.z< -1?'hidden':'visible';}});renderer.render(scene,camera);}
    function request(){if(live.current.reduced&&gsap.isTweening(pose)){gsap.killTweensOf(pose);renderer.domElement.dataset.camera='idle';}if(raf)cancelAnimationFrame(raf);if(live.current.active&&!document.hidden)raf=requestAnimationFrame(draw);else{gsap.killTweensOf(pose);renderer.domElement.dataset.camera='idle';orbit.enabled=false;}}
    function apply(){camera.position.x=pose.x;camera.position.y=pose.y;orbit.target.set(pose.x,pose.y,0);orbit.update();request();}
    focus.current=id=>{gsap.killTweensOf(pose);const p=positions.get(id);if(!p)return;Object.assign(pose,{x:orbit.target.x,y:orbit.target.y});renderer.domElement.dataset.camera=live.current.reduced?'idle':'moving';if(live.current.reduced||!live.current.active){pose.x=p.x*.45;pose.y=p.y*.45;apply();}else gsap.to(pose,{x:p.x*.45,y:p.y*.45,duration:.85,ease:'power3.inOut',onUpdate:apply,onComplete:()=>{renderer.domElement.dataset.camera='idle';request();}});};redraw.current=request;
    function pick(e:MouseEvent){if(!live.current.active||document.querySelector('dialog[open]'))return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.x)/r.width*2-1,-(e.clientY-r.y)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(nodes)[0];if(hit)live.current.select(hit.object.userData.id);}
    const observer=new ResizeObserver(()=>{if(!el.clientWidth||!el.clientHeight)return;renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();draw();});observer.observe(el);const gesture=()=>{gsap.killTweensOf(pose);renderer.domElement.dataset.camera='idle';};orbit.addEventListener('change',request);orbit.addEventListener('start',gesture);renderer.domElement.addEventListener('click',pick);document.addEventListener('visibilitychange',request);draw();focus.current(live.current.selected);cleanup=()=>{gsap.killTweensOf(pose);cancelAnimationFrame(raf);observer.disconnect();orbit.removeEventListener('change',request);orbit.removeEventListener('start',gesture);orbit.dispose();document.removeEventListener('visibilitychange',request);renderer.domElement.removeEventListener('click',pick);geometry.dispose();lineGeometry.dispose();materials.forEach(m=>m.dispose());lineMaterial.dispose();renderer.dispose();renderer.domElement.remove();redraw.current=()=>{};focus.current=()=>{};};}).catch(()=>{if(!stopped)setError('Não foi possível carregar o cenário. As relações e notas continuam disponíveis.');});return()=>{stopped=true;cleanup();};},[notes.map(n=>n.id).join(','),links.map(l=>`${l.sourceId}:${l.targetId}`).join(',')]);
  return <div className="graph-canvas-host" ref={host}>{notes.map((n,i)=><button className="graph-node-label" key={n.id} ref={e=>{labels.current[i]=e;}} aria-label={`Selecionar nó ${n.title}`} aria-pressed={selected===n.id} onClick={()=>select(n.id)}>{n.title}</button>)}{error&&<p className="graph-error" role="alert">{error}</p>}</div>;
}
