import { useEffect,useRef,useState } from 'react';
import { gsap } from 'gsap';
import type { NoteRef } from '../shared/contracts';
import type { NoteLink } from '../shared/study';
import { useReducedMotion } from './motion';
import { usePreferences } from './preferences';
export function GraphScene({notes,links,selected,select,active}:{notes:NoteRef[];links:NoteLink[];selected:string;select(id:string):void;active:boolean}){
 const {value:preferences}=usePreferences(),reduced=useReducedMotion(),editorial=preferences.theme==='editorial';
 const host=useRef<HTMLDivElement>(null),labels=useRef<(HTMLButtonElement|null)[]>([]),live=useRef({active,selected,select,reduced,editorial});live.current={active,selected,select,reduced,editorial};
 const snapshot=useRef<{x:number;y:number;zoom:number;nodes:Record<string,{x:number;y:number}>}|null>(null);
 const focus=useRef((id:string)=>{}),redraw=useRef(()=>{}),controls=useRef({zoom:(_direction:number)=>{},reset:()=>{}}),[error,setError]=useState('');
 useEffect(()=>{redraw.current();},[active,reduced,editorial]);useEffect(()=>{focus.current(selected);redraw.current();},[selected]);
 useEffect(()=>{let stopped=false,cleanup=()=>{};
  void Promise.all([import('three'),import('three/addons/controls/OrbitControls.js')]).then(([T,{OrbitControls}])=>{
   if(stopped||!host.current)return;const el=host.current;let renderer:InstanceType<typeof T.WebGLRenderer>;
   try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});}catch{setError('O grafo não abriu. Use a lista de notas e relações.');return;}
   renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));const canvas=renderer.domElement;canvas.dataset.testid='graph-canvas';canvas.tabIndex=0;canvas.setAttribute('aria-label','Grafo de notas reais');el.prepend(canvas);
   const scene=new T.Scene(),camera=new T.OrthographicCamera(-12,12,10,-10,.1,100);camera.position.set(snapshot.current?.x??0,snapshot.current?.y??0,20);camera.zoom=snapshot.current?.zoom??1;camera.updateProjectionMatrix();
   const orbit=new OrbitControls(camera,canvas);orbit.target.set(camera.position.x,camera.position.y,0);orbit.enableRotate=false;orbit.enableZoom=false;orbit.enableDamping=!live.current.reduced;orbit.dampingFactor=.12;orbit.mouseButtons={LEFT:T.MOUSE.PAN,MIDDLE:T.MOUSE.PAN,RIGHT:T.MOUSE.PAN};
   const geometry=new T.SphereGeometry(.16,14,8),materials:InstanceType<typeof T.MeshBasicMaterial>[]=[],nodes:InstanceType<typeof T.Mesh>[]=[],index=new Map<string,number>();
   const velocity=notes.map(()=>new T.Vector2());notes.forEach((n,i)=>{index.set(n.id,i);const material=new T.MeshBasicMaterial({color:'#92988f'}),node=new T.Mesh(geometry,material),a=i*2.399963,r=1+Math.sqrt(i)*.8;const old=snapshot.current?.nodes[n.id];node.position.set(old?.x??Math.cos(a)*r,old?.y??Math.sin(a)*r,0);node.userData.id=n.id;scene.add(node);nodes.push(node);materials.push(material);});
   const edges=links.map(l=>[index.get(l.sourceId),index.get(l.targetId)]).filter((e):e is [number,number]=>e[0]!==undefined&&e[1]!==undefined),lineGeometry=new T.BufferGeometry(),points=new Float32Array(edges.length*6),colors=new Float32Array(edges.length*6),lineMaterial=new T.LineBasicMaterial({vertexColors:true,transparent:true,opacity:.7});lineGeometry.setAttribute('position',new T.BufferAttribute(points,3));lineGeometry.setAttribute('color',new T.BufferAttribute(colors,3));scene.add(new T.LineSegments(lineGeometry,lineMaterial));
   let raf=0,alpha=notes.length?.5:0,hover='',zoomTarget=camera.zoom,gestureStart:{x:number;y:number}|null=null,dragged=false;const pose={x:0,y:0},ray=new T.Raycaster(),pointer=new T.Vector2(),color=new T.Color();
   function simulate(){if(alpha<.008)return;for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){const a=nodes[i].position,b=nodes[j].position,dx=a.x-b.x,dy=a.y-b.y,d=Math.max(.25,dx*dx+dy*dy),force=.016*alpha/d;velocity[i].x+=dx*force;velocity[i].y+=dy*force;velocity[j].x-=dx*force;velocity[j].y-=dy*force;}
    for(const [i,j] of edges){const a=nodes[i].position,b=nodes[j].position,dx=b.x-a.x,dy=b.y-a.y,d=Math.max(.1,Math.hypot(dx,dy)),force=(d-2.8)*.009*alpha/d;velocity[i].x+=dx*force;velocity[i].y+=dy*force;velocity[j].x-=dx*force;velocity[j].y-=dy*force;}
    nodes.forEach((n,i)=>{velocity[i].x=(velocity[i].x-n.position.x*.003*alpha)*.82;velocity[i].y=(velocity[i].y-n.position.y*.003*alpha)*.82;n.position.x+=velocity[i].x;n.position.y+=velocity[i].y;});alpha*=.979;
   }
   function paint(){scene.background=live.current.editorial?null:new T.Color('#0c1210');const highlight=hover||live.current.selected,neighbors=new Set([highlight]);edges.forEach(([i,j])=>{if(nodes[i].userData.id===highlight)neighbors.add(nodes[j].userData.id);if(nodes[j].userData.id===highlight)neighbors.add(nodes[i].userData.id);});
    nodes.forEach((n,i)=>{const chosen=n.userData.id===live.current.selected,related=!highlight||neighbors.has(n.userData.id);materials[i].color.set(chosen?(live.current.editorial?'#e1ded4':'#edcf88'):related?'#989e94':'#454b43');n.scale.setScalar(chosen?1.55:1);const projected=n.position.clone().project(camera),label=labels.current[i];if(label){label.style.left=`${(projected.x+1)*el.clientWidth/2}px`;label.style.top=`${(1-projected.y)*el.clientHeight/2}px`;label.style.visibility=Math.abs(projected.x)>1.05||Math.abs(projected.y)>1.05?'hidden':'visible';label.style.opacity=chosen||n.userData.id===hover?'1':String(Math.max(0,Math.min(1,(camera.zoom-.45)*1.7))*(related?1:.25));}});
    edges.forEach(([i,j],n)=>{points.set([...nodes[i].position.toArray(),...nodes[j].position.toArray()],n*6);const related=!highlight||nodes[i].userData.id===highlight||nodes[j].userData.id===highlight;color.set(related?(highlight?'#b0b5a8':'#636a60'):'#2c322b');colors.set([...color.toArray(),...color.toArray()],n*6);});lineGeometry.attributes.position.needsUpdate=true;lineGeometry.attributes.color.needsUpdate=true;renderer.render(scene,camera);canvas.dataset.targetX=camera.position.x.toFixed(4);canvas.dataset.targetY=camera.position.y.toFixed(4);canvas.dataset.zoom=camera.zoom.toFixed(4);canvas.dataset.force=alpha>.008?'settling':'idle';
   }
   function tick(){raf=0;if(!live.current.active||document.hidden){canvas.dataset.camera='idle';return;}orbit.enableDamping=!live.current.reduced;const changed=orbit.update();if(live.current.reduced){if(gsap.isTweening(pose))gsap.killTweensOf(pose);zoomTarget=camera.zoom;if(alpha>.008){for(let i=0;i<220;i++)simulate();alpha=0;}}else simulate();const zooming=Math.abs(zoomTarget-camera.zoom)>.0002;if(zooming){camera.zoom+=(zoomTarget-camera.zoom)*.2;camera.updateProjectionMatrix();}const moving=!!changed||zooming||gsap.isTweening(pose);canvas.dataset.camera=moving?'moving':'idle';paint();if(moving||alpha>.008)request();}
   function request(){if(!live.current.active||document.hidden){if(raf)cancelAnimationFrame(raf);raf=0;gsap.killTweensOf(pose);canvas.dataset.camera='idle';orbit.enabled=false;return;}orbit.enabled=true;if(!raf)raf=requestAnimationFrame(tick);}
   function apply(){const dx=pose.x-orbit.target.x,dy=pose.y-orbit.target.y;camera.position.x+=dx;camera.position.y+=dy;orbit.target.set(pose.x,pose.y,0);orbit.update();request();}
   focus.current=id=>{gsap.killTweensOf(pose);const i=index.get(id);if(i===undefined)return;Object.assign(pose,{x:orbit.target.x,y:orbit.target.y});const target=nodes[i].position;if(live.current.reduced){pose.x=target.x*.65;pose.y=target.y*.65;apply();}else gsap.to(pose,{x:target.x*.65,y:target.y*.65,duration:.55,ease:'power3.out',onUpdate:apply,onComplete:request});};redraw.current=request;
   function zoom(direction:number){zoomTarget=Math.min(3.5,Math.max(.35,zoomTarget*Math.exp(direction*.12)));if(live.current.reduced){camera.zoom=zoomTarget;camera.updateProjectionMatrix();}request();}controls.current={zoom,reset:()=>{gsap.killTweensOf(pose);pose.x=0;pose.y=0;apply();zoomTarget=1;if(live.current.reduced){camera.zoom=1;camera.updateProjectionMatrix();}request();}};
   function point(e:MouseEvent){const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.x)/r.width*2-1,-(e.clientY-r.y)/r.height*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObjects(nodes)[0]?.object.userData.id as string|undefined;}
   function pick(e:MouseEvent){if(!live.current.active||dragged||document.querySelector('dialog[open]'))return;const id=point(e);if(id)live.current.select(id);}
   function over(e:MouseEvent){if(gestureStart&&Math.hypot(e.clientX-gestureStart.x,e.clientY-gestureStart.y)>5)dragged=true;const id=point(e)??'';if(id!==hover){hover=id;request();}}
   const wheel=(e:WheelEvent)=>{if(!live.current.active)return;e.preventDefault();zoom(-Math.max(-3,Math.min(3,e.deltaY/90)));};const down=(e:PointerEvent)=>{gestureStart={x:e.clientX,y:e.clientY};dragged=false;canvas.focus();};const up=()=>{gestureStart=null;};const leave=()=>{hover='';request();};
   function key(e:KeyboardEvent){if(!live.current.active||e.target!==canvas)return;if(['+','=','-'].includes(e.key)){e.preventDefault();zoom(e.key==='-'?-1:1);}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const step=(e.shiftKey?1:.4)/camera.zoom;pose.x=orbit.target.x+(e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0);pose.y=orbit.target.y+(e.key==='ArrowUp'?step:e.key==='ArrowDown'?-step:0);apply();}}
   const observer=new ResizeObserver(()=>{if(!el.clientWidth||!el.clientHeight)return;renderer.setSize(el.clientWidth,el.clientHeight);const aspect=el.clientWidth/el.clientHeight;camera.left=-10*aspect;camera.right=10*aspect;camera.updateProjectionMatrix();request();});observer.observe(el);
   const gesture=()=>{gsap.killTweensOf(pose);};orbit.addEventListener('change',request);orbit.addEventListener('start',gesture);canvas.addEventListener('wheel',wheel,{passive:false});canvas.addEventListener('click',pick);canvas.addEventListener('pointermove',over);canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointerleave',leave);canvas.addEventListener('keydown',key);document.addEventListener('visibilitychange',request);request();
   cleanup=()=>{snapshot.current={x:camera.position.x,y:camera.position.y,zoom:camera.zoom,nodes:Object.fromEntries(nodes.map(n=>[n.userData.id,{x:n.position.x,y:n.position.y}]))};gsap.killTweensOf(pose);cancelAnimationFrame(raf);observer.disconnect();orbit.removeEventListener('change',request);orbit.removeEventListener('start',gesture);orbit.dispose();canvas.removeEventListener('wheel',wheel);canvas.removeEventListener('click',pick);canvas.removeEventListener('pointermove',over);canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointerleave',leave);canvas.removeEventListener('keydown',key);document.removeEventListener('visibilitychange',request);geometry.dispose();lineGeometry.dispose();lineMaterial.dispose();materials.forEach(m=>m.dispose());renderer.dispose();canvas.remove();focus.current=()=>{};redraw.current=()=>{};};
  }).catch(()=>{if(!stopped)setError('Não foi possível carregar o grafo. As relações e notas continuam disponíveis.');});return()=>{stopped=true;cleanup();};
 },[notes.map(n=>n.id).join(','),links.map(l=>`${l.sourceId}:${l.targetId}`).join(',')]);
 return <div className="graph-canvas-host" ref={host}>{notes.map((n,i)=><button className="graph-node-label" key={n.id} ref={e=>{labels.current[i]=e;}} aria-label={`Selecionar nó ${n.title}`} aria-pressed={selected===n.id} onClick={()=>select(n.id)}>{n.title}</button>)}<div className="graph-camera-tools"><button aria-label="Aproximar grafo" onClick={()=>controls.current.zoom(1)}>+</button><button aria-label="Afastar grafo" onClick={()=>controls.current.zoom(-1)}>−</button><button aria-label="Centralizar grafo" onClick={()=>controls.current.reset()}>◎</button></div>{error&&<p className="graph-error" role="alert">{error}</p>}</div>;
}
