import { useEffect,useRef,useState,type ReactNode,type PointerEvent,type FormEvent } from 'react';
import type { Material } from '../shared/contracts';
import type { PdfMark } from '../shared/study';
import { MotionDialog } from './MotionDialog';
type Box={x:number;y:number;width:number;height:number};
export function PdfAnnotations({material,fingerprint,page,ready,noteId,onPage,onNote,children}:{material:Material;fingerprint:string;page:number;ready:boolean;noteId:string|null;onPage(page:number):void;onNote(id:string):void;children:ReactNode}){
  const [marks,setMarks]=useState<PdfMark[]>([]),[other,setOther]=useState(0),[marking,setMarking]=useState(false),[box,setBox]=useState<Box|null>(null),[pending,setPending]=useState<Box|null>(null),[comment,setComment]=useState(''),[link,setLink]=useState(true),[color,setColor]=useState<'gold'|'sage'|'blue'>('gold'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const start=useRef<{x:number;y:number}|null>(null),guard=useRef(false);
  useEffect(()=>{let stopped=false;setMarks([]);setOther(0);setError('');if(fingerprint)void window.desktop.listPdfMarks({subjectId:material.subjectId,materialId:material.id,fingerprint}).then(r=>{if(!stopped){if(r.ok){setMarks(r.value.marks);setOther(r.value.otherVersions);}else setError(r.message);}});return()=>{stopped=true;};},[material.id,fingerprint]);
  useEffect(()=>{start.current=null;setBox(null);setPending(null);},[page,fingerprint]);
  function position(e:PointerEvent<SVGSVGElement>){const r=e.currentTarget.getBoundingClientRect();return{x:Math.min(1,Math.max(0,(e.clientX-r.x)/r.width)),y:Math.min(1,Math.max(0,(e.clientY-r.y)/r.height))};}
  function down(e:PointerEvent<SVGSVGElement>){if(!marking||!ready||e.button!==0)return;start.current=position(e);e.currentTarget.setPointerCapture(e.pointerId);setBox(null);}
  function move(e:PointerEvent<SVGSVGElement>){if(!start.current)return;const p=position(e),s=start.current;setBox({x:Math.min(s.x,p.x),y:Math.min(s.y,p.y),width:Math.abs(s.x-p.x),height:Math.abs(s.y-p.y)});}
  function end(e:PointerEvent<SVGSVGElement>){const s=start.current;if(!s)return;const p=position(e);start.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);const next={x:Math.min(s.x,p.x),y:Math.min(s.y,p.y),width:Math.abs(s.x-p.x),height:Math.abs(s.y-p.y)};setBox(null);if(next.width>=.002&&next.height>=.002){setPending(next);setComment('');}}
  async function save(e:FormEvent){e.preventDefault();if(!pending||guard.current)return;guard.current=true;setBusy(true);setError('');try{const r=await window.desktop.addPdfMark({subjectId:material.subjectId,materialId:material.id,fingerprint,noteId:link?noteId:null,page,...pending,color,comment});if(r.ok){setMarks(v=>[...v,r.value]);setPending(null);setMarking(false);}else setError(r.message);}finally{guard.current=false;setBusy(false);}}
  async function remove(item:PdfMark){if(guard.current)return;guard.current=true;setBusy(true);try{const r=await window.desktop.removePdfMark({subjectId:material.subjectId,materialId:material.id,id:item.id});if(r.ok)setMarks(v=>v.filter(m=>m.id!==item.id));else setError(r.message);}finally{guard.current=false;setBusy(false);}}
  const fill={gold:'#e3c579',sage:'#9ab7a4',blue:'#82b3d7'};
  return <><div className="pdf-annotation-tools"><button disabled={!ready||!fingerprint||busy} className={marking?'selected':''} aria-pressed={marking} onClick={()=>setMarking(v=>!v)}>Marcar área</button><span>{marking?'Arraste sobre a página para destacar um trecho.':`${marks.length} marcações neste documento`}</span></div><div className="pdf-sheet">{children}<svg className={`pdf-mark-overlay ${marking?'marking':''}`} viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-label="Áreas destacadas do PDF" onPointerDown={down} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>{start.current=null;setBox(null);}}>{marks.filter(m=>m.page===page).map(m=><rect key={m.id} x={m.x*1000} y={m.y*1000} width={m.width*1000} height={m.height*1000} fill={fill[m.color]} fillOpacity=".28" stroke={fill[m.color]} strokeWidth="2"/>)}{box&&<rect x={box.x*1000} y={box.y*1000} width={box.width*1000} height={box.height*1000} fill={fill[color]} fillOpacity=".25" stroke={fill[color]} strokeWidth="2"/>}</svg></div><section className="pdf-mark-list" aria-label="Marcações do PDF">{error&&<p role="alert">{error}</p>}{other>0&&<p>{other} marcações de uma versão anterior foram conservadas e ficam separadas desta página.</p>}{marks.map(m=><article key={m.id}><button onClick={()=>onPage(m.page)}>Página {m.page}</button><p>{m.comment||'Área destacada'}</p>{m.noteId&&<button onClick={()=>onNote(m.noteId!)}>Abrir nota vinculada</button>}<button disabled={busy} onClick={()=>remove(m)} aria-label={`Excluir marcação da página ${m.page}`}>Excluir</button></article>)}</section>{pending&&<MotionDialog title="Anotar trecho do PDF" close={()=>{if(!guard.current)setPending(null);}}>{requestClose=><form onSubmit={save}><label>Comentário<textarea aria-label="Comentário da marcação" maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)}/></label><label>Cor<select aria-label="Cor da marcação" value={color} onChange={e=>setColor(e.target.value as typeof color)}><option value="gold">Dourado</option><option value="sage">Sálvia</option><option value="blue">Azul</option></select></label>{noteId&&<label><input type="checkbox" checked={link} onChange={e=>setLink(e.target.checked)}/> Vincular à nota aberta</label>}<p>O destaque fica salvo no app; seu PDF permanece intacto.</p>{error&&<p role="alert">{error}</p>}<div className="dialog-buttons"><button type="button" disabled={busy} onClick={requestClose}>Cancelar</button><button className="primary" disabled={busy}>Salvar marcação</button></div></form>}</MotionDialog>}</>;
}
