import { useEffect, useRef, useState } from 'react';
import type { ProjectCatalog, ProjectDocument, ProjectFileRef, ProjectTree } from '../shared/projects';
import { ProjectEditor } from './ProjectEditor';
import './projects.css';
import { Icon, type Kind } from './Icon';
import { useSurfaceMotion } from './motion';
const fileIcon = (name: string): Kind => /\.(tsx?|jsx?)$/i.test(name) ? 'code' : /\.json$/i.test(name) ? 'json' : /\.(md|txt)$/i.test(name) ? 'note' : /\.(css|html?)$/i.test(name) ? 'layout' : 'file';
type BufferTab = { doc: ProjectDocument; text: string; baseHash: string; conflict: ProjectDocument | null; status: string };
const keyOf = (r: ProjectFileRef) => `${r.projectId}:${r.path}`;
export default function ProjectWorkspace({ registerFlush, activeArea,requestedProject }: { activeArea: boolean; registerFlush(fn: (() => Promise<boolean>) | null): void;requestedProject?:{id:string;nonce:string}|null }) {
  const [catalog, setCatalog] = useState<ProjectCatalog>({ projects: [], view: { projectId: null, tabs: [], active: null } });
  const [tabs, setTabs] = useState<BufferTab[]>([]), [active, setActive] = useState<string | null>(null), [trees, setTrees] = useState<Record<string, ProjectTree>>({}), [expanded, setExpanded] = useState<string[]>([]);
  const [width, setWidth] = useState(() => { try { const saved = Number(localStorage.getItem('nodus.explorer.width')); return saved >= 190 && saved <= 400 ? saved : 260; } catch { return 260; } });
  const body = useRef<HTMLDivElement>(null), activeView = useRef(activeArea); activeView.current = activeArea;
  useSurfaceMotion(body, active ?? 'empty', activeArea);
  function resize(value: number) { const size = Math.max(190, Math.min(400, Math.round(value))); setWidth(size); try { localStorage.setItem('nodus.explorer.width', String(size)); } catch {} }
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true);
  const live = useRef({ tabs, active, catalog, busy }); live.current = { tabs, active, catalog, busy };
  const saving = useRef<Promise<void> | null>(null), drafts = useRef<Promise<boolean>>(Promise.resolve(true));
  const draftTimer = useRef<ReturnType<typeof setTimeout> | null>(null), guard = useRef(false), stopped = useRef(false);
  function update(id: string, patch: Partial<BufferTab>) { const next = live.current.tabs.map(t => keyOf(t.doc) === id ? { ...t, ...patch } : t); live.current.tabs = next; setTabs(next); }
  async function writeDrafts() {
    if (draftTimer.current) clearTimeout(draftTimer.current);
    const snapshot = [...live.current.tabs];
    const pending = drafts.current.then(async () => { try { for (const t of snapshot) if (t.text !== t.doc.text || t.doc.draft) { const r = await window.desktop.recoverProjectDraft({ projectId: t.doc.projectId, path: t.doc.path, hash: t.baseHash, text: t.text }); if (!r.ok) { setError(r.message); return false; } } return true; }
    catch { setError('Não foi possível preservar o rascunho. Mantenha esta janela aberta e tente novamente.'); return false; } }); drafts.current = pending; return pending;
  }
  async function flush() { if (saving.current) await saving.current; return writeDrafts(); }
  async function tree(ref: ProjectFileRef) { const r = await window.desktop.projectTree(ref); if (r.ok && !stopped.current) setTrees(v => ({ ...v, [keyOf(ref)]: r.value })); else if (!r.ok) setError(r.message); }
  async function persist(nextTabs = live.current.tabs, nextActive = live.current.active, projectId = live.current.catalog.view.projectId) {
    const view = { projectId, tabs: nextTabs.map(t => ({ projectId: t.doc.projectId, path: t.doc.path })), active: nextTabs.find(t => keyOf(t.doc) === nextActive)?.doc ?? null };
    const r = await window.desktop.saveProjectView({ ...view, active: view.active ? { projectId: view.active.projectId, path: view.active.path } : null }); if (!r.ok) setError(r.message);
  }
  const makeTab = (doc: ProjectDocument): BufferTab => ({ doc, text: doc.draft?.text ?? doc.text, baseHash: doc.draft?.baseHash ?? doc.hash ?? '', conflict: doc.draft && doc.hash !== doc.draft.baseHash && !doc.missing ? doc : null, status: doc.missing ? 'Arquivo ausente · rascunho recuperado' : doc.draft ? 'Rascunho recuperado' : 'Arquivo atualizado' });
  useEffect(() => { stopped.current = false; registerFlush(flush); void (async () => { const r = await window.desktop.listProjects(); if (!r.ok) { setError(r.message); setLoading(false); return; } if (stopped.current) return; setCatalog(r.value); const loaded: BufferTab[] = []; for (const ref of r.value.view.tabs) { const doc = await window.desktop.openProjectFile(ref); if (doc.ok) loaded.push(makeTab(doc.value)); else setError(doc.message); } if (stopped.current) return; setTabs(loaded); setActive(r.value.view.active ? keyOf(r.value.view.active) : loaded[0] ? keyOf(loaded[0].doc) : null); setLoading(false); if (r.value.view.projectId) await tree({ projectId: r.value.view.projectId, path: '' }); })().catch(() => { setError('Não foi possível abrir os projetos.'); setLoading(false); }); return () => { stopped.current = true; registerFlush(null); if (draftTimer.current) clearTimeout(draftTimer.current); }; }, []);
  useEffect(() => { const timer = setInterval(() => { void (async () => { const l = live.current, t = l.tabs.find(t => keyOf(t.doc) === l.active); if (!activeView.current || !t || guard.current) return; const r = await window.desktop.openProjectFile({ projectId: t.doc.projectId, path: t.doc.path }); if (!r.ok || stopped.current) return; const current = live.current.tabs.find(v => keyOf(v.doc) === keyOf(t.doc)); if (!current || r.value.hash === current.doc.hash && r.value.missing === current.doc.missing) return;
    if (current.text !== current.doc.text || current.doc.draft) update(keyOf(t.doc), { conflict: r.value.missing ? null : r.value, doc: { ...current.doc, missing: r.value.missing }, status: r.value.missing ? 'Arquivo ausente · rascunho preservado' : 'Alteração externa · revisão necessária' });
    else update(keyOf(t.doc), makeTab(r.value));
  })().catch(() => {}); }, 1500); return () => clearInterval(timer); }, []);
  async function choose(id: string) { if (!await flush()) return; setCatalog(c => ({ ...c, view: { ...c.view, projectId: id } })); live.current.catalog = { ...live.current.catalog, view: { ...live.current.catalog.view, projectId: id } }; await persist(undefined, undefined, id); await tree({ projectId: id, path: '' }); }
  useEffect(()=>{if(activeArea&&!loading&&requestedProject)void choose(requestedProject.id).catch(()=>setError('Não foi possível selecionar o projeto.'));},[activeArea,loading,requestedProject?.nonce]);
  async function add() { const r = await window.desktop.chooseProject(); if (!r.ok) setError(r.message); else if (r.value) { setCatalog(r.value); live.current.catalog = r.value; if (r.value.view.projectId) await choose(r.value.view.projectId); } }
  async function open(ref: ProjectFileRef) { if (!await flush()) return; const id = keyOf(ref); if (live.current.tabs.some(t => keyOf(t.doc) === id)) { setActive(id); live.current.active = id; await persist(); return; } if (live.current.tabs.length >= 12) { setError('Feche uma aba para abrir outro arquivo (limite: 12).'); return; } const r = await window.desktop.openProjectFile(ref); if (!r.ok) { setError(r.message); return; } const next = [...live.current.tabs, makeTab(r.value)]; live.current.tabs = next; live.current.active = id; setTabs(next); setActive(id); setError(''); await persist(); }
  async function performSave() { const t = live.current.tabs.find(t => keyOf(t.doc) === live.current.active); if (!t || t.doc.missing || t.conflict || guard.current) return; guard.current = true; setBusy(true); const submitted = t.text; try { if (!await writeDrafts()) return; const r = await window.desktop.saveProjectFile({ projectId: t.doc.projectId, path: t.doc.path, hash: t.baseHash, text: submitted }); if (!r.ok) { setError(r.message); return; } const id = keyOf(t.doc), current = live.current.tabs.find(v => keyOf(v.doc) === id)!; if (r.value.state === 'conflict') update(id, { conflict: r.value.external, status: 'Alteração externa · revisão necessária' }); else { update(id, { doc: r.value.document, text: current.text, baseHash: r.value.document.hash!, status: current.text === submitted ? 'Salvo no arquivo' : 'Edição em andamento', conflict: null }); if (current.text !== submitted) await writeDrafts(); } } catch { setError('Falha ao salvar. Sua edição permanece nesta aba; tente novamente.'); } finally { guard.current = false; setBusy(false); } }
  function trackMutation(action: () => Promise<void>) { if (guard.current) return; const pending = action(); saving.current = pending; void pending.finally(() => { if (saving.current === pending) saving.current = null; }); }
  function save() { trackMutation(performSave); }
  useEffect(() => { const key = (e: KeyboardEvent) => { if (activeView.current && !e.defaultPrevented && (e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 's') { e.preventDefault(); save(); } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, []);
  function change(text: string) { const id = live.current.active; if (!id) return; update(id, { text, status: 'Rascunho em edição' }); if (draftTimer.current) clearTimeout(draftTimer.current); draftTimer.current = setTimeout(() => void flush(), 250); }
  async function closeTab(id: string) { if (guard.current || !await flush()) return; const next = live.current.tabs.filter(t => keyOf(t.doc) !== id), selected = live.current.active === id ? next[0] ? keyOf(next[0].doc) : null : live.current.active; setTabs(next); setActive(selected); live.current.tabs = next; live.current.active = selected; await persist(); }
  async function performUseFile() { const t = live.current.tabs.find(t => keyOf(t.doc) === live.current.active); if (!t || guard.current) return; guard.current = true; setBusy(true); try { if (!await writeDrafts()) return; const r = await window.desktop.discardProjectDraft({ projectId: t.doc.projectId, path: t.doc.path }); if (r.ok) update(keyOf(t.doc), makeTab(r.value)); else setError(r.message); } catch { setError('Falha ao recuperar o arquivo. Seu rascunho permanece preservado.'); } finally { guard.current = false; setBusy(false); } }
  function useFile() { trackMutation(performUseFile); }
  async function performKeepMine() { const t = live.current.tabs.find(t => keyOf(t.doc) === live.current.active); if (guard.current || !t?.conflict?.hash) return; guard.current = true; setBusy(true); try { update(keyOf(t.doc), { doc: t.conflict, baseHash: t.conflict.hash, conflict: null, status: 'Edição conservada · revise antes de salvar' }); await writeDrafts(); } finally { guard.current = false; setBusy(false); } }
  function keepMine() { trackMutation(performKeepMine); }
  async function reveal(projectId: string, folder: string) { await choose(projectId); const paths = folder ? folder.split('/').map((_, i, segments) => segments.slice(0, i + 1).join('/')) : []; for (const path of paths) await tree({ projectId, path }); setExpanded(v => [...new Set([...v, ...paths.map(path => keyOf({ projectId, path }))])]); }
  const current = tabs.find(t => keyOf(t.doc) === active), root = catalog.view.projectId;
  function branch(folder: string, depth = 0): React.ReactNode { if (!root || depth > 20) return null; const ref = { projectId: root, path: folder }, data = trees[keyOf(ref)]; return data ? <>{data.entries.map(e => { const id = keyOf({ projectId: root, path: e.path }), expandedHere = expanded.includes(id); return <div key={e.path}><button className={`tree-entry ${active === id ? 'selected' : ''}`} style={{ paddingLeft: 16 + depth * 14 }} aria-label={`${e.kind === 'directory' ? 'Pasta' : 'Arquivo'} ${e.path}`} disabled={e.kind === 'link'} onClick={() => { if (e.kind !== 'directory') { void open({ projectId: root, path: e.path }); return; } setExpanded(v => expandedHere ? v.filter(k => k !== id) : [...v, id]); if (!expandedHere) void tree({ projectId: root, path: e.path }); }}><span className={`tree-chevron ${expandedHere ? 'expanded' : ''}`}>{e.kind === 'directory' && <Icon kind="chevron"/>}</span><Icon kind={e.kind === 'directory' ? 'folder' : e.kind === 'link' ? 'link' : fileIcon(e.name)}/><span className="tree-name">{e.name}</span></button>{expandedHere && branch(e.path, depth + 1)}</div>; })}{data.truncated && <p className="project-limit">Exibindo os primeiros 500 itens.</p>}</> : null; }
  return <div className="project-shell" data-area-ready={!loading} style={{ gridTemplateColumns: `${width}px 6px minmax(0,1fr)` }}>
    <aside className="project-sidebar"><header>EXPLORER <button aria-label="Adicionar projeto" onClick={() => void add()}><Icon kind="plus"/></button><button aria-label="Atualizar árvore" disabled={!root} onClick={() => root && void tree({ projectId: root, path: '' })}><Icon kind="refresh"/></button></header><div className="project-roots">{catalog.projects.map(p => <button key={p.id} className={root === p.id ? 'selected' : ''} aria-label={`Projeto ${p.name}`} onClick={() => void choose(p.id)}><Icon kind="folder"/>{p.name}{!p.available && <small> ausente</small>}</button>)}</div><div className="project-tree">{branch('')}</div><p className="project-sidebar-tip">Pastas locais, arquivos reais.<br/>Ctrl+S salva a aba ativa.</p></aside><div className="project-resizer" role="separator" aria-label="Largura do Explorer" aria-orientation="vertical" aria-valuemin={190} aria-valuemax={400} aria-valuenow={width} tabIndex={0} onDoubleClick={() => resize(260)} onKeyDown={e => { if (["ArrowLeft", "ArrowRight", "Home", "End"].includes(e.key)) { e.preventDefault(); resize(e.key === "Home" ? 190 : e.key === "End" ? 400 : width + (e.key === "ArrowRight" ? 10 : -10)); } }} onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); }} onPointerMove={e => { if (e.currentTarget.hasPointerCapture(e.pointerId)) resize(e.clientX - 68); }} onPointerUp={e => { if (e.currentTarget.hasPointerCapture(e.pointerId)) e.currentTarget.releasePointerCapture(e.pointerId); }}/>
    <main className="project-main"><header className="project-top"><span>APP ESTUDOS <b>/ PROJETOS</b></span><button onClick={() => void add()}>Abrir pasta ↗</button></header><div className="project-tabs">{tabs.map(t => <div key={keyOf(t.doc)} className={active === keyOf(t.doc) ? 'selected' : ''}><button aria-label={`Aba ${t.doc.path}`} onClick={() => { setActive(keyOf(t.doc)); live.current.active = keyOf(t.doc); void persist(); }}><Icon kind={fileIcon(t.doc.path)}/>{t.doc.path.split('/').at(-1)}{t.text !== t.doc.text && <span> ●</span>}</button><button aria-label={`Fechar ${t.doc.path}`} onClick={() => void closeTab(keyOf(t.doc))}><Icon kind="close"/></button></div>)}</div>
    {error && <div className="error-banner" role="alert">{error}<button aria-label="Fechar aviso" onClick={() => setError('')}>×</button></div>}
    {current ? <><div className="project-breadcrumb"><nav aria-label="Caminho do arquivo"><button onClick={() => void reveal(current.doc.projectId, "")}>{catalog.projects.find(p => p.id === current.doc.projectId)?.name}</button>{current.doc.path.split("/").map((segment, i, parts) => <span key={i}><Icon kind="chevron"/>{i < parts.length - 1 ? <button aria-label={`Abrir pasta ${parts.slice(0, i + 1).join("/")} na árvore`} onClick={() => void reveal(current.doc.projectId, parts.slice(0, i + 1).join("/"))}>{segment}</button> : <b>{segment}</b>}</span>)}</nav><button className="save-button" aria-label="Salvar arquivo" disabled={busy || current.doc.missing || Boolean(current.conflict)} onClick={() => void save()}>Salvar <kbd>Ctrl S</kbd></button></div>{current.conflict && <div className="conflict-box"><strong>Arquivo alterado fora do app</strong><p>Sua edição e a versão externa foram preservadas. Confira antes de continuar.</p><details><summary>Ver versão externa</summary><pre>{current.conflict.text}</pre></details><button disabled={busy} onClick={() => void useFile()}>Usar arquivo externo</button><button disabled={busy} onClick={() => void keepMine()}>Conservar minha edição para revisão</button></div>}{(current.doc.draft || current.text !== current.doc.text) && !current.conflict && <div className="draft-banner">{current.doc.draft ? "Rascunho recuperado" : "Rascunho local preservado"} <button disabled={busy || current.doc.missing} onClick={() => void useFile()}>Usar versão do arquivo</button></div>}<div className="project-editor-stage" ref={body}><ProjectEditor path={current.doc.path} busy={busy} key={active} text={current.text} onChange={change} onSave={() => void save()}/></div><footer className="project-status" role="status"><span>{current.status}</span><span>UTF-8{current.text.startsWith('\uFEFF') ? ' BOM' : ''} · {current.text.includes('\r\n') ? 'CRLF' : 'LF'} · TEXTO LOCAL</span></footer></> : <div className="project-welcome"><span><Icon kind="folder"/></span><h1>Seu projeto, no seu espaço.</h1><p>{loading ? 'Retomando seus arquivos…' : catalog.projects.length ? 'Escolha um arquivo na árvore para começar.' : 'Abra uma pasta do computador. Navegue, edite e retome suas abas.'}</p><button className="primary" onClick={() => void add()}>Abrir pasta de projeto →</button><small>Arquivos de texto UTF-8 de até 1 MiB.</small></div>}</main></div>;
}
