import { useEffect, useRef, useState } from 'react';
import type { TodayState } from '../shared/study';
import { Icon } from './Icon';
import { useSurfaceMotion } from './motion';
export function TodayWorkspace({activeArea,openSubject,review,search}:{activeArea:boolean;openSubject(id:string):Promise<void>;review():void;search():void}) {
  const [data,setData]=useState<TodayState|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);const host=useRef<HTMLDivElement>(null);useSurfaceMotion(host, String(revision),activeArea);
  useEffect(()=>{if(!activeArea)return;let stopped=false;async function load(){const r=await window.desktop.today();if(stopped)return;if(r.ok){setData(r.value);setError('');}else setError(r.message);}void load().catch(()=>setError('Não foi possível consultar o dia.'));const timer=setInterval(()=>void load().catch(()=>{}),15000);return()=>{stopped=true;clearInterval(timer);};},[activeArea,revision]);
  const last=data?.subjects.find(s=>s.id===data.lastSubjectId);
  return <div className="study-workspace today-workspace" data-area-ready="true" ref={host}><header><span className="eyebrow">UM PASSO DE CADA VEZ</span><h1>Seu dia, com espaço para estudar.</h1><p>{new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</p><button onClick={()=>setRevision(n=>n+1)}><Icon kind="refresh"/> Atualizar Hoje</button></header>{error&&<p role="alert">{error}</p>}<div className="today-stats"><div><small>FOCO REGISTRADO HOJE</small><strong>{Math.floor((data?.focusMs??0)/60000)}<span> min</span></strong><p>Seu tempo de estudo; pausas ficam fora.</p></div><div><small>REVISÕES PARA AGORA</small><strong>{data?.due??0}<span> cartões</span></strong><button onClick={review}>Abrir revisões <Icon kind="arrow"/></button></div><div><small>CONTINUAR DE ONDE PAROU</small><strong className="today-subject">{last?.name??'Sua primeira matéria'}</strong>{last?<button onClick={()=>void openSubject(last.id)}>Retomar mesa <Icon kind="arrow"/></button>:<button onClick={search}>Encontrar uma ação <kbd>Ctrl K</kbd></button>}</div></div><section><div className="study-section-heading"><h2>Próximos passos</h2><span>{data?.tasks.length??0} tarefas abertas</span></div>{data&&!data.tasks.length&&<p className="study-muted">Seu checklist está livre. Crie uma tarefa na mesa da matéria para planejar o próximo passo.</p>}<div className="today-tasks">{data?.tasks.map(task=><button key={task.id} onClick={()=>void openSubject(task.subjectId)}><Icon kind="check"/><span><strong>{task.text}</strong><small>{task.subject} · {task.total?`${task.done}/${task.total} etapas`:'Sem etapas ainda'}</small></span><Icon kind="arrow"/></button>)}</div></section><section><h2>Suas matérias</h2><div className="today-subjects">{data?.subjects.map(s=><button key={s.id} onClick={()=>void openSubject(s.id)}><Icon kind="book"/>{s.name}<Icon kind="arrow"/></button>)}</div></section></div>;
}
