import { useRef,type ReactNode,type PointerEvent,type KeyboardEvent } from 'react';
import { WORKSPACE_AREAS,type WorkspaceArea,type WorkspaceLayout } from '../shared/workspace';
export function WorkspaceFrame({layout,focused,pending,cinema,choose,close,single,resize,saveSizes,focus,children,tools}:{layout:WorkspaceLayout;focused:number;pending:boolean;cinema:boolean;choose(area:WorkspaceArea,index:number):void;close(index:number):void;single():void;resize(sizes:number[]):void;saveSizes():void;focus(area:string):void;children:ReactNode;tools:ReactNode}){
 const body=useRef<HTMLDivElement>(null),drag=useRef<{x:number;sizes:number[];index:number;width:number}|null>(null);
 function change(index:number,delta:number,sizes=layout.sizes){const next=[...sizes],sum=sizes[index]+sizes[index+1];next[index]=Math.min(sum-20,Math.max(20,sizes[index]+delta));next[index+1]=sum-next[index];resize(next);}
 function start(e:PointerEvent<HTMLDivElement>,index:number){if(e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,sizes:[...layout.sizes],index,width:body.current!.clientWidth};}
 function move(e:PointerEvent<HTMLDivElement>){const d=drag.current;if(d)change(d.index,(e.clientX-d.x)/d.width*100,d.sizes);}
 function end(e:PointerEvent<HTMLDivElement>){if(!drag.current)return;drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);saveSizes();}
 function focusTarget(target:EventTarget|null){const area=(target as HTMLElement|null)?.closest<HTMLElement>('[data-area]')?.dataset.area;if(area)focus(area);}
 function key(e:KeyboardEvent<HTMLDivElement>,index:number){if(!['ArrowLeft','ArrowRight','Home'].includes(e.key))return;e.preventDefault();const delta=e.key==='Home'?(layout.sizes[index]+layout.sizes[index+1])/2-layout.sizes[index]:(e.key==='ArrowLeft'?-1:1)*(e.shiftKey?5:2);change(index,delta);saveSizes();}
 return <div className="workspace-frame"><header className="workspace-controls" inert={cinema}><div className="workspace-pane-choices">{layout.panes.map((area,i)=><div key={i} className={i===focused?'selected':''}><label><span>{String(i+1).padStart(2,'0')}</span><select aria-label={`Módulo ${i+1}`} disabled={pending} value={area} onFocus={()=>focus(area)} onChange={e=>choose(e.target.value as WorkspaceArea,i)}>{WORKSPACE_AREAS.map(a=><option key={a.id} value={a.id} disabled={layout.panes.includes(a.id)&&a.id!==area}>{a.name}</option>)}</select></label>{layout.panes.length>1&&<button aria-label={`Fechar módulo ${i+1}`} title="Fechar módulo" disabled={pending} onClick={()=>close(i)}>×</button>}</div>)}</div><div className="workspace-layout-actions">{layout.panes.length>1&&<button onClick={single} disabled={pending}>Tela única</button>}<details className="workspace-add"><summary aria-disabled={layout.panes.length>=3||pending}>+ Módulo</summary><div role="menu" aria-label="Adicionar módulo">{WORKSPACE_AREAS.map(a=><button role="menuitem" key={a.id} disabled={pending||layout.panes.length>=3||layout.panes.includes(a.id)} onClick={e=>{choose(a.id,layout.panes.length);e.currentTarget.closest('details')!.open=false;}}>{a.name}</button>)}</div></details></div></header><div className="workspace-body" ref={body} onPointerDownCapture={e=>focusTarget(e.target)} onFocusCapture={e=>focusTarget(e.target)}>{children}{layout.sizes.slice(0,-1).map((size,i)=><div key={i} className="workspace-divider" style={{left:`${layout.sizes.slice(0,i+1).reduce((a,b)=>a+b,0)}%`}} role="separator" tabIndex={cinema?-1:0} aria-label={`Largura do módulo ${i+1}`} aria-orientation="vertical" aria-valuemin={20} aria-valuemax={Math.round(size+layout.sizes[i+1]-20)} aria-valuenow={Math.round(size)} onPointerDown={e=>start(e,i)} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onKeyDown={e=>key(e,i)}/>)}</div>{tools}</div>;
}
